{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d2852f88",
   "metadata": {},
   "source": [
    "# Neural Networks with PyTorch: Classification & Regression\n",
    "## **SOLUTIONS**\n",
    "\n",
    "**Overview:**\n",
    "1. **Classification** on the Wine dataset (real-world data with 3 classes).\n",
    "2. **Regression** on the California Housing dataset (predict house value).\n",
    "3. Building **single-layer** and **two-layer** MLPs.\n",
    "4. Experimenting with **different batch sizes** and **learning rates** to observe effects on performance."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e2ca06b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import time\n",
    "\n",
    "from sklearn.datasets import load_wine, fetch_california_housing, load_iris, load_diabetes\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader, TensorDataset\n",
    "\n",
    "from sklearn.base import BaseEstimator, RegressorMixin, ClassifierMixin\n",
    "from sklearn.inspection import permutation_importance\n",
    "\n",
    "\n",
    "class PyTorchClassifierWrapper(BaseEstimator, ClassifierMixin):\n",
    "    def __init__(self, model, device='cpu'):\n",
    "        self.model = model\n",
    "        self.device = device\n",
    "        self.classes_ = None\n",
    "    \n",
    "    def fit(self, X, y):\n",
    "        self.classes_ = np.unique(y)\n",
    "        return self\n",
    "    \n",
    "    def predict(self, X):\n",
    "        self.model.eval()\n",
    "        with torch.no_grad():\n",
    "            X_tensor = torch.FloatTensor(X).to(self.device)\n",
    "            outputs = self.model(X_tensor)\n",
    "            _, predicted = torch.max(outputs, 1)\n",
    "        return predicted.cpu().numpy()\n",
    "    \n",
    "    def predict_proba(self, X):\n",
    "        self.model.eval()\n",
    "        with torch.no_grad():\n",
    "            X_tensor = torch.FloatTensor(X).to(self.device)\n",
    "            outputs = self.model(X_tensor)\n",
    "            proba = torch.softmax(outputs, dim=1)\n",
    "        return proba.cpu().numpy()\n",
    "\n",
    "\n",
    "class PyTorchRegressorWrapper(BaseEstimator, RegressorMixin):\n",
    "    def __init__(self, model, device='cpu'):\n",
    "        self.model = model\n",
    "        self.device = device\n",
    "    \n",
    "    def fit(self, X, y):\n",
    "        return self\n",
    "    \n",
    "    def predict(self, X):\n",
    "        self.model.eval()\n",
    "        with torch.no_grad():\n",
    "            X_tensor = torch.FloatTensor(X).to(self.device)\n",
    "            outputs = self.model(X_tensor)\n",
    "        return outputs.cpu().numpy().flatten()\n",
    "\n",
    "\n",
    "# For reproducibility\n",
    "np.random.seed(42)\n",
    "torch.manual_seed(42)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed(42)\n",
    "\n",
    "# Set device\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"PyTorch version: {torch.__version__}\")\n",
    "print(f\"Using device: {device}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5fd82dd8",
   "metadata": {},
   "source": [
    "# Activation Functions in PyTorch\n",
    "\n",
    "| **Activation** | **PyTorch Syntax** | **Use Case** |\n",
    "|----------------|-------------------|---------------|\n",
    "| **Sigmoid** | `nn.Sigmoid()` | Output layer for **binary classification** |\n",
    "| **Tanh** | `nn.Tanh()` | Hidden layers (zero-centered) |\n",
    "| **ReLU** | `nn.ReLU()` | Default for **hidden layers** |\n",
    "| **Leaky ReLU** | `nn.LeakyReLU(0.01)` | Avoids **dying ReLU** |\n",
    "| **ELU** | `nn.ELU()` | Smoother than ReLU |\n",
    "| **Softmax** | `nn.Softmax(dim=1)` | Output for **multi-class classification** |\n",
    "| **Linear** | *(no activation)* | Output for **regression** |"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a6b7c8d9",
   "metadata": {},
   "source": [
    "## XOR Problem: Single vs. Two-Layer ANN\n",
    "\n",
    "The XOR problem demonstrates why we need **hidden layers**. XOR is not **linearly separable**, so a single-layer perceptron cannot solve it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "xor_data",
   "metadata": {},
   "outputs": [],
   "source": [
    "# XOR Dataset\n",
    "X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)\n",
    "y_xor = np.array([[0], [1], [1], [0]], dtype=np.float32)\n",
    "\n",
    "print(\"XOR Input:\")\n",
    "print(X_xor)\n",
    "print(\"\\nXOR Output:\")\n",
    "print(y_xor.flatten())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "xor_single",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Single-layer ANN - Cannot solve XOR!\n",
    "class SingleLayerXOR(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(SingleLayerXOR, self).__init__()\n",
    "        self.fc = nn.Linear(2, 1)\n",
    "        self.sigmoid = nn.Sigmoid()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.sigmoid(self.fc(x))\n",
    "\n",
    "def train_xor_model(model, X, y, epochs=500, lr=0.5):\n",
    "    X_tensor = torch.FloatTensor(X)\n",
    "    y_tensor = torch.FloatTensor(y)\n",
    "    \n",
    "    criterion = nn.BCELoss()\n",
    "    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)\n",
    "    \n",
    "    history = {'loss': [], 'accuracy': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_tensor)\n",
    "        loss = criterion(outputs, y_tensor)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        predicted = (outputs > 0.5).float()\n",
    "        accuracy = (predicted == y_tensor).float().mean().item()\n",
    "        history['loss'].append(loss.item())\n",
    "        history['accuracy'].append(accuracy)\n",
    "    \n",
    "    return history\n",
    "\n",
    "model_single_xor = SingleLayerXOR()\n",
    "history_single_xor = train_xor_model(model_single_xor, X_xor, y_xor)\n",
    "\n",
    "model_single_xor.eval()\n",
    "with torch.no_grad():\n",
    "    preds_single = model_single_xor(torch.FloatTensor(X_xor))\n",
    "    acc_single = ((preds_single > 0.5).float() == torch.FloatTensor(y_xor)).float().mean().item()\n",
    "\n",
    "print(f\"Single-Layer ANN Accuracy: {acc_single:.4f}\")\n",
    "print(\"Predictions:\", np.round(preds_single.numpy().flatten(), 3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "xor_two_layer",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Two-layer ANN - Can solve XOR!\n",
    "class TwoLayerXOR(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(TwoLayerXOR, self).__init__()\n",
    "        self.fc1 = nn.Linear(2, 64)\n",
    "        self.tanh = nn.Tanh()\n",
    "        self.fc2 = nn.Linear(64, 1)\n",
    "        self.sigmoid = nn.Sigmoid()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.tanh(self.fc1(x))\n",
    "        x = self.sigmoid(self.fc2(x))\n",
    "        return x\n",
    "\n",
    "model_two_xor = TwoLayerXOR()\n",
    "history_two_xor = train_xor_model(model_two_xor, X_xor, y_xor)\n",
    "\n",
    "model_two_xor.eval()\n",
    "with torch.no_grad():\n",
    "    preds_two = model_two_xor(torch.FloatTensor(X_xor))\n",
    "    acc_two = ((preds_two > 0.5).float() == torch.FloatTensor(y_xor)).float().mean().item()\n",
    "\n",
    "print(f\"Two-Layer ANN Accuracy: {acc_two:.4f}\")\n",
    "print(\"Predictions:\", np.round(preds_two.numpy().flatten(), 3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "xor_plot",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.plot(history_single_xor['accuracy'], label='Single Layer')\n",
    "plt.plot(history_two_xor['accuracy'], label='Two Layer')\n",
    "plt.title('Training Accuracy on XOR')\n",
    "plt.xlabel('Epoch')\n",
    "plt.ylabel('Accuracy')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e821e318",
   "metadata": {},
   "source": [
    "---\n",
    "## Part 1: Classification on the Wine Dataset\n",
    "\n",
    "The Wine dataset contains:\n",
    "- 178 samples, 13 features, 3 classes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "82f62c0e",
   "metadata": {},
   "outputs": [],
   "source": [
    "wine = load_wine()\n",
    "X_wine, y_wine = wine.data, wine.target\n",
    "\n",
    "print(\"Feature matrix shape:\", X_wine.shape)\n",
    "print(\"Classes:\", wine.target_names)\n",
    "\n",
    "df_wine = pd.DataFrame(X_wine, columns=wine.feature_names)\n",
    "df_wine['target'] = y_wine\n",
    "df_wine.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "wine_split",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_wine, X_test_wine, y_train_wine, y_test_wine = train_test_split(\n",
    "    X_wine, y_wine, test_size=0.2, random_state=42, stratify=y_wine\n",
    ")\n",
    "\n",
    "scaler_wine = StandardScaler()\n",
    "X_train_wine_scaled = scaler_wine.fit_transform(X_train_wine)\n",
    "X_test_wine_scaled = scaler_wine.transform(X_test_wine)\n",
    "\n",
    "print(f\"Training: {X_train_wine_scaled.shape[0]}, Test: {X_test_wine_scaled.shape[0]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "wine_single_layer",
   "metadata": {},
   "outputs": [],
   "source": [
    "class SingleLayerClassifier(nn.Module):\n",
    "    def __init__(self, input_size, hidden_size, num_classes):\n",
    "        super(SingleLayerClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.relu = nn.ReLU()\n",
    "        self.fc2 = nn.Linear(hidden_size, num_classes)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu(self.fc1(x))\n",
    "        x = self.fc2(x)\n",
    "        return x\n",
    "\n",
    "\n",
    "def train_classifier(model, train_loader, val_loader, epochs, lr, patience=30, device='cpu'):\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)\n",
    "    \n",
    "    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}\n",
    "    best_val_acc, best_model_state, patience_counter = 0.0, None, 0\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        train_loss, train_correct, train_total = 0.0, 0, 0\n",
    "        \n",
    "        for X_batch, y_batch in train_loader:\n",
    "            X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model(X_batch)\n",
    "            loss = criterion(outputs, y_batch)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            \n",
    "            train_loss += loss.item() * X_batch.size(0)\n",
    "            _, predicted = torch.max(outputs, 1)\n",
    "            train_total += y_batch.size(0)\n",
    "            train_correct += (predicted == y_batch).sum().item()\n",
    "        \n",
    "        train_loss /= train_total\n",
    "        train_acc = train_correct / train_total\n",
    "        \n",
    "        model.eval()\n",
    "        val_loss, val_correct, val_total = 0.0, 0, 0\n",
    "        with torch.no_grad():\n",
    "            for X_batch, y_batch in val_loader:\n",
    "                X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "                outputs = model(X_batch)\n",
    "                loss = criterion(outputs, y_batch)\n",
    "                val_loss += loss.item() * X_batch.size(0)\n",
    "                _, predicted = torch.max(outputs, 1)\n",
    "                val_total += y_batch.size(0)\n",
    "                val_correct += (predicted == y_batch).sum().item()\n",
    "        \n",
    "        val_loss /= val_total\n",
    "        val_acc = val_correct / val_total\n",
    "        \n",
    "        history['train_loss'].append(train_loss)\n",
    "        history['train_acc'].append(train_acc)\n",
    "        history['val_loss'].append(val_loss)\n",
    "        history['val_acc'].append(val_acc)\n",
    "        \n",
    "        if val_acc > best_val_acc:\n",
    "            best_val_acc = val_acc\n",
    "            best_model_state = model.state_dict().copy()\n",
    "            patience_counter = 0\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            if patience_counter >= patience:\n",
    "                print(f\"Early stopping at epoch {epoch + 1}\")\n",
    "                break\n",
    "    \n",
    "    if best_model_state:\n",
    "        model.load_state_dict(best_model_state)\n",
    "    print(\"Training complete.\")\n",
    "    return history"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "wine_train_single",
   "metadata": {},
   "outputs": [],
   "source": [
    "lr, batch_size_val, epochs_val = 0.01, 16, 1000\n",
    "\n",
    "X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(\n",
    "    X_train_wine_scaled, y_train_wine, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "train_dataset = TensorDataset(torch.FloatTensor(X_train_split), torch.LongTensor(y_train_split))\n",
    "val_dataset = TensorDataset(torch.FloatTensor(X_val_split), torch.LongTensor(y_val_split))\n",
    "train_loader = DataLoader(train_dataset, batch_size=batch_size_val, shuffle=True)\n",
    "val_loader = DataLoader(val_dataset, batch_size=batch_size_val, shuffle=False)\n",
    "\n",
    "input_size = X_train_wine_scaled.shape[1]\n",
    "num_classes = len(np.unique(y_train_wine))\n",
    "\n",
    "model_single_wine = SingleLayerClassifier(input_size, hidden_size=32, num_classes=num_classes)\n",
    "history_single_wine = train_classifier(model_single_wine, train_loader, val_loader, \n",
    "                                        epochs=epochs_val, lr=lr, patience=30, device=device)\n",
    "\n",
    "model_single_wine.eval()\n",
    "with torch.no_grad():\n",
    "    test_outputs = model_single_wine(torch.FloatTensor(X_test_wine_scaled).to(device))\n",
    "    _, test_preds = torch.max(test_outputs, 1)\n",
    "    test_acc = (test_preds.cpu().numpy() == y_test_wine).mean()\n",
    "\n",
    "print(f\"Single-Layer MLP Test Accuracy: {test_acc:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "wine_two_layer_def",
   "metadata": {},
   "outputs": [],
   "source": [
    "class TwoLayerClassifier(nn.Module):\n",
    "    def __init__(self, input_size, hidden1_size, hidden2_size, num_classes):\n",
    "        super(TwoLayerClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden1_size)\n",
    "        self.relu1 = nn.ReLU()\n",
    "        self.fc2 = nn.Linear(hidden1_size, hidden2_size)\n",
    "        self.relu2 = nn.ReLU()\n",
    "        self.fc3 = nn.Linear(hidden2_size, num_classes)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu1(self.fc1(x))\n",
    "        x = self.relu2(self.fc2(x))\n",
    "        x = self.fc3(x)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "regression_header",
   "metadata": {},
   "source": [
    "---\n",
    "## Part 2: Regression on the California Housing Dataset\n",
    "\n",
    "20,640 samples, 8 features, target: median house value"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cal_load",
   "metadata": {},
   "outputs": [],
   "source": [
    "cal_housing = fetch_california_housing()\n",
    "X_cal, y_cal = cal_housing.data, cal_housing.target\n",
    "print(f\"Shape: {X_cal.shape}, Features: {cal_housing.feature_names}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cal_split",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_cal, X_test_cal, y_train_cal, y_test_cal = train_test_split(X_cal, y_cal, test_size=0.2, random_state=42)\n",
    "scaler_cal = StandardScaler()\n",
    "X_train_cal_scaled = scaler_cal.fit_transform(X_train_cal)\n",
    "X_test_cal_scaled = scaler_cal.transform(X_test_cal)\n",
    "print(f\"Training: {X_train_cal_scaled.shape[0]}, Test: {X_test_cal_scaled.shape[0]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cal_regressor_def",
   "metadata": {},
   "outputs": [],
   "source": [
    "class SingleLayerRegressor(nn.Module):\n",
    "    def __init__(self, input_size, hidden_size):\n",
    "        super(SingleLayerRegressor, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.relu = nn.ReLU()\n",
    "        self.fc2 = nn.Linear(hidden_size, 1)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.fc2(self.relu(self.fc1(x)))\n",
    "\n",
    "\n",
    "def train_regressor(model, train_loader, val_loader, epochs, lr, device='cpu', verbose=True):\n",
    "    model = model.to(device)\n",
    "    criterion = nn.MSELoss()\n",
    "    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_mae': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        train_loss, train_total = 0.0, 0\n",
    "        for X_batch, y_batch in train_loader:\n",
    "            X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model(X_batch).squeeze()\n",
    "            loss = criterion(outputs, y_batch)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            train_loss += loss.item() * X_batch.size(0)\n",
    "            train_total += X_batch.size(0)\n",
    "        \n",
    "        model.eval()\n",
    "        val_loss, val_mae, val_total = 0.0, 0.0, 0\n",
    "        with torch.no_grad():\n",
    "            for X_batch, y_batch in val_loader:\n",
    "                X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "                outputs = model(X_batch).squeeze()\n",
    "                val_loss += criterion(outputs, y_batch).item() * X_batch.size(0)\n",
    "                val_mae += torch.abs(outputs - y_batch).sum().item()\n",
    "                val_total += X_batch.size(0)\n",
    "        \n",
    "        history['train_loss'].append(train_loss / train_total)\n",
    "        history['val_loss'].append(val_loss / val_total)\n",
    "        history['val_mae'].append(val_mae / val_total)\n",
    "        \n",
    "        if verbose and (epoch + 1) % 10 == 0:\n",
    "            print(f\"Epoch {epoch+1}/{epochs} - Val MAE: {val_mae/val_total:.4f}\")\n",
    "    \n",
    "    return history"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cal_data_prep",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_cal_split, X_val_cal_split, y_train_cal_split, y_val_cal_split = train_test_split(\n",
    "    X_train_cal_scaled, y_train_cal, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "train_dataset_cal = TensorDataset(torch.FloatTensor(X_train_cal_split), torch.FloatTensor(y_train_cal_split))\n",
    "val_dataset_cal = TensorDataset(torch.FloatTensor(X_val_cal_split), torch.FloatTensor(y_val_cal_split))\n",
    "\n",
    "input_size_cal = X_train_cal_scaled.shape[1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cal_two_layer",
   "metadata": {},
   "outputs": [],
   "source": [
    "class TwoLayerRegressor(nn.Module):\n",
    "    def __init__(self, input_size):\n",
    "        super(TwoLayerRegressor, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, 32)\n",
    "        self.tanh = nn.Tanh()\n",
    "        self.fc2 = nn.Linear(32, 16)\n",
    "        self.relu = nn.ReLU()\n",
    "        self.fc3 = nn.Linear(16, 1)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.tanh(self.fc1(x))\n",
    "        x = self.relu(self.fc2(x))\n",
    "        return self.fc3(x)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "exercises_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Exercise Solutions"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex1_header",
   "metadata": {},
   "source": [
    "## Exercise 1: Logic Gates - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex1_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 1: Logic Gates - SOLUTION\n",
    "\n",
    "# AND gate: output is 1 only when BOTH inputs are 1\n",
    "X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)\n",
    "y_and = np.array([[0], [0], [0], [1]], dtype=np.float32)\n",
    "\n",
    "# OR gate: output is 1 when AT LEAST ONE input is 1\n",
    "X_or = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)\n",
    "y_or = np.array([[0], [1], [1], [1]], dtype=np.float32)\n",
    "\n",
    "# Single-layer network for logic gates\n",
    "class SingleLayerGate(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(SingleLayerGate, self).__init__()\n",
    "        self.fc = nn.Linear(2, 1)\n",
    "        self.sigmoid = nn.Sigmoid()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.sigmoid(self.fc(x))\n",
    "\n",
    "def train_gate(model, X, y, epochs=1000, lr=1.0):\n",
    "    X_tensor = torch.FloatTensor(X)\n",
    "    y_tensor = torch.FloatTensor(y)\n",
    "    criterion = nn.BCELoss()\n",
    "    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_tensor)\n",
    "        loss = criterion(outputs, y_tensor)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "    \n",
    "    return model\n",
    "\n",
    "# Train AND gate\n",
    "print(\"=\" * 50)\n",
    "print(\"AND Gate\")\n",
    "print(\"=\" * 50)\n",
    "model_and = SingleLayerGate()\n",
    "model_and = train_gate(model_and, X_and, y_and)\n",
    "\n",
    "model_and.eval()\n",
    "with torch.no_grad():\n",
    "    preds_and = model_and(torch.FloatTensor(X_and))\n",
    "    acc_and = ((preds_and > 0.5).float() == torch.FloatTensor(y_and)).float().mean().item()\n",
    "\n",
    "print(f\"AND Gate Accuracy: {acc_and:.4f}\")\n",
    "print(\"Input -> Output (Predicted)\")\n",
    "for i in range(4):\n",
    "    print(f\"{X_and[i]} -> {y_and[i][0]:.0f} ({preds_and[i].item():.3f})\")\n",
    "\n",
    "# Print learned weights\n",
    "print(f\"\\nLearned weights: {model_and.fc.weight.data.numpy().flatten()}\")\n",
    "print(f\"Learned bias: {model_and.fc.bias.data.numpy()[0]:.4f}\")\n",
    "\n",
    "# Train OR gate\n",
    "print(\"\\n\" + \"=\" * 50)\n",
    "print(\"OR Gate\")\n",
    "print(\"=\" * 50)\n",
    "model_or = SingleLayerGate()\n",
    "model_or = train_gate(model_or, X_or, y_or)\n",
    "\n",
    "model_or.eval()\n",
    "with torch.no_grad():\n",
    "    preds_or = model_or(torch.FloatTensor(X_or))\n",
    "    acc_or = ((preds_or > 0.5).float() == torch.FloatTensor(y_or)).float().mean().item()\n",
    "\n",
    "print(f\"OR Gate Accuracy: {acc_or:.4f}\")\n",
    "print(\"Input -> Output (Predicted)\")\n",
    "for i in range(4):\n",
    "    print(f\"{X_or[i]} -> {y_or[i][0]:.0f} ({preds_or[i].item():.3f})\")\n",
    "\n",
    "# Print learned weights\n",
    "print(f\"\\nLearned weights: {model_or.fc.weight.data.numpy().flatten()}\")\n",
    "print(f\"Learned bias: {model_or.fc.bias.data.numpy()[0]:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex1_answer",
   "metadata": {},
   "source": [
    "**Explanation: Why can single layer solve AND/OR but not XOR?**\n",
    "\n",
    "AND and OR gates are **linearly separable** - you can draw a single straight line to separate the 0s from the 1s in 2D space.\n",
    "\n",
    "- **AND Gate**: The single output of 1 at (1,1) can be separated from the three 0s by a line like `x1 + x2 = 1.5`\n",
    "- **OR Gate**: The single output of 0 at (0,0) can be separated from the three 1s by a line like `x1 + x2 = 0.5`\n",
    "\n",
    "**XOR is NOT linearly separable**: The 1s are at (0,1) and (1,0), while the 0s are at (0,0) and (1,1). No single straight line can separate them - you would need a curved or complex boundary, which requires a hidden layer to create."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex2_header",
   "metadata": {},
   "source": [
    "## Exercise 2: Minimum Hidden Neurons for XOR - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex2_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 2: Minimum Hidden Neurons - SOLUTION\n",
    "\n",
    "class VariableXOR(nn.Module):\n",
    "    def __init__(self, hidden_neurons):\n",
    "        super(VariableXOR, self).__init__()\n",
    "        self.fc1 = nn.Linear(2, hidden_neurons)\n",
    "        self.tanh = nn.Tanh()\n",
    "        self.fc2 = nn.Linear(hidden_neurons, 1)\n",
    "        self.sigmoid = nn.Sigmoid()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.sigmoid(self.fc2(self.tanh(self.fc1(x))))\n",
    "\n",
    "def test_xor_hidden_size(hidden_neurons, num_trials=5, epochs=1000, lr=0.5):\n",
    "    \"\"\"\n",
    "    Test if a given number of hidden neurons can solve XOR.\n",
    "    Returns number of successful trials (100% accuracy).\n",
    "    \"\"\"\n",
    "    X_tensor = torch.FloatTensor(X_xor)\n",
    "    y_tensor = torch.FloatTensor(y_xor)\n",
    "    successes = 0\n",
    "    \n",
    "    for trial in range(num_trials):\n",
    "        # Reset seed for different initialization each trial\n",
    "        torch.manual_seed(trial * 100 + hidden_neurons)\n",
    "        \n",
    "        model = VariableXOR(hidden_neurons)\n",
    "        criterion = nn.BCELoss()\n",
    "        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9)\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model(X_tensor)\n",
    "            loss = criterion(outputs, y_tensor)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            preds = model(X_tensor)\n",
    "            accuracy = ((preds > 0.5).float() == y_tensor).float().mean().item()\n",
    "        \n",
    "        if accuracy == 1.0:\n",
    "            successes += 1\n",
    "    \n",
    "    return successes\n",
    "\n",
    "# Test different hidden sizes\n",
    "hidden_sizes = [2, 3, 4, 8]\n",
    "num_trials = 5\n",
    "\n",
    "print(\"Testing minimum hidden neurons for XOR\")\n",
    "print(\"=\" * 50)\n",
    "print(f\"{'Hidden Neurons':<15} {'Successes':<12} {'Success Rate'}\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "results = {}\n",
    "for h in hidden_sizes:\n",
    "    successes = test_xor_hidden_size(h, num_trials=num_trials)\n",
    "    results[h] = successes\n",
    "    print(f\"{h:<15} {successes}/{num_trials:<10} {successes/num_trials*100:.0f}%\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 50)\n",
    "print(\"CONCLUSION:\")\n",
    "min_neurons = min([h for h, s in results.items() if s == num_trials], default=None)\n",
    "if min_neurons:\n",
    "    print(f\"Minimum hidden neurons that consistently solves XOR: {min_neurons}\")\n",
    "else:\n",
    "    print(\"No configuration consistently solved XOR in all trials.\")\n",
    "    min_neurons = min([h for h, s in results.items() if s > 0], default=None)\n",
    "    if min_neurons:\n",
    "        print(f\"Minimum that sometimes works: {min_neurons}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex2_explanation",
   "metadata": {},
   "source": [
    "**Explanation:**\n",
    "\n",
    "Theoretically, **2 hidden neurons** is the minimum required to solve XOR, as XOR can be decomposed into:\n",
    "- XOR(x1, x2) = AND(OR(x1, x2), NAND(x1, x2))\n",
    "\n",
    "Each hidden neuron can learn one of these functions. However, in practice, with random initialization and gradient descent, 2 neurons may not always converge to the correct solution. With more neurons (3-4), the network has more flexibility and is more likely to find a working solution."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex3_header",
   "metadata": {},
   "source": [
    "## Exercise 3: Learning Rate Comparison - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex3_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 3: Learning Rate Comparison - SOLUTION\n",
    "\n",
    "learning_rates = [0.001, 0.01, 0.1, 0.5]\n",
    "lr_results = {}\n",
    "\n",
    "# Create data loaders\n",
    "train_loader_lr = DataLoader(train_dataset, batch_size=16, shuffle=True)\n",
    "val_loader_lr = DataLoader(val_dataset, batch_size=16, shuffle=False)\n",
    "\n",
    "for lr_test in learning_rates:\n",
    "    print(f\"\\nTraining with lr={lr_test}\")\n",
    "    torch.manual_seed(42)  # Reset seed for fair comparison\n",
    "    \n",
    "    model_lr = TwoLayerClassifier(input_size, 32, 16, num_classes)\n",
    "    \n",
    "    # Train without early stopping to see full behavior\n",
    "    model_lr = model_lr.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.SGD(model_lr.parameters(), lr=lr_test, momentum=0.9)\n",
    "    \n",
    "    history = {'train_acc': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(100):\n",
    "        model_lr.train()\n",
    "        train_correct, train_total = 0, 0\n",
    "        for X_batch, y_batch in train_loader_lr:\n",
    "            X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model_lr(X_batch)\n",
    "            loss = criterion(outputs, y_batch)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            _, predicted = torch.max(outputs, 1)\n",
    "            train_total += y_batch.size(0)\n",
    "            train_correct += (predicted == y_batch).sum().item()\n",
    "        \n",
    "        model_lr.eval()\n",
    "        val_correct, val_total = 0, 0\n",
    "        with torch.no_grad():\n",
    "            for X_batch, y_batch in val_loader_lr:\n",
    "                X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "                outputs = model_lr(X_batch)\n",
    "                _, predicted = torch.max(outputs, 1)\n",
    "                val_total += y_batch.size(0)\n",
    "                val_correct += (predicted == y_batch).sum().item()\n",
    "        \n",
    "        history['train_acc'].append(train_correct / train_total)\n",
    "        history['val_acc'].append(val_correct / val_total)\n",
    "    \n",
    "    # Test accuracy\n",
    "    model_lr.eval()\n",
    "    with torch.no_grad():\n",
    "        test_outputs = model_lr(torch.FloatTensor(X_test_wine_scaled).to(device))\n",
    "        _, test_preds = torch.max(test_outputs, 1)\n",
    "        test_acc = (test_preds.cpu().numpy() == y_test_wine).mean()\n",
    "    \n",
    "    lr_results[lr_test] = {\n",
    "        'history': history,\n",
    "        'test_acc': test_acc\n",
    "    }\n",
    "    print(f\"  Final test accuracy: {test_acc:.4f}\")\n",
    "\n",
    "# Plot comparison\n",
    "plt.figure(figsize=(12, 5))\n",
    "\n",
    "plt.subplot(1, 2, 1)\n",
    "for lr_test in learning_rates:\n",
    "    plt.plot(lr_results[lr_test]['history']['val_acc'], label=f'lr={lr_test}')\n",
    "plt.xlabel('Epoch')\n",
    "plt.ylabel('Validation Accuracy')\n",
    "plt.title('Validation Accuracy vs Learning Rate')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "lrs = list(lr_results.keys())\n",
    "test_accs = [lr_results[lr]['test_acc'] for lr in lrs]\n",
    "plt.bar([str(lr) for lr in lrs], test_accs, color=['blue', 'green', 'orange', 'red'])\n",
    "plt.xlabel('Learning Rate')\n",
    "plt.ylabel('Test Accuracy')\n",
    "plt.title('Final Test Accuracy')\n",
    "plt.ylim(0, 1.1)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Summary table\n",
    "print(\"\\nSummary:\")\n",
    "print(\"-\" * 40)\n",
    "print(f\"{'Learning Rate':<15} {'Test Accuracy'}\")\n",
    "print(\"-\" * 40)\n",
    "for lr_test in learning_rates:\n",
    "    print(f\"{lr_test:<15} {lr_results[lr_test]['test_acc']:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex3_answer",
   "metadata": {},
   "source": [
    "**Explanation:**\n",
    "\n",
    "- **lr=0.001**: Too slow - may not converge in 100 epochs, accuracy improves very gradually\n",
    "- **lr=0.01**: Good balance - converges steadily to good accuracy\n",
    "- **lr=0.1**: Faster convergence but may oscillate more\n",
    "- **lr=0.5**: Too high - may overshoot optima, causing unstable training or divergence\n",
    "\n",
    "**Best learning rate**: Typically around 0.01-0.1 for this problem. The optimal LR balances:\n",
    "1. Fast enough convergence (not too slow)\n",
    "2. Stable training (not overshooting)\n",
    "3. Good final accuracy (reaching good minima)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex4_header",
   "metadata": {},
   "source": [
    "## Exercise 4: Batch Size Experiment - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex4_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 4: Batch Size Experiment - SOLUTION\n",
    "\n",
    "batch_sizes = [8, 32, 128, 512]\n",
    "batch_results = {}\n",
    "\n",
    "for bs in batch_sizes:\n",
    "    print(f\"\\nTraining with batch_size={bs}\")\n",
    "    torch.manual_seed(42)\n",
    "    \n",
    "    # Create data loaders with this batch size\n",
    "    train_loader_bs = DataLoader(train_dataset_cal, batch_size=bs, shuffle=True)\n",
    "    val_loader_bs = DataLoader(val_dataset_cal, batch_size=bs, shuffle=False)\n",
    "    \n",
    "    model_bs = TwoLayerRegressor(input_size_cal)\n",
    "    \n",
    "    # Time the training\n",
    "    start_time = time.time()\n",
    "    history_bs = train_regressor(model_bs, train_loader_bs, val_loader_bs,\n",
    "                                  epochs=50, lr=0.005, device=device, verbose=False)\n",
    "    elapsed_time = time.time() - start_time\n",
    "    \n",
    "    # Evaluate on test set\n",
    "    model_bs.eval()\n",
    "    with torch.no_grad():\n",
    "        test_preds = model_bs(torch.FloatTensor(X_test_cal_scaled).to(device)).squeeze().cpu().numpy()\n",
    "        test_mae = np.mean(np.abs(test_preds - y_test_cal))\n",
    "    \n",
    "    batch_results[bs] = {\n",
    "        'time': elapsed_time,\n",
    "        'test_mae': test_mae,\n",
    "        'history': history_bs\n",
    "    }\n",
    "    print(f\"  Time: {elapsed_time:.2f}s, Test MAE: {test_mae:.4f}\")\n",
    "\n",
    "# Plot comparison\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "# MAE curves\n",
    "for bs in batch_sizes:\n",
    "    axes[0].plot(batch_results[bs]['history']['val_mae'], label=f'bs={bs}')\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation MAE')\n",
    "axes[0].set_title('Validation MAE over Epochs')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True)\n",
    "\n",
    "# Training time\n",
    "times = [batch_results[bs]['time'] for bs in batch_sizes]\n",
    "axes[1].bar([str(bs) for bs in batch_sizes], times, color='steelblue')\n",
    "axes[1].set_xlabel('Batch Size')\n",
    "axes[1].set_ylabel('Training Time (s)')\n",
    "axes[1].set_title('Training Time')\n",
    "\n",
    "# Final MAE\n",
    "maes = [batch_results[bs]['test_mae'] for bs in batch_sizes]\n",
    "axes[2].bar([str(bs) for bs in batch_sizes], maes, color='coral')\n",
    "axes[2].set_xlabel('Batch Size')\n",
    "axes[2].set_ylabel('Test MAE')\n",
    "axes[2].set_title('Final Test MAE')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Summary table\n",
    "print(\"\\nSummary Table:\")\n",
    "print(\"-\" * 50)\n",
    "print(f\"{'Batch Size':<12} {'Time (s)':<12} {'Test MAE':<12}\")\n",
    "print(\"-\" * 50)\n",
    "for bs in batch_sizes:\n",
    "    print(f\"{bs:<12} {batch_results[bs]['time']:<12.2f} {batch_results[bs]['test_mae']:<12.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex4_answer",
   "metadata": {},
   "source": [
    "**Explanation of Trade-offs:**\n",
    "\n",
    "**Small batch sizes (8, 32):**\n",
    "- **Pros**: More gradient updates per epoch, adds regularization through noise, can escape local minima\n",
    "- **Cons**: Slower per-epoch (more iterations), noisier gradients, may not fully utilize GPU parallelism\n",
    "\n",
    "**Large batch sizes (128, 512):**\n",
    "- **Pros**: Faster per-epoch (fewer iterations), more stable gradients, better GPU utilization\n",
    "- **Cons**: Fewer updates per epoch, may converge to sharper minima (worse generalization), may need learning rate adjustment\n",
    "\n",
    "**Key insights:**\n",
    "1. Larger batches are faster per epoch but may need more epochs to converge\n",
    "2. Smaller batches often generalize better due to gradient noise acting as regularization\n",
    "3. The optimal batch size depends on dataset size, model complexity, and hardware"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex5_header",
   "metadata": {},
   "source": [
    "## Exercise 5: Activation Function Comparison - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex5_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 5: Activation Functions - SOLUTION\n",
    "\n",
    "class FlexibleClassifier(nn.Module):\n",
    "    def __init__(self, input_size, hidden1, hidden2, num_classes, activation='relu'):\n",
    "        super(FlexibleClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden1)\n",
    "        self.fc2 = nn.Linear(hidden1, hidden2)\n",
    "        self.fc3 = nn.Linear(hidden2, num_classes)\n",
    "        \n",
    "        # Set activation based on parameter\n",
    "        if activation == 'relu':\n",
    "            self.act = nn.ReLU()\n",
    "        elif activation == 'tanh':\n",
    "            self.act = nn.Tanh()\n",
    "        elif activation == 'leaky_relu':\n",
    "            self.act = nn.LeakyReLU(0.01)\n",
    "        elif activation == 'elu':\n",
    "            self.act = nn.ELU()\n",
    "        else:\n",
    "            raise ValueError(f\"Unknown activation: {activation}\")\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.act(self.fc1(x))\n",
    "        x = self.act(self.fc2(x))\n",
    "        return self.fc3(x)\n",
    "\n",
    "activations = ['relu', 'tanh', 'leaky_relu', 'elu']\n",
    "act_results = {}\n",
    "\n",
    "train_loader_act = DataLoader(train_dataset, batch_size=16, shuffle=True)\n",
    "val_loader_act = DataLoader(val_dataset, batch_size=16, shuffle=False)\n",
    "\n",
    "for act in activations:\n",
    "    print(f\"\\nTraining with activation: {act}\")\n",
    "    torch.manual_seed(42)\n",
    "    \n",
    "    model_act = FlexibleClassifier(input_size, 32, 16, num_classes, activation=act)\n",
    "    model_act = model_act.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.SGD(model_act.parameters(), lr=0.01, momentum=0.9)\n",
    "    \n",
    "    history = {'train_acc': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(100):\n",
    "        model_act.train()\n",
    "        train_correct, train_total = 0, 0\n",
    "        for X_batch, y_batch in train_loader_act:\n",
    "            X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model_act(X_batch)\n",
    "            loss = criterion(outputs, y_batch)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            _, predicted = torch.max(outputs, 1)\n",
    "            train_total += y_batch.size(0)\n",
    "            train_correct += (predicted == y_batch).sum().item()\n",
    "        \n",
    "        model_act.eval()\n",
    "        val_correct, val_total = 0, 0\n",
    "        with torch.no_grad():\n",
    "            for X_batch, y_batch in val_loader_act:\n",
    "                X_batch, y_batch = X_batch.to(device), y_batch.to(device)\n",
    "                outputs = model_act(X_batch)\n",
    "                _, predicted = torch.max(outputs, 1)\n",
    "                val_total += y_batch.size(0)\n",
    "                val_correct += (predicted == y_batch).sum().item()\n",
    "        \n",
    "        history['train_acc'].append(train_correct / train_total)\n",
    "        history['val_acc'].append(val_correct / val_total)\n",
    "    \n",
    "    # Test accuracy\n",
    "    model_act.eval()\n",
    "    with torch.no_grad():\n",
    "        test_outputs = model_act(torch.FloatTensor(X_test_wine_scaled).to(device))\n",
    "        _, test_preds = torch.max(test_outputs, 1)\n",
    "        test_acc = (test_preds.cpu().numpy() == y_test_wine).mean()\n",
    "    \n",
    "    act_results[act] = {\n",
    "        'history': history,\n",
    "        'test_acc': test_acc\n",
    "    }\n",
    "    print(f\"  Test accuracy: {test_acc:.4f}\")\n",
    "\n",
    "# Plot comparison\n",
    "plt.figure(figsize=(12, 5))\n",
    "\n",
    "plt.subplot(1, 2, 1)\n",
    "for act in activations:\n",
    "    plt.plot(act_results[act]['history']['val_acc'], label=act)\n",
    "plt.xlabel('Epoch')\n",
    "plt.ylabel('Validation Accuracy')\n",
    "plt.title('Validation Accuracy by Activation Function')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "test_accs = [act_results[act]['test_acc'] for act in activations]\n",
    "colors = ['blue', 'green', 'orange', 'red']\n",
    "plt.bar(activations, test_accs, color=colors)\n",
    "plt.xlabel('Activation Function')\n",
    "plt.ylabel('Test Accuracy')\n",
    "plt.title('Final Test Accuracy')\n",
    "plt.ylim(0, 1.1)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Summary\n",
    "print(\"\\nSummary:\")\n",
    "print(\"-\" * 40)\n",
    "for act in activations:\n",
    "    print(f\"{act:<15}: {act_results[act]['test_acc']:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex5_answer",
   "metadata": {},
   "source": [
    "**Explanation:**\n",
    "\n",
    "- **ReLU**: Fast to compute, avoids vanishing gradients for positive values, but can \"die\" (output 0 forever)\n",
    "- **Tanh**: Zero-centered, good for hidden layers, but can have vanishing gradients at extremes\n",
    "- **LeakyReLU**: Addresses dying ReLU by allowing small negative values\n",
    "- **ELU**: Smooth transition at 0, can produce negative outputs, may converge faster\n",
    "\n",
    "For this dataset, ReLU variants typically perform well. The differences may be subtle for small networks and datasets."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex6_header",
   "metadata": {},
   "source": [
    "## Exercise 6: Network Depth Experiment - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex6_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 6: Network Depth - SOLUTION\n",
    "\n",
    "class FlexibleRegressor(nn.Module):\n",
    "    def __init__(self, input_size, hidden_sizes):\n",
    "        \"\"\"\n",
    "        hidden_sizes: list like [32] for 1 layer, [32, 16] for 2 layers, etc.\n",
    "        \"\"\"\n",
    "        super(FlexibleRegressor, self).__init__()\n",
    "        layers = []\n",
    "        prev_size = input_size\n",
    "        for h in hidden_sizes:\n",
    "            layers.append(nn.Linear(prev_size, h))\n",
    "            layers.append(nn.ReLU())\n",
    "            prev_size = h\n",
    "        layers.append(nn.Linear(prev_size, 1))\n",
    "        self.network = nn.Sequential(*layers)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.network(x)\n",
    "\n",
    "def count_parameters(model):\n",
    "    return sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
    "\n",
    "architectures = {\n",
    "    '1 layer': [32],\n",
    "    '2 layers': [32, 16],\n",
    "    '3 layers': [32, 24, 16],\n",
    "    '4 layers': [32, 24, 16, 8]\n",
    "}\n",
    "\n",
    "depth_results = {}\n",
    "\n",
    "train_loader_depth = DataLoader(train_dataset_cal, batch_size=64, shuffle=True)\n",
    "val_loader_depth = DataLoader(val_dataset_cal, batch_size=64, shuffle=False)\n",
    "\n",
    "for name, hidden_sizes in architectures.items():\n",
    "    print(f\"\\nTraining {name}: {hidden_sizes}\")\n",
    "    torch.manual_seed(42)\n",
    "    \n",
    "    model_depth = FlexibleRegressor(input_size_cal, hidden_sizes)\n",
    "    n_params = count_parameters(model_depth)\n",
    "    print(f\"  Parameters: {n_params}\")\n",
    "    \n",
    "    history_depth = train_regressor(model_depth, train_loader_depth, val_loader_depth,\n",
    "                                     epochs=50, lr=0.005, device=device, verbose=False)\n",
    "    \n",
    "    model_depth.eval()\n",
    "    with torch.no_grad():\n",
    "        test_preds = model_depth(torch.FloatTensor(X_test_cal_scaled).to(device)).squeeze().cpu().numpy()\n",
    "        test_mae = np.mean(np.abs(test_preds - y_test_cal))\n",
    "    \n",
    "    depth_results[name] = {\n",
    "        'params': n_params,\n",
    "        'test_mae': test_mae,\n",
    "        'history': history_depth\n",
    "    }\n",
    "    print(f\"  Test MAE: {test_mae:.4f}\")\n",
    "\n",
    "# Plot comparison\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "# MAE curves\n",
    "for name in architectures:\n",
    "    axes[0].plot(depth_results[name]['history']['val_mae'], label=name)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation MAE')\n",
    "axes[0].set_title('Validation MAE over Training')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True)\n",
    "\n",
    "# Parameters\n",
    "names = list(architectures.keys())\n",
    "params = [depth_results[n]['params'] for n in names]\n",
    "axes[1].bar(names, params, color='steelblue')\n",
    "axes[1].set_xlabel('Architecture')\n",
    "axes[1].set_ylabel('Parameters')\n",
    "axes[1].set_title('Number of Parameters')\n",
    "axes[1].tick_params(axis='x', rotation=45)\n",
    "\n",
    "# Final MAE\n",
    "maes = [depth_results[n]['test_mae'] for n in names]\n",
    "axes[2].bar(names, maes, color='coral')\n",
    "axes[2].set_xlabel('Architecture')\n",
    "axes[2].set_ylabel('Test MAE')\n",
    "axes[2].set_title('Final Test MAE')\n",
    "axes[2].tick_params(axis='x', rotation=45)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Summary\n",
    "print(\"\\nSummary:\")\n",
    "print(\"-\" * 55)\n",
    "print(f\"{'Architecture':<15} {'Parameters':<12} {'Test MAE'}\")\n",
    "print(\"-\" * 55)\n",
    "for name in architectures:\n",
    "    print(f\"{name:<15} {depth_results[name]['params']:<12} {depth_results[name]['test_mae']:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex6_answer",
   "metadata": {},
   "source": [
    "**Explanation:**\n",
    "\n",
    "**Is deeper always better?** No!\n",
    "\n",
    "**Problems with very deep networks:**\n",
    "1. **Vanishing gradients**: Gradients can become very small in deep networks, making early layers hard to train\n",
    "2. **Overfitting**: More parameters = more capacity to memorize training data\n",
    "3. **Harder optimization**: More local minima and saddle points\n",
    "4. **Diminishing returns**: After a point, adding layers doesn't help and may hurt\n",
    "\n",
    "For this dataset, 2-3 layers is typically sufficient. Very deep networks (4+) may overfit or not provide significant improvement."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex7_header",
   "metadata": {},
   "source": [
    "## Exercise 7: Iris Classification - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex7_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 7: Iris Classification - SOLUTION\n",
    "\n",
    "# Load data\n",
    "iris = load_iris()\n",
    "X_iris, y_iris = iris.data, iris.target\n",
    "print(f\"Shape: {X_iris.shape}, Classes: {len(np.unique(y_iris))}\")\n",
    "print(f\"Class names: {iris.target_names}\")\n",
    "\n",
    "# Split and scale\n",
    "X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(\n",
    "    X_iris, y_iris, test_size=0.2, random_state=42, stratify=y_iris\n",
    ")\n",
    "\n",
    "scaler_iris = StandardScaler()\n",
    "X_train_iris_scaled = scaler_iris.fit_transform(X_train_iris)\n",
    "X_test_iris_scaled = scaler_iris.transform(X_test_iris)\n",
    "\n",
    "# Create datasets and loaders\n",
    "X_tr_iris, X_val_iris, y_tr_iris, y_val_iris = train_test_split(\n",
    "    X_train_iris_scaled, y_train_iris, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "train_ds_iris = TensorDataset(torch.FloatTensor(X_tr_iris), torch.LongTensor(y_tr_iris))\n",
    "val_ds_iris = TensorDataset(torch.FloatTensor(X_val_iris), torch.LongTensor(y_val_iris))\n",
    "train_loader_iris = DataLoader(train_ds_iris, batch_size=16, shuffle=True)\n",
    "val_loader_iris = DataLoader(val_ds_iris, batch_size=16, shuffle=False)\n",
    "\n",
    "# Build classifier\n",
    "class IrisClassifier(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(IrisClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(4, 16)\n",
    "        self.relu1 = nn.ReLU()\n",
    "        self.fc2 = nn.Linear(16, 8)\n",
    "        self.relu2 = nn.ReLU()\n",
    "        self.fc3 = nn.Linear(8, 3)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu1(self.fc1(x))\n",
    "        x = self.relu2(self.fc2(x))\n",
    "        return self.fc3(x)\n",
    "\n",
    "# Train\n",
    "torch.manual_seed(42)\n",
    "model_iris = IrisClassifier()\n",
    "history_iris = train_classifier(model_iris, train_loader_iris, val_loader_iris,\n",
    "                                 epochs=200, lr=0.01, patience=30, device=device)\n",
    "\n",
    "# Evaluate\n",
    "model_iris.eval()\n",
    "with torch.no_grad():\n",
    "    test_outputs = model_iris(torch.FloatTensor(X_test_iris_scaled).to(device))\n",
    "    _, y_pred_iris = torch.max(test_outputs, 1)\n",
    "    y_pred_iris = y_pred_iris.cpu().numpy()\n",
    "    test_acc_iris = (y_pred_iris == y_test_iris).mean()\n",
    "\n",
    "print(f\"\\nTest Accuracy: {test_acc_iris:.4f}\")\n",
    "\n",
    "# Confusion matrix\n",
    "cm_iris = confusion_matrix(y_test_iris, y_pred_iris)\n",
    "plt.figure(figsize=(6, 5))\n",
    "sns.heatmap(cm_iris, annot=True, cmap='Blues', \n",
    "            xticklabels=iris.target_names, yticklabels=iris.target_names)\n",
    "plt.title('Iris Classification - Confusion Matrix')\n",
    "plt.xlabel('Predicted')\n",
    "plt.ylabel('Actual')\n",
    "plt.show()\n",
    "\n",
    "print(\"\\nClassification Report:\")\n",
    "print(classification_report(y_test_iris, y_pred_iris, target_names=iris.target_names))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex8_header",
   "metadata": {},
   "source": [
    "## Exercise 8: Diabetes Regression - SOLUTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex8_solution",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 8: Diabetes Regression - SOLUTION\n",
    "\n",
    "# Load data\n",
    "diabetes = load_diabetes()\n",
    "X_diabetes, y_diabetes = diabetes.data, diabetes.target\n",
    "print(f\"Shape: {X_diabetes.shape}\")\n",
    "print(f\"Target range: {y_diabetes.min():.0f} - {y_diabetes.max():.0f}\")\n",
    "print(f\"Features: {diabetes.feature_names}\")\n",
    "\n",
    "# Split and scale\n",
    "X_train_diab, X_test_diab, y_train_diab, y_test_diab = train_test_split(\n",
    "    X_diabetes, y_diabetes, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "scaler_diab = StandardScaler()\n",
    "X_train_diab_scaled = scaler_diab.fit_transform(X_train_diab)\n",
    "X_test_diab_scaled = scaler_diab.transform(X_test_diab)\n",
    "\n",
    "# Create datasets and loaders\n",
    "X_tr_diab, X_val_diab, y_tr_diab, y_val_diab = train_test_split(\n",
    "    X_train_diab_scaled, y_train_diab, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "train_ds_diab = TensorDataset(torch.FloatTensor(X_tr_diab), torch.FloatTensor(y_tr_diab))\n",
    "val_ds_diab = TensorDataset(torch.FloatTensor(X_val_diab), torch.FloatTensor(y_val_diab))\n",
    "train_loader_diab = DataLoader(train_ds_diab, batch_size=32, shuffle=True)\n",
    "val_loader_diab = DataLoader(val_ds_diab, batch_size=32, shuffle=False)\n",
    "\n",
    "# Build regressor\n",
    "class DiabetesRegressor(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(DiabetesRegressor, self).__init__()\n",
    "        self.fc1 = nn.Linear(10, 32)\n",
    "        self.relu1 = nn.ReLU()\n",
    "        self.fc2 = nn.Linear(32, 16)\n",
    "        self.relu2 = nn.ReLU()\n",
    "        self.fc3 = nn.Linear(16, 1)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu1(self.fc1(x))\n",
    "        x = self.relu2(self.fc2(x))\n",
    "        return self.fc3(x)\n",
    "\n",
    "# Train\n",
    "torch.manual_seed(42)\n",
    "model_diab = DiabetesRegressor()\n",
    "history_diab = train_regressor(model_diab, train_loader_diab, val_loader_diab,\n",
    "                                epochs=100, lr=0.01, device=device, verbose=True)\n",
    "\n",
    "# Evaluate\n",
    "model_diab.eval()\n",
    "with torch.no_grad():\n",
    "    test_preds_diab = model_diab(torch.FloatTensor(X_test_diab_scaled).to(device)).squeeze().cpu().numpy()\n",
    "    test_mae_diab = np.mean(np.abs(test_preds_diab - y_test_diab))\n",
    "\n",
    "print(f\"\\nTest MAE: {test_mae_diab:.4f}\")\n",
    "\n",
    "# Plot predictions vs actual\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
    "\n",
    "# Scatter plot\n",
    "axes[0].scatter(y_test_diab, test_preds_diab, alpha=0.6)\n",
    "axes[0].plot([y_test_diab.min(), y_test_diab.max()], \n",
    "             [y_test_diab.min(), y_test_diab.max()], 'r--', lw=2)\n",
    "axes[0].set_xlabel('Actual')\n",
    "axes[0].set_ylabel('Predicted')\n",
    "axes[0].set_title('Predictions vs Actual')\n",
    "axes[0].grid(True)\n",
    "\n",
    "# Residual plot\n",
    "residuals = test_preds_diab - y_test_diab\n",
    "axes[1].scatter(test_preds_diab, residuals, alpha=0.6)\n",
    "axes[1].axhline(y=0, color='r', linestyle='--')\n",
    "axes[1].set_xlabel('Predicted')\n",
    "axes[1].set_ylabel('Residual (Predicted - Actual)')\n",
    "axes[1].set_title('Residual Plot')\n",
    "axes[1].grid(True)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(f\"\\nCorrelation: {np.corrcoef(y_test_diab, test_preds_diab)[0,1]:.4f}\")\n",
    "print(f\"R² Score: {1 - np.sum((y_test_diab - test_preds_diab)**2) / np.sum((y_test_diab - y_test_diab.mean())**2):.4f}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
