{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# LDSCI6211: CNN Lab - Complete Solutions\n",
        "## Machine Learning and Data Mining II\n",
        "### Dr. Waleed Iqbal - Northeastern University London\n",
        "\n",
        "This notebook contains complete solutions to all lab tasks and bonus exercises."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Setup and Imports"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "import torch.optim as optim\n",
        "from torch.utils.data import DataLoader\n",
        "from torchvision import datasets, transforms\n",
        "\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from tqdm import tqdm\n",
        "from collections import Counter\n",
        "import seaborn as sns\n",
        "from sklearn.metrics import confusion_matrix\n",
        "\n",
        "# Set random seeds\n",
        "torch.manual_seed(42)\n",
        "np.random.seed(42)\n",
        "\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "print(f\"Using device: {device}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "# Part 1: Basic CNN Operations - Solutions\n",
        "\n",
        "## Task 1.1 Solution: Convolution Calculations"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\"*60)\n",
        "print(\"TASK 1.1 SOLUTION - CONVOLUTION CALCULATIONS\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Scenario 1: Input: 64x64, Kernel: 3x3, Padding: 1, Stride: 1\n",
        "print(\"\\nScenario 1:\")\n",
        "print(\"Formula: (W - K + 2P) / S + 1\")\n",
        "print(\"Calculation: (64 - 3 + 2*1) / 1 + 1 = 64\")\n",
        "\n",
        "test_input_1 = torch.randn(1, 3, 64, 64)\n",
        "conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1, stride=1)\n",
        "output1 = conv1(test_input_1)\n",
        "print(f\"Verified output shape: {output1.shape}\")\n",
        "print(f\"Output dimensions: {output1.shape[2]}x{output1.shape[3]}\")\n",
        "\n",
        "# Scenario 2: Input: 128x128, Kernel: 7x7, Padding: 3, Stride: 2\n",
        "print(\"\\nScenario 2:\")\n",
        "print(\"Formula: (W - K + 2P) / S + 1\")\n",
        "print(\"Calculation: (128 - 7 + 2*3) / 2 + 1 = 64\")\n",
        "\n",
        "test_input_2 = torch.randn(1, 3, 128, 128)\n",
        "conv2 = nn.Conv2d(3, 16, kernel_size=7, padding=3, stride=2)\n",
        "output2 = conv2(test_input_2)\n",
        "print(f\"Verified output shape: {output2.shape}\")\n",
        "print(f\"Output dimensions: {output2.shape[2]}x{output2.shape[3]}\")\n",
        "\n",
        "# Scenario 3: Input: 56x56, Kernel: 5x5, Padding: 0, Stride: 1\n",
        "print(\"\\nScenario 3:\")\n",
        "print(\"Formula: (W - K + 2P) / S + 1\")\n",
        "print(\"Calculation: (56 - 5 + 2*0) / 1 + 1 = 52\")\n",
        "\n",
        "test_input_3 = torch.randn(1, 3, 56, 56)\n",
        "conv3 = nn.Conv2d(3, 16, kernel_size=5, padding=0, stride=1)\n",
        "output3 = conv3(test_input_3)\n",
        "print(f\"Verified output shape: {output3.shape}\")\n",
        "print(f\"Output dimensions: {output3.shape[2]}x{output3.shape[3]}\")\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Task 1.2 Solution: Understanding Dead ReLU"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\"*60)\n",
        "print(\"TASK 1.2 SOLUTION - DEAD ReLU PROBLEM\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "# Create test values\n",
        "test_values = torch.tensor([-5.0, -3.0, -1.0, 0.0, 1.0, 3.0, 5.0])\n",
        "\n",
        "# Apply different activations\n",
        "relu_output = F.relu(test_values)\n",
        "leaky_relu_output = F.leaky_relu(test_values, negative_slope=0.1)\n",
        "\n",
        "print(\"\\nOriginal values:\")\n",
        "print(test_values)\n",
        "print(\"\\nAfter ReLU:\")\n",
        "print(relu_output)\n",
        "print(\"\\nAfter Leaky ReLU (slope=0.1):\")\n",
        "print(leaky_relu_output)\n",
        "\n",
        "print(\"\\n\" + \"-\"*60)\n",
        "print(\"ANALYSIS:\")\n",
        "print(\"-\"*60)\n",
        "print(\"\\n1. ReLU zeros out ALL negative values\")\n",
        "print(\"   - This can cause 'dead neurons'\")\n",
        "print(\"   - Example: -5.0 -> 0.0, -3.0 -> 0.0\")\n",
        "\n",
        "print(\"\\n2. Leaky ReLU preserves information\")\n",
        "print(\"   - Multiplies negative values by 0.1\")\n",
        "print(\"   - Example: -5.0 -> -0.5, -3.0 -> -0.3\")\n",
        "print(\"   - Prevents dead neurons\")\n",
        "\n",
        "print(\"\\n3. Both keep positive values unchanged\")\n",
        "print(\"   - Example: 5.0 -> 5.0, 3.0 -> 3.0\")\n",
        "print(\"\\n\" + \"=\"*60)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Visualize comparison\n",
        "x_range = torch.linspace(-5, 5, 100)\n",
        "\n",
        "plt.figure(figsize=(10, 5))\n",
        "plt.plot(x_range.numpy(), F.relu(x_range).numpy(), \n",
        "         label='ReLU', linewidth=2)\n",
        "plt.plot(x_range.numpy(), F.leaky_relu(x_range, 0.1).numpy(), \n",
        "         label='Leaky ReLU', linewidth=2)\n",
        "plt.axhline(y=0, color='k', linestyle='--', alpha=0.3)\n",
        "plt.axvline(x=0, color='k', linestyle='--', alpha=0.3)\n",
        "plt.xlabel('Input Value')\n",
        "plt.ylabel('Output Value')\n",
        "plt.title('ReLU vs Leaky ReLU: Dead Neuron Problem')\n",
        "plt.legend()\n",
        "plt.grid(True, alpha=0.3)\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "# Part 2: Building CNNs - Solutions\n",
        "\n",
        "## Load MNIST Dataset"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Load MNIST\n",
        "transform = transforms.Compose([\n",
        "    transforms.ToTensor(),\n",
        "    transforms.Normalize((0.1307,), (0.3081,))\n",
        "])\n",
        "\n",
        "train_dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)\n",
        "test_dataset = datasets.MNIST('./data', train=False, transform=transform)\n",
        "\n",
        "train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)\n",
        "test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)\n",
        "\n",
        "print(f\"Training samples: {len(train_dataset)}\")\n",
        "print(f\"Test samples: {len(test_dataset)}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Baseline SimpleCNN Model"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "class SimpleCNN(nn.Module):\n",
        "    def __init__(self):\n",
        "        super(SimpleCNN, self).__init__()\n",
        "        \n",
        "        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)\n",
        "        self.relu1 = nn.ReLU()\n",
        "        self.pool1 = nn.MaxPool2d(2, 2)\n",
        "        \n",
        "        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)\n",
        "        self.relu2 = nn.ReLU()\n",
        "        self.pool2 = nn.MaxPool2d(2, 2)\n",
        "        \n",
        "        self.fc1 = nn.Linear(64 * 7 * 7, 128)\n",
        "        self.relu3 = nn.ReLU()\n",
        "        self.dropout = nn.Dropout(0.5)\n",
        "        self.fc2 = nn.Linear(128, 10)\n",
        "        \n",
        "    def forward(self, x):\n",
        "        x = self.pool1(self.relu1(self.conv1(x)))\n",
        "        x = self.pool2(self.relu2(self.conv2(x)))\n",
        "        x = x.view(x.size(0), -1)\n",
        "        x = self.fc1(x)\n",
        "        x = self.relu3(x)\n",
        "        x = self.dropout(x)\n",
        "        x = self.fc2(x)\n",
        "        return x\n",
        "\n",
        "model = SimpleCNN().to(device)\n",
        "print(model)\n",
        "print(f\"\\nTotal parameters: {sum(p.numel() for p in model.parameters()):,}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Training and Evaluation Functions"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "def train_epoch(model, train_loader, criterion, optimizer, device):\n",
        "    model.train()\n",
        "    running_loss = 0.0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "    \n",
        "    for inputs, labels in tqdm(train_loader, desc=\"Training\"):\n",
        "        inputs, labels = inputs.to(device), labels.to(device)\n",
        "        \n",
        "        optimizer.zero_grad()\n",
        "        outputs = model(inputs)\n",
        "        loss = criterion(outputs, labels)\n",
        "        loss.backward()\n",
        "        optimizer.step()\n",
        "        \n",
        "        running_loss += loss.item()\n",
        "        _, predicted = outputs.max(1)\n",
        "        total += labels.size(0)\n",
        "        correct += predicted.eq(labels).sum().item()\n",
        "    \n",
        "    return running_loss / len(train_loader), 100. * correct / total\n",
        "\n",
        "def evaluate(model, test_loader, criterion, device):\n",
        "    model.eval()\n",
        "    running_loss = 0.0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for inputs, labels in test_loader:\n",
        "            inputs, labels = inputs.to(device), labels.to(device)\n",
        "            outputs = model(inputs)\n",
        "            loss = criterion(outputs, labels)\n",
        "            \n",
        "            running_loss += loss.item()\n",
        "            _, predicted = outputs.max(1)\n",
        "            total += labels.size(0)\n",
        "            correct += predicted.eq(labels).sum().item()\n",
        "    \n",
        "    return running_loss / len(test_loader), 100. * correct / total"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Train Baseline Model"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "criterion = nn.CrossEntropyLoss()\n",
        "optimizer = optim.Adam(model.parameters(), lr=0.001)\n",
        "\n",
        "num_epochs = 3\n",
        "train_losses, train_accs = [], []\n",
        "test_losses, test_accs = [], []\n",
        "\n",
        "print(\"Training Baseline Model...\")\n",
        "for epoch in range(num_epochs):\n",
        "    print(f\"\\nEpoch {epoch+1}/{num_epochs}\")\n",
        "    \n",
        "    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)\n",
        "    train_losses.append(train_loss)\n",
        "    train_accs.append(train_acc)\n",
        "    \n",
        "    test_loss, test_acc = evaluate(model, test_loader, criterion, device)\n",
        "    test_losses.append(test_loss)\n",
        "    test_accs.append(test_acc)\n",
        "    \n",
        "    print(f\"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%\")\n",
        "    print(f\"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.2f}%\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "## Task 2.1 Solution: Improved CNN Architecture"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\"*60)\n",
        "print(\"TASK 2.1 SOLUTION - IMPROVED CNN\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "class ImprovedCNN(nn.Module):\n",
        "    def __init__(self):\n",
        "        super(ImprovedCNN, self).__init__()\n",
        "        \n",
        "        # Conv block 1 with BatchNorm\n",
        "        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)\n",
        "        self.bn1 = nn.BatchNorm2d(32)\n",
        "        self.relu1 = nn.ReLU()\n",
        "        self.pool1 = nn.MaxPool2d(2, 2)\n",
        "        \n",
        "        # Conv block 2 with BatchNorm\n",
        "        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)\n",
        "        self.bn2 = nn.BatchNorm2d(64)\n",
        "        self.relu2 = nn.ReLU()\n",
        "        self.pool2 = nn.MaxPool2d(2, 2)\n",
        "        \n",
        "        # Conv block 3 (NEW!)\n",
        "        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)\n",
        "        self.bn3 = nn.BatchNorm2d(128)\n",
        "        self.relu3 = nn.ReLU()\n",
        "        \n",
        "        # Deeper FC layers\n",
        "        self.fc1 = nn.Linear(128 * 7 * 7, 256)\n",
        "        self.relu4 = nn.ReLU()\n",
        "        self.dropout1 = nn.Dropout(0.5)\n",
        "        self.fc2 = nn.Linear(256, 128)\n",
        "        self.relu5 = nn.ReLU()\n",
        "        self.dropout2 = nn.Dropout(0.3)\n",
        "        self.fc3 = nn.Linear(128, 10)\n",
        "        \n",
        "    def forward(self, x):\n",
        "        x = self.conv1(x)\n",
        "        x = self.bn1(x)\n",
        "        x = self.relu1(x)\n",
        "        x = self.pool1(x)\n",
        "        \n",
        "        x = self.conv2(x)\n",
        "        x = self.bn2(x)\n",
        "        x = self.relu2(x)\n",
        "        x = self.pool2(x)\n",
        "        \n",
        "        x = self.conv3(x)\n",
        "        x = self.bn3(x)\n",
        "        x = self.relu3(x)\n",
        "        \n",
        "        x = x.view(x.size(0), -1)\n",
        "        \n",
        "        x = self.fc1(x)\n",
        "        x = self.relu4(x)\n",
        "        x = self.dropout1(x)\n",
        "        x = self.fc2(x)\n",
        "        x = self.relu5(x)\n",
        "        x = self.dropout2(x)\n",
        "        x = self.fc3(x)\n",
        "        \n",
        "        return x\n",
        "\n",
        "improved_model = ImprovedCNN().to(device)\n",
        "print(improved_model)\n",
        "total_params = sum(p.numel() for p in improved_model.parameters())\n",
        "print(f\"\\nTotal parameters: {total_params:,}\")\n",
        "\n",
        "print(\"\\nKEY IMPROVEMENTS:\")\n",
        "print(\"1. Added 3rd convolutional layer\")\n",
        "print(\"2. Batch Normalization after each conv\")\n",
        "print(\"3. Increased filters: 32 -> 64 -> 128\")\n",
        "print(\"4. Deeper FC layers (256 -> 128 -> 10)\")\n",
        "print(\"5. Multiple dropout layers\")\n",
        "print(\"=\"*60)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "criterion_improved = nn.CrossEntropyLoss()\n",
        "optimizer_improved = optim.Adam(improved_model.parameters(), lr=0.001)\n",
        "\n",
        "train_losses_imp = []\n",
        "test_losses_imp = []\n",
        "train_accs_imp = []\n",
        "test_accs_imp = []\n",
        "\n",
        "print(\"\\nTraining Improved Model...\")\n",
        "for epoch in range(3):\n",
        "    print(f\"\\nEpoch {epoch+1}/3\")\n",
        "    \n",
        "    train_loss, train_acc = train_epoch(improved_model, train_loader, \n",
        "                                       criterion_improved, optimizer_improved, device)\n",
        "    train_losses_imp.append(train_loss)\n",
        "    train_accs_imp.append(train_acc)\n",
        "    \n",
        "    test_loss, test_acc = evaluate(improved_model, test_loader, \n",
        "                                   criterion_improved, device)\n",
        "    test_losses_imp.append(test_loss)\n",
        "    test_accs_imp.append(test_acc)\n",
        "    \n",
        "    print(f\"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%\")\n",
        "    print(f\"Test Loss: {test_loss:.4f}, Test Acc: {test_acc:.2f}%\")\n",
        "\n",
        "print(f\"\\nBaseline Final Accuracy: {test_accs[-1]:.2f}%\")\n",
        "print(f\"Improved Final Accuracy: {test_accs_imp[-1]:.2f}%\")\n",
        "print(f\"Improvement: +{test_accs_imp[-1] - test_accs[-1]:.2f}%\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "ax1.plot(range(1, 4), test_losses[:3], 'o-', label='Baseline', linewidth=2)\n",
        "ax1.plot(range(1, 4), test_losses_imp, 's-', label='Improved', linewidth=2)\n",
        "ax1.set_xlabel('Epoch')\n",
        "ax1.set_ylabel('Test Loss')\n",
        "ax1.set_title('Test Loss Comparison')\n",
        "ax1.legend()\n",
        "ax1.grid(True)\n",
        "\n",
        "ax2.plot(range(1, 4), test_accs[:3], 'o-', label='Baseline', linewidth=2)\n",
        "ax2.plot(range(1, 4), test_accs_imp, 's-', label='Improved', linewidth=2)\n",
        "ax2.set_xlabel('Epoch')\n",
        "ax2.set_ylabel('Test Accuracy (%)')\n",
        "ax2.set_title('Test Accuracy Comparison')\n",
        "ax2.legend()\n",
        "ax2.grid(True)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "# Part 3: Visualization and Analysis - Solutions\n",
        "\n",
        "## Visualize Learned Filters"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "def visualize_filters(model, layer_name='conv1'):\n",
        "    conv_layer = getattr(model, layer_name)\n",
        "    filters = conv_layer.weight.data.cpu()\n",
        "    filters = (filters - filters.min()) / (filters.max() - filters.min())\n",
        "    \n",
        "    n_filters = min(32, filters.shape[0])\n",
        "    fig, axes = plt.subplots(4, 8, figsize=(15, 8))\n",
        "    \n",
        "    for i, ax in enumerate(axes.flat):\n",
        "        if i < n_filters:\n",
        "            ax.imshow(filters[i, 0], cmap='gray')\n",
        "            ax.set_title(f'Filter {i+1}')\n",
        "        ax.axis('off')\n",
        "    \n",
        "    plt.suptitle('First Layer Learned Filters', fontsize=14)\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "visualize_filters(model, 'conv1')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Task 3.1 Solution: Error Analysis"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\"*60)\n",
        "print(\"TASK 3.1 SOLUTION - ERROR ANALYSIS\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "def find_misclassifications(model, test_loader, device, n_errors=10):\n",
        "    model.eval()\n",
        "    \n",
        "    misclassified_images = []\n",
        "    misclassified_labels = []\n",
        "    misclassified_preds = []\n",
        "    misclassified_probs = []\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for images, labels in test_loader:\n",
        "            images, labels = images.to(device), labels.to(device)\n",
        "            outputs = model(images)\n",
        "            _, predictions = outputs.max(1)\n",
        "            probabilities = F.softmax(outputs, dim=1)\n",
        "            \n",
        "            mask = predictions != labels\n",
        "            \n",
        "            if mask.sum() > 0:\n",
        "                misclassified_images.extend(images[mask].cpu())\n",
        "                misclassified_labels.extend(labels[mask].cpu())\n",
        "                misclassified_preds.extend(predictions[mask].cpu())\n",
        "                \n",
        "                for i in range(mask.sum()):\n",
        "                    idx = torch.where(mask)[0][i]\n",
        "                    pred_class = predictions[idx]\n",
        "                    conf = probabilities[idx, pred_class].cpu().item()\n",
        "                    misclassified_probs.append(conf)\n",
        "            \n",
        "            if len(misclassified_images) >= n_errors:\n",
        "                break\n",
        "    \n",
        "    # Visualize\n",
        "    n_show = min(n_errors, len(misclassified_images))\n",
        "    fig, axes = plt.subplots(2, 5, figsize=(15, 7))\n",
        "    \n",
        "    for i, ax in enumerate(axes.flat):\n",
        "        if i < n_show:\n",
        "            img = misclassified_images[i].squeeze()\n",
        "            true_label = misclassified_labels[i].item()\n",
        "            pred_label = misclassified_preds[i].item()\n",
        "            confidence = misclassified_probs[i]\n",
        "            \n",
        "            ax.imshow(img, cmap='gray')\n",
        "            ax.set_title(f'True: {true_label}, Pred: {pred_label}\\nConf: {confidence:.2f}', \n",
        "                        color='red', fontweight='bold')\n",
        "            ax.axis('off')\n",
        "        else:\n",
        "            ax.axis('off')\n",
        "    \n",
        "    plt.suptitle('Misclassified Examples', fontsize=16, fontweight='bold')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    \n",
        "    return misclassified_images[:n_show], misclassified_labels[:n_show],            misclassified_preds[:n_show], misclassified_probs[:n_show]\n",
        "\n",
        "mis_imgs, mis_labels, mis_preds, mis_probs = find_misclassifications(\n",
        "    model, test_loader, device, n_errors=10\n",
        ")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Analyze errors\n",
        "confusion_pairs = [(mis_labels[i].item(), mis_preds[i].item()) \n",
        "                   for i in range(len(mis_labels))]\n",
        "confusion_counts = Counter(confusion_pairs)\n",
        "\n",
        "print(\"\\nMost Common Confusions:\")\n",
        "for (true, pred), count in confusion_counts.most_common(5):\n",
        "    print(f\"  {true} confused with {pred}: {count} times\")\n",
        "\n",
        "print(\"\\n\" + \"-\"*60)\n",
        "print(\"COMMON ERROR PATTERNS:\")\n",
        "print(\"-\"*60)\n",
        "print(\"1. Similar-Looking Digits: 4 vs 9, 3 vs 5, 7 vs 1\")\n",
        "print(\"2. Writing Style Variations\")\n",
        "print(\"3. Image Quality Issues\")\n",
        "print(\"4. Average confidence on errors: {:.2f}\".format(np.mean(mis_probs)))\n",
        "print(\"\\nModel is sometimes confident even when wrong!\")\n",
        "print(\"=\"*60)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "# Part 4: Hyperparameter Experiments - Solutions\n",
        "\n",
        "## Task 4.1 Solution: Learning Rate Experiment"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\"*60)\n",
        "print(\"TASK 4.1 SOLUTION - LEARNING RATE EXPERIMENT\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "learning_rates = [0.0001, 0.001, 0.01]\n",
        "lr_results = {}\n",
        "\n",
        "for lr in learning_rates:\n",
        "    print(f\"\\nTraining with LR={lr}\")\n",
        "    \n",
        "    model_lr = SimpleCNN().to(device)\n",
        "    criterion_lr = nn.CrossEntropyLoss()\n",
        "    optimizer_lr = optim.Adam(model_lr.parameters(), lr=lr)\n",
        "    \n",
        "    test_accs_lr = []\n",
        "    \n",
        "    for epoch in range(3):\n",
        "        train_loss, train_acc = train_epoch(model_lr, train_loader, \n",
        "                                           criterion_lr, optimizer_lr, device)\n",
        "        test_loss, test_acc = evaluate(model_lr, test_loader, \n",
        "                                       criterion_lr, device)\n",
        "        test_accs_lr.append(test_acc)\n",
        "        print(f\"  Epoch {epoch+1}: Test Acc = {test_acc:.2f}%\")\n",
        "    \n",
        "    lr_results[lr] = test_accs_lr\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"SUMMARY:\")\n",
        "print(\"=\"*60)\n",
        "for lr in learning_rates:\n",
        "    print(f\"LR={lr}: Final Acc = {lr_results[lr][-1]:.2f}%\")\n",
        "\n",
        "print(\"\\nOBSERVATIONS:\")\n",
        "print(\"- LR=0.0001: Slow convergence\")\n",
        "print(\"- LR=0.001: Good balance\")\n",
        "print(\"- LR=0.01: Fast but may be unstable\")\n",
        "print(\"=\"*60)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Plot LR comparison\n",
        "plt.figure(figsize=(10, 6))\n",
        "for lr in learning_rates:\n",
        "    plt.plot(range(1, 4), lr_results[lr], 'o-', label=f'LR={lr}', linewidth=2)\n",
        "plt.xlabel('Epoch')\n",
        "plt.ylabel('Test Accuracy (%)')\n",
        "plt.title('Learning Rate Comparison')\n",
        "plt.legend()\n",
        "plt.grid(True)\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Task 4.2 Solution: Optimizer Comparison"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "print(\"=\"*60)\n",
        "print(\"TASK 4.2 SOLUTION - OPTIMIZER COMPARISON\")\n",
        "print(\"=\"*60)\n",
        "\n",
        "optimizers_config = [\n",
        "    ('SGD', lambda params: optim.SGD(params, lr=0.001)),\n",
        "    ('SGD+Momentum', lambda params: optim.SGD(params, lr=0.001, momentum=0.9)),\n",
        "    ('Adam', lambda params: optim.Adam(params, lr=0.001))\n",
        "]\n",
        "\n",
        "opt_results = {}\n",
        "\n",
        "for opt_name, opt_fn in optimizers_config:\n",
        "    print(f\"\\nTraining with {opt_name}\")\n",
        "    \n",
        "    model_opt = SimpleCNN().to(device)\n",
        "    criterion_opt = nn.CrossEntropyLoss()\n",
        "    optimizer_opt = opt_fn(model_opt.parameters())\n",
        "    \n",
        "    test_accs_opt = []\n",
        "    \n",
        "    for epoch in range(3):\n",
        "        train_loss, train_acc = train_epoch(model_opt, train_loader, \n",
        "                                           criterion_opt, optimizer_opt, device)\n",
        "        test_loss, test_acc = evaluate(model_opt, test_loader, \n",
        "                                       criterion_opt, device)\n",
        "        test_accs_opt.append(test_acc)\n",
        "        print(f\"  Epoch {epoch+1}: Test Acc = {test_acc:.2f}%\")\n",
        "    \n",
        "    opt_results[opt_name] = test_accs_opt\n",
        "\n",
        "print(\"\\n\" + \"=\"*60)\n",
        "print(\"SUMMARY:\")\n",
        "print(\"=\"*60)\n",
        "for opt_name, _ in optimizers_config:\n",
        "    print(f\"{opt_name}: Final Acc = {opt_results[opt_name][-1]:.2f}%\")\n",
        "\n",
        "print(\"\\nKEY TAKEAWAY:\")\n",
        "print(\"Adam usually converges fastest and most reliably\")\n",
        "print(\"=\"*60)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# Plot optimizer comparison\n",
        "plt.figure(figsize=(10, 6))\n",
        "markers = ['o', 's', '^']\n",
        "for (opt_name, _), marker in zip(optimizers_config, markers):\n",
        "    plt.plot(range(1, 4), opt_results[opt_name], marker=marker, \n",
        "             label=opt_name, linewidth=2, markersize=8)\n",
        "plt.xlabel('Epoch')\n",
        "plt.ylabel('Test Accuracy (%)')\n",
        "plt.title('Optimizer Comparison')\n",
        "plt.legend()\n",
        "plt.grid(True)\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "#\n",
        "\n",
        "##  Batch Normalization"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "class CNNWithBatchNorm(nn.Module):\n",
        "    def __init__(self):\n",
        "        super(CNNWithBatchNorm, self).__init__()\n",
        "        \n",
        "        self.conv1 = nn.Conv2d(1, 32, 3, padding=1)\n",
        "        self.bn1 = nn.BatchNorm2d(32)\n",
        "        self.relu1 = nn.ReLU()\n",
        "        self.pool1 = nn.MaxPool2d(2, 2)\n",
        "        \n",
        "        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)\n",
        "        self.bn2 = nn.BatchNorm2d(64)\n",
        "        self.relu2 = nn.ReLU()\n",
        "        self.pool2 = nn.MaxPool2d(2, 2)\n",
        "        \n",
        "        self.fc1 = nn.Linear(64 * 7 * 7, 128)\n",
        "        self.bn3 = nn.BatchNorm1d(128)\n",
        "        self.relu3 = nn.ReLU()\n",
        "        self.dropout = nn.Dropout(0.5)\n",
        "        self.fc2 = nn.Linear(128, 10)\n",
        "        \n",
        "    def forward(self, x):\n",
        "        x = self.pool1(self.relu1(self.bn1(self.conv1(x))))\n",
        "        x = self.pool2(self.relu2(self.bn2(self.conv2(x))))\n",
        "        x = x.view(x.size(0), -1)\n",
        "        x = self.fc1(x)\n",
        "        x = self.relu3(self.bn3(x))\n",
        "        x = self.dropout(x)\n",
        "        x = self.fc2(x)\n",
        "        return x\n",
        "\n",
        "print(\"Batch Normalization Benefits:\")\n",
        "print(\"1. Normalizes activations\")\n",
        "print(\"2. Reduces internal covariate shift\")\n",
        "print(\"3. Allows higher learning rates\")\n",
        "print(\"4. Acts as regularization\")\n",
        "print(\"5. Faster convergence\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Data Augmentation"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "augmented_transform = transforms.Compose([\n",
        "    transforms.RandomRotation(10),\n",
        "    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),\n",
        "    transforms.ToTensor(),\n",
        "    transforms.Normalize((0.1307,), (0.3081,)),\n",
        "    transforms.RandomErasing(p=0.3, scale=(0.02, 0.1))\n",
        "])\n",
        "\n",
        "train_dataset_aug = datasets.MNIST('./data', train=True, \n",
        "                                   transform=augmented_transform)\n",
        "train_loader_aug = DataLoader(train_dataset_aug, batch_size=64, shuffle=True)\n",
        "\n",
        "print(\"Data Augmentation Applied:\")\n",
        "print(\"- Random rotation (±10°)\")\n",
        "print(\"- Random translation (10%)\")\n",
        "print(\"- Random erasing (30% probability)\")\n",
        "print(\"\\nThis helps model generalize better!\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Confusion Matrix"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "def plot_confusion_matrix(model, test_loader, device):\n",
        "    model.eval()\n",
        "    all_preds = []\n",
        "    all_labels = []\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for images, labels in test_loader:\n",
        "            images = images.to(device)\n",
        "            outputs = model(images)\n",
        "            _, predictions = outputs.max(1)\n",
        "            \n",
        "            all_preds.extend(predictions.cpu().numpy())\n",
        "            all_labels.extend(labels.numpy())\n",
        "    \n",
        "    cm = confusion_matrix(all_labels, all_preds)\n",
        "    \n",
        "    plt.figure(figsize=(10, 8))\n",
        "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', \n",
        "                xticklabels=range(10), yticklabels=range(10))\n",
        "    plt.xlabel('Predicted Label')\n",
        "    plt.ylabel('True Label')\n",
        "    plt.title('Confusion Matrix - MNIST Classification')\n",
        "    plt.show()\n",
        "    \n",
        "    print(\"Per-digit accuracy:\")\n",
        "    for i in range(10):\n",
        "        acc = cm[i, i] / cm[i].sum() * 100\n",
        "        print(f\"Digit {i}: {acc:.1f}%\")\n",
        "\n",
        "plot_confusion_matrix(model, test_loader, device)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "---\n",
        "# Summary\n",
        "\n",
        "## What We Accomplished:\n",
        "\n",
        "✅ **Part 1:** Understood convolution operations and activation functions  \n",
        "✅ **Part 2:** Built and trained CNNs from scratch  \n",
        "✅ **Part 3:** Visualized filters and analyzed errors  \n",
        "✅ **Part 4:** Experimented with hyperparameters  \n",
        "✅ **Bonus:** Implemented advanced techniques\n",
        "\n",
        "## Key Takeaways:\n",
        "\n",
        "1. **CNNs preserve spatial structure** unlike fully-connected networks\n",
        "2. **Batch Normalization** stabilizes training\n",
        "3. **Learning rate** is critical for convergence\n",
        "4. **Adam optimizer** works well as default\n",
        "5. **Data augmentation** improves generalization\n",
        "6. **Error analysis** reveals model weaknesses\n",
        "\n",
        "## Next Steps:\n",
        "\n",
        "- Try Fashion-MNIST or CIFAR-10\n",
        "- Implement ResNet or other architectures\n",
        "- Explore transfer learning\n",
        "- Deploy models in production\n",
        "\n",
        "---\n",
        "\n",
        "*End of Solutions Notebook*"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.8.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
