{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "title-cell",
   "metadata": {},
   "source": [
    "# LDSCI6211 Machine Learning and Data Mining II\n",
    "## Lab 9: Variational Autoencoders & Generative Adversarial Networks\n",
    "\n",
    "**Dr Waleed Iqbal — Northeastern University London**\n",
    "\n",
    "---\n",
    "\n",
    "### Lab Overview\n",
    "\n",
    "This lab has two parts, each taking approximately **60 minutes**:\n",
    "\n",
    "| Part | Topic |\n",
    "|------|-------|\n",
    "| 1 | Variational Autoencoders (VAE) on Fashion-MNIST|\n",
    "| 2 | Generative Adversarial Networks (GAN) on MNIST |\n",
    "\n",
    "### Learning Outcomes\n",
    "By the end of this lab you should be able to:\n",
    "1. Implement the reparameterisation trick and explain *why* it is needed.\n",
    "2. Build a VAE in PyTorch and decompose the ELBO loss into its two terms.\n",
    "3. Visualise and interpret a structured VAE latent space.\n",
    "4. Implement the two-step GAN training loop (update D, then update G).\n",
    "5. Observe and diagnose mode collapse and training instability.\n",
    "6. Compare generated sample quality between a VAE and a GAN.\n",
    "\n",
    "### Runtime\n",
    "> ⚠️ **Enable GPU before starting:** `Runtime → Change runtime type → T4 GPU`  \n",
    "> All experiments are designed to complete within 5–10 minutes of training on the free Colab T4."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "setup-header",
   "metadata": {},
   "source": [
    "---\n",
    "## Setup\n",
    "Run the cell below once to install and import everything needed for both parts."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "setup-cell",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Imports ──────────────────────────────────────────────────────────────────\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "from matplotlib.colors import ListedColormap\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ── Device ───────────────────────────────────────────────────────────────────\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Using device: {device}')\n",
    "if device.type == 'cpu':\n",
    "    print(' No GPU detected. Training will be slower. '\n",
    "          'Go to Runtime → Change runtime type → T4 GPU.')\n",
    "\n",
    "# ── Reproducibility ──────────────────────────────────────────────────────────\n",
    "torch.manual_seed(42)\n",
    "np.random.seed(42)\n",
    "print('Setup complete')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "part1-header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 1 — Variational Autoencoders (VAE)\n",
    "\n",
    "**Recap from lecture:**\n",
    "A vanilla autoencoder maps each input to a *fixed* point in latent space — random samples from that space produce garbage because there is no structure. A VAE fixes this by making the encoder output a *distribution* $\\mathcal{N}(\\mu, \\sigma^2)$ and regularising it towards $\\mathcal{N}(\\mathbf{0}, \\mathbf{I})$ using KL divergence. Any point sampled from the prior then decodes to something meaningful.\n",
    "\n",
    "The full ELBO loss is:\n",
    "$$\\mathcal{L}(\\theta, \\phi; \\mathbf{x}) = \\underbrace{-\\|\\mathbf{x} - \\hat{\\mathbf{x}}\\|^2}_{\\text{Reconstruction}} - \\underbrace{\\frac{1}{2}\\sum_j \\left(\\mu_j^2 + \\sigma_j^2 - \\log\\sigma_j^2 - 1\\right)}_{\\text{KL Regularisation}}$$\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-data-header",
   "metadata": {},
   "source": [
    "## 1.1 Load Fashion-MNIST\n",
    "\n",
    "We use **Fashion-MNIST** (10 clothing categories, 28×28 greyscale images). It is more visually interesting than plain digits and shows the VAE's generative quality more clearly."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-data",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Data ─────────────────────────────────────────────────────────────────────\n",
    "transform = transforms.Compose([\n",
    "    transforms.ToTensor(),          # pixels → [0, 1]\n",
    "])\n",
    "\n",
    "train_dataset = torchvision.datasets.FashionMNIST(\n",
    "    root='./data', train=True,  download=True, transform=transform)\n",
    "test_dataset  = torchvision.datasets.FashionMNIST(\n",
    "    root='./data', train=False, download=True, transform=transform)\n",
    "\n",
    "train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True,  num_workers=2)\n",
    "test_loader  = DataLoader(test_dataset,  batch_size=128, shuffle=False, num_workers=2)\n",
    "\n",
    "CLASS_NAMES = ['T-shirt', 'Trouser', 'Pullover', 'Dress', 'Coat',\n",
    "               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']\n",
    "\n",
    "# ── Visualise a few samples ───────────────────────────────────────────────────\n",
    "fig, axes = plt.subplots(2, 8, figsize=(14, 4))\n",
    "for i, ax in enumerate(axes.flat):\n",
    "    img, label = train_dataset[i]\n",
    "    ax.imshow(img.squeeze(), cmap='gray')\n",
    "    ax.set_title(CLASS_NAMES[label], fontsize=8)\n",
    "    ax.axis('off')\n",
    "plt.suptitle('Fashion-MNIST Samples', fontsize=12, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "print(f'Training set: {len(train_dataset):,} images | Test set: {len(test_dataset):,} images')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-arch-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.2 Build the VAE Architecture\n",
    "\n",
    "The VAE has three components:\n",
    "\n",
    "| Component | Role | Output |\n",
    "|-----------|------|--------|\n",
    "| **Encoder** $q_\\phi(z\\|x)$ | Compress image to distribution parameters | $(\\mu, \\log\\sigma^2)$ |\n",
    "| **Sampling** (reparameterisation) | Draw $z$ differentiably | $z = \\mu + \\sigma \\odot \\varepsilon$ |\n",
    "| **Decoder** $p_\\theta(x\\|z)$ | Reconstruct image from $z$ | $\\hat{x} \\in [0,1]^{784}$ |\n",
    "\n",
    "**Why do we output $\\log\\sigma^2$ rather than $\\sigma$?**  \n",
    "$\\log\\sigma^2$ is unconstrained (any real number), which is easier to learn. We recover $\\sigma = \\exp(0.5 \\cdot \\log\\sigma^2)$."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-model",
   "metadata": {},
   "outputs": [],
   "source": [
    "LATENT_DIM = 2   # 2-D so we can plot the latent space as a 2-D scatter\n",
    "\n",
    "class Encoder(nn.Module):\n",
    "    \"\"\"Maps a 28x28 image to (mu, log_var) in latent space.\"\"\"\n",
    "    def __init__(self, latent_dim):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            nn.Flatten(),\n",
    "            nn.Linear(784, 512), nn.ReLU(),\n",
    "            nn.Linear(512, 256), nn.ReLU(),\n",
    "        )\n",
    "        self.fc_mu      = nn.Linear(256, latent_dim)\n",
    "        self.fc_log_var = nn.Linear(256, latent_dim)\n",
    "\n",
    "    def forward(self, x):\n",
    "        h       = self.net(x)\n",
    "        mu      = self.fc_mu(h)\n",
    "        log_var = self.fc_log_var(h)\n",
    "        return mu, log_var\n",
    "\n",
    "\n",
    "class Decoder(nn.Module):\n",
    "    \"\"\"Maps a latent vector z back to a 28x28 image.\"\"\"\n",
    "    def __init__(self, latent_dim):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            nn.Linear(latent_dim, 256), nn.ReLU(),\n",
    "            nn.Linear(256, 512),        nn.ReLU(),\n",
    "            nn.Linear(512, 784),        nn.Sigmoid(),  # output in [0,1]\n",
    "        )\n",
    "\n",
    "    def forward(self, z):\n",
    "        return self.net(z).view(-1, 1, 28, 28)\n",
    "\n",
    "\n",
    "class VAE(nn.Module):\n",
    "    def __init__(self, latent_dim=2):\n",
    "        super().__init__()\n",
    "        self.encoder = Encoder(latent_dim)\n",
    "        self.decoder = Decoder(latent_dim)\n",
    "\n",
    "    def reparameterise(self, mu, log_var):\n",
    "        \"\"\"z = mu + sigma * epsilon,  epsilon ~ N(0,I)\"\"\"\n",
    "        # ── KEY STEP ──────────────────────────────────────────────────────────\n",
    "        # We do NOT sample from N(mu, sigma) directly because a stochastic node\n",
    "        # blocks gradient flow. Instead we sample epsilon from N(0,I) — which\n",
    "        # has no learnable parameters — and compute z deterministically.\n",
    "        # Gradients can then flow through mu and sigma to the encoder.\n",
    "        # ─────────────────────────────────────────────────────────────────────\n",
    "        if self.training:\n",
    "            std     = torch.exp(0.5 * log_var)   # sigma = exp(0.5 * log(sigma^2))\n",
    "            epsilon = torch.randn_like(std)       # epsilon ~ N(0, I)\n",
    "            return mu + std * epsilon             # z = mu + sigma * epsilon\n",
    "        else:\n",
    "            return mu   # at inference, use the mean (no noise)\n",
    "\n",
    "    def forward(self, x):\n",
    "        mu, log_var = self.encoder(x)\n",
    "        z           = self.reparameterise(mu, log_var)\n",
    "        x_hat       = self.decoder(z)\n",
    "        return x_hat, mu, log_var\n",
    "\n",
    "\n",
    "# ── Instantiate and print a summary ──────────────────────────────────────────\n",
    "vae = VAE(latent_dim=LATENT_DIM).to(device)\n",
    "\n",
    "total_params = sum(p.numel() for p in vae.parameters())\n",
    "print(f'VAE total parameters: {total_params:,}')\n",
    "print(vae)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-loss-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.3 The ELBO Loss Function\n",
    "\n",
    "The loss has exactly two terms:\n",
    "\n",
    "**Term 1 — Reconstruction loss** (binary cross-entropy on pixel values)  \n",
    "Penalises the decoder when $\\hat{x}$ differs from $x$.\n",
    "\n",
    "**Term 2 — KL divergence** (closed-form for diagonal Gaussian)  \n",
    "$D_{\\text{KL}} = \\frac{1}{2} \\sum_j \\left( \\mu_j^2 + \\sigma_j^2 - \\log\\sigma_j^2 - 1 \\right)$  \n",
    "This equals zero only when $\\mu_j = 0$ and $\\sigma_j = 1$ — i.e. the encoder exactly matches the prior.\n",
    "\n",
    "We *minimise* the loss (maximise the ELBO), so both terms compete: reconstruction wants to encode all information precisely, KL wants everything collapsed to the prior."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-loss",
   "metadata": {},
   "outputs": [],
   "source": [
    "def vae_loss(x, x_hat, mu, log_var, beta=1.0):\n",
    "    \"\"\"\n",
    "    ELBO loss = Reconstruction loss + beta * KL divergence\n",
    "\n",
    "    beta=1.0  → standard VAE (Kingma & Welling 2014)\n",
    "    beta>1.0  → beta-VAE: stronger disentanglement, more blurry\n",
    "    beta<1.0  → sharper reconstructions, weaker latent structure\n",
    "    \"\"\"\n",
    "    # ── Term 1: Reconstruction ─────────────────────────────────────────────\n",
    "    # Binary cross-entropy: compares pixel-wise probabilities.\n",
    "    # reduction='sum' gives per-sample total; we normalise by batch size later.\n",
    "    recon_loss = F.binary_cross_entropy(x_hat, x, reduction='sum')\n",
    "\n",
    "    # ── Term 2: KL divergence (closed form for diagonal Gaussian) ──────────\n",
    "    # D_KL(N(mu, sigma^2) || N(0,I)) = 0.5 * sum(mu^2 + sigma^2 - log(sigma^2) - 1)\n",
    "    kl_loss = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp())\n",
    "\n",
    "    # Normalise by batch size so the loss scale is independent of batch size\n",
    "    batch_size = x.size(0)\n",
    "    return (recon_loss + beta * kl_loss) / batch_size, \\\n",
    "           recon_loss.item() / batch_size, \\\n",
    "           kl_loss.item()    / batch_size\n",
    "\n",
    "\n",
    "# ── Quick sanity-check ────────────────────────────────────────────────────────\n",
    "x_sample = next(iter(train_loader))[0][:4].to(device)\n",
    "x_hat, mu_out, logvar_out = vae(x_sample)\n",
    "loss, r, kl = vae_loss(x_sample, x_hat, mu_out, logvar_out)\n",
    "print(f'Sanity check — Total loss: {loss.item():.2f}  '\n",
    "      f'| Recon: {r:.2f}  | KL: {kl:.4f}')\n",
    "print(f'mu range:  [{mu_out.min().item():.3f}, {mu_out.max().item():.3f}]')\n",
    "print(f'σ  range:  [{logvar_out.exp().sqrt().min().item():.3f}, '\n",
    "      f'{logvar_out.exp().sqrt().max().item():.3f}]')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-train-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.4 Train the VAE\n",
    "\n",
    "Training follows the steps from the lecture:\n",
    "1. **Encode** $x \\rightarrow (\\mu, \\sigma)$\n",
    "2. **Sample** $z = \\mu + \\sigma \\odot \\varepsilon$\n",
    "3. **Decode** $z \\rightarrow \\hat{x}$\n",
    "4. **Compute loss** $= $ Reconstruction $+ $ KL\n",
    "5. **Backprop** through decoder, through the reparameterised $z$, into the encoder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-train",
   "metadata": {},
   "outputs": [],
   "source": [
    "EPOCHS   = 15\n",
    "LR       = 1e-3\n",
    "BETA     = 1.0   # standard VAE; try 4.0 later to see stronger regularisation\n",
    "\n",
    "optimizer = optim.Adam(vae.parameters(), lr=LR)\n",
    "\n",
    "train_losses, recon_losses, kl_losses = [], [], []\n",
    "\n",
    "print(f'Training VAE for {EPOCHS} epochs (latent_dim={LATENT_DIM}, beta={BETA})...')\n",
    "print(f'{\"Epoch\":>6} | {\"Total\":>8} | {\"Recon\":>8} | {\"KL\":>8}')\n",
    "print('-' * 40)\n",
    "\n",
    "for epoch in range(1, EPOCHS + 1):\n",
    "    vae.train()\n",
    "    total_loss = recon_total = kl_total = 0.0\n",
    "\n",
    "    for x_batch, _ in train_loader:\n",
    "        x_batch = x_batch.to(device)\n",
    "\n",
    "        # Forward pass\n",
    "        x_hat, mu, log_var = vae(x_batch)\n",
    "        loss, r, kl = vae_loss(x_batch, x_hat, mu, log_var, beta=BETA)\n",
    "\n",
    "        # Backward pass\n",
    "        optimizer.zero_grad()\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "\n",
    "        total_loss  += loss.item()\n",
    "        recon_total += r\n",
    "        kl_total    += kl\n",
    "\n",
    "    n = len(train_loader)\n",
    "    train_losses.append(total_loss  / n)\n",
    "    recon_losses.append(recon_total / n)\n",
    "    kl_losses.append(kl_total       / n)\n",
    "\n",
    "    print(f'{epoch:>6} | {train_losses[-1]:>8.2f} | '\n",
    "          f'{recon_losses[-1]:>8.2f} | {kl_losses[-1]:>8.4f}')\n",
    "\n",
    "print('\\nTraining complete ✓')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-losscurve-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.5 Inspect the Loss Curves\n",
    "\n",
    "**What to look for:**\n",
    "- **Reconstruction loss** should decrease monotonically — the decoder is getting better.\n",
    "- **KL loss** starts near zero (encoder ignores the prior at first) and then rises as the KL term pulls the encoder towards $\\mathcal{N}(\\mathbf{0}, \\mathbf{I})$.\n",
    "- If KL stays at zero for many epochs, the model is suffering **posterior collapse**: the encoder ignores the input and the decoder learns to do everything — a known VAE failure mode."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-losscurve",
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "axes[0].plot(train_losses, color='#CC092F', lw=2)\n",
    "axes[0].set_title('Total ELBO Loss', fontweight='bold')\n",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')\n",
    "\n",
    "axes[1].plot(recon_losses, color='steelblue', lw=2)\n",
    "axes[1].set_title('Reconstruction Loss (Term 1)', fontweight='bold')\n",
    "axes[1].set_xlabel('Epoch')\n",
    "\n",
    "axes[2].plot(kl_losses, color='darkorange', lw=2)\n",
    "axes[2].set_title('KL Divergence (Term 2)', fontweight='bold')\n",
    "axes[2].set_xlabel('Epoch')\n",
    "\n",
    "for ax in axes:\n",
    "    ax.grid(alpha=0.3)\n",
    "    ax.spines['top'].set_visible(False)\n",
    "    ax.spines['right'].set_visible(False)\n",
    "\n",
    "plt.suptitle('VAE Training Curves', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-recon-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.6 Reconstruction Quality\n",
    "\n",
    "Compare original images (top row) with their VAE reconstructions (bottom row).  \n",
    "Notice the slight **blurriness** — this is the MSE/BCE averaging effect from the lecture."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-recon",
   "metadata": {},
   "outputs": [],
   "source": [
    "vae.eval()\n",
    "with torch.no_grad():\n",
    "    x_test, labels = next(iter(test_loader))\n",
    "    x_test = x_test[:10].to(device)\n",
    "    x_hat_test, _, _ = vae(x_test)\n",
    "\n",
    "fig, axes = plt.subplots(2, 10, figsize=(15, 4))\n",
    "for i in range(10):\n",
    "    # Original\n",
    "    axes[0, i].imshow(x_test[i].cpu().squeeze(), cmap='gray')\n",
    "    axes[0, i].set_title(CLASS_NAMES[labels[i]], fontsize=7)\n",
    "    axes[0, i].axis('off')\n",
    "    # Reconstruction\n",
    "    axes[1, i].imshow(x_hat_test[i].cpu().squeeze(), cmap='gray')\n",
    "    axes[1, i].axis('off')\n",
    "\n",
    "axes[0, 0].set_ylabel('Original',       fontsize=9, rotation=0, labelpad=55)\n",
    "axes[1, 0].set_ylabel('Reconstructed',  fontsize=9, rotation=0, labelpad=55)\n",
    "plt.suptitle('VAE Reconstruction Quality', fontsize=12, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-latent-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.7 Visualise the Latent Space\n",
    "\n",
    "Because we set `LATENT_DIM = 2`, we can plot every test image as a 2-D point $(\\mu_1, \\mu_2)$ coloured by class.  \n",
    "\n",
    "**What a well-trained VAE latent space looks like:**\n",
    "- Clusters for each class, roughly centred at the origin.\n",
    "- Clusters *overlap* at their boundaries — this means interpolating between them gives plausible in-between images.\n",
    "- No large empty gaps (completeness).\n",
    "\n",
    "Compare this to what a vanilla AE would show: tight, isolated point clouds with large empty voids between them."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-latent",
   "metadata": {},
   "outputs": [],
   "source": [
    "vae.eval()\n",
    "all_mu, all_labels = [], []\n",
    "\n",
    "with torch.no_grad():\n",
    "    for x_batch, y_batch in test_loader:\n",
    "        mu, _ = vae.encoder(x_batch.to(device))\n",
    "        all_mu.append(mu.cpu().numpy())\n",
    "        all_labels.append(y_batch.numpy())\n",
    "\n",
    "all_mu     = np.concatenate(all_mu,     axis=0)\n",
    "all_labels = np.concatenate(all_labels, axis=0)\n",
    "\n",
    "# ── Plot ──────────────────────────────────────────────────────────────────────\n",
    "fig, ax = plt.subplots(figsize=(9, 7))\n",
    "scatter = ax.scatter(all_mu[:, 0], all_mu[:, 1],\n",
    "                     c=all_labels, cmap='tab10',\n",
    "                     alpha=0.4, s=5)\n",
    "\n",
    "# Add class-centroid labels\n",
    "for cls in range(10):\n",
    "    mask = all_labels == cls\n",
    "    cx, cy = all_mu[mask, 0].mean(), all_mu[mask, 1].mean()\n",
    "    ax.text(cx, cy, CLASS_NAMES[cls], fontsize=8, ha='center',\n",
    "            fontweight='bold',\n",
    "            bbox=dict(boxstyle='round,pad=0.2', fc='white', alpha=0.6))\n",
    "\n",
    "cbar = plt.colorbar(scatter, ax=ax, ticks=range(10))\n",
    "cbar.set_ticklabels(CLASS_NAMES)\n",
    "ax.set_xlabel('z₁ (μ₁)', fontsize=11)\n",
    "ax.set_ylabel('z₂ (μ₂)', fontsize=11)\n",
    "ax.set_title('VAE Latent Space — Test Set (10,000 images)', fontsize=12, fontweight='bold')\n",
    "ax.grid(alpha=0.2)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print('Observation: Clusters are continuous and mostly overlap — '\n",
    "      'this is the regularised latent space the KL term produces.')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-gen-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.8 Generate New Samples\n",
    "\n",
    "Because the KL term forces the latent space towards $\\mathcal{N}(\\mathbf{0}, \\mathbf{I})$, **any random sample from the standard Gaussian decodes to a meaningful image** — no cherry-picking needed.\n",
    "\n",
    "We generate by sampling a grid of points in $[-3, 3]^2$ and decoding each one."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-gen",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── 2-D grid of latent points ─────────────────────────────────────────────────\n",
    "n     = 15       # grid size\n",
    "limit = 2.5      # range in latent space\n",
    "\n",
    "grid_z1 = np.linspace(-limit, limit, n)\n",
    "grid_z2 = np.linspace(-limit, limit, n)\n",
    "canvas  = np.zeros((28 * n, 28 * n))\n",
    "\n",
    "vae.eval()\n",
    "with torch.no_grad():\n",
    "    for i, z2 in enumerate(grid_z2[::-1]):   # flip so top = positive z2\n",
    "        for j, z1 in enumerate(grid_z1):\n",
    "            z      = torch.tensor([[z1, z2]], dtype=torch.float32).to(device)\n",
    "            x_gen  = vae.decoder(z).cpu().squeeze().numpy()\n",
    "            canvas[i*28:(i+1)*28, j*28:(j+1)*28] = x_gen\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(12, 12))\n",
    "ax.imshow(canvas, cmap='gray')\n",
    "ax.set_xticks(np.arange(0, 28*n, 28) + 14)\n",
    "ax.set_xticklabels([f'{z:.1f}' for z in grid_z1], fontsize=6)\n",
    "ax.set_yticks(np.arange(0, 28*n, 28) + 14)\n",
    "ax.set_yticklabels([f'{z:.1f}' for z in grid_z2[::-1]], fontsize=6)\n",
    "ax.set_xlabel('z₁', fontsize=12)\n",
    "ax.set_ylabel('z₂', fontsize=12)\n",
    "ax.set_title('VAE Generative Grid — Each cell is a decoded point from the prior',\n",
    "             fontsize=11, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "vae-interp-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 1.9 Latent Space Interpolation\n",
    "\n",
    "We pick two real test images, encode them to get their latent vectors $z_A$ and $z_B$, then linearly interpolate: $z(t) = (1-t)\\cdot z_A + t \\cdot z_B$ for $t \\in [0, 1]$.\n",
    "\n",
    "In a well-structured latent space, the intermediate decoded images should transition **smoothly and meaningfully** — not teleport through noise."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "vae-interp",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pick two images from different classes to make the interpolation obvious\n",
    "PAIR_IDX = [(0, 1)]   # indices into the test set\n",
    "\n",
    "# Find one T-shirt (class 0) and one Ankle boot (class 9)\n",
    "indices_A = (np.array(test_dataset.targets) == 0).nonzero()[0][:1]\n",
    "indices_B = (np.array(test_dataset.targets) == 9).nonzero()[0][:1]\n",
    "\n",
    "img_A = test_dataset[indices_A[0]][0].unsqueeze(0).to(device)\n",
    "img_B = test_dataset[indices_B[0]][0].unsqueeze(0).to(device)\n",
    "\n",
    "n_steps = 10\n",
    "alphas  = np.linspace(0, 1, n_steps)\n",
    "\n",
    "vae.eval()\n",
    "with torch.no_grad():\n",
    "    mu_A, _ = vae.encoder(img_A)\n",
    "    mu_B, _ = vae.encoder(img_B)\n",
    "\n",
    "    interpolated = []\n",
    "    for alpha in alphas:\n",
    "        z_interp = (1 - alpha) * mu_A + alpha * mu_B\n",
    "        interpolated.append(vae.decoder(z_interp).cpu().squeeze().numpy())\n",
    "\n",
    "fig, axes = plt.subplots(1, n_steps, figsize=(16, 2.5))\n",
    "for i, (ax, img) in enumerate(zip(axes, interpolated)):\n",
    "    ax.imshow(img, cmap='gray')\n",
    "    ax.set_title(f'α={alphas[i]:.1f}', fontsize=7)\n",
    "    ax.axis('off')\n",
    "\n",
    "axes[0].set_title('T-shirt\\nα=0.0', fontsize=7, color='steelblue', fontweight='bold')\n",
    "axes[-1].set_title('Boot\\nα=1.0',  fontsize=7, color='#CC092F',   fontweight='bold')\n",
    "plt.suptitle('VAE Latent Interpolation: T-shirt → Ankle Boot',\n",
    "             fontsize=11, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "part2-header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 2 — Generative Adversarial Networks (GAN)\n",
    "\n",
    "**Recap from lecture:**\n",
    "A GAN trains two networks in opposition. The **Generator** $G$ maps random noise $z$ to fake images. The **Discriminator** $D$ scores images as real or fake. Their losses are:\n",
    "\n",
    "$$\\mathcal{L}_D = -\\left[\\log D(x) + \\log(1 - D(G(z)))\\right]$$\n",
    "\n",
    "$$\\mathcal{L}_G = -\\log D(G(z)) \\quad \\text{(non-saturating fix)}$$\n",
    "\n",
    "Training alternates: one step updates $D$ (G frozen), the next updates $G$ (D frozen, gradient flows *through* D).\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-data-header",
   "metadata": {},
   "source": [
    "## 2.1 Load MNIST for the GAN\n",
    "\n",
    "We use **MNIST** digits here. GANs can focus on a single easy distribution, letting us see results quickly. We rescale pixels to $[-1, 1]$ to match the Generator's Tanh output."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-data",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Rescale to [-1, 1] — matches Tanh output of the Generator\n",
    "gan_transform = transforms.Compose([\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize([0.5], [0.5])   # (pixel - 0.5) / 0.5  →  [-1, 1]\n",
    "])\n",
    "\n",
    "mnist_train = torchvision.datasets.MNIST(\n",
    "    root='./data', train=True, download=True, transform=gan_transform)\n",
    "gan_loader = DataLoader(mnist_train, batch_size=128, shuffle=True, num_workers=2)\n",
    "\n",
    "# Preview a batch (undo normalisation for display)\n",
    "sample_imgs, _ = next(iter(gan_loader))\n",
    "grid = torchvision.utils.make_grid(\n",
    "    sample_imgs[:32] * 0.5 + 0.5, nrow=8, padding=2)\n",
    "plt.figure(figsize=(10, 4))\n",
    "plt.imshow(grid.permute(1, 2, 0).squeeze(), cmap='gray')\n",
    "plt.axis('off')\n",
    "plt.title('MNIST Training Samples (rescaled to [-1,1] for display)', fontweight='bold')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-arch-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.2 Generator and Discriminator Architectures\n",
    "\n",
    "We build a **DCGAN-style** architecture (Radford et al. 2016) adapted for 28×28 images:\n",
    "\n",
    "| Network | Layers | Key design choices |\n",
    "|---------|--------|--------------------|\n",
    "| Generator | Linear → reshape → 3× ConvTranspose | Tanh output, BatchNorm+ReLU inside |\n",
    "| Discriminator | 3× Conv (stride 2) → Linear | LeakyReLU (avoids dead neurons), Sigmoid output |\n",
    "\n",
    "**Why LeakyReLU in the Discriminator?**  \n",
    "Standard ReLU kills all negative activations forever. Discriminator gradients must flow back to the Generator — if they vanish inside D, G learns nothing. LeakyReLU keeps a small slope for negatives: $f(x) = x$ if $x > 0$, else $0.2x$."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-model",
   "metadata": {},
   "outputs": [],
   "source": [
    "Z_DIM = 100   # noise vector dimension (standard choice from DCGAN paper)\n",
    "\n",
    "class Generator(nn.Module):\n",
    "    \"\"\"Maps z ~ N(0,I) to a 1x28x28 fake image in [-1,1].\"\"\"\n",
    "    def __init__(self, z_dim=100):\n",
    "        super().__init__()\n",
    "        self.project = nn.Sequential(\n",
    "            nn.Linear(z_dim, 128 * 7 * 7),\n",
    "            nn.BatchNorm1d(128 * 7 * 7),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        self.conv_blocks = nn.Sequential(\n",
    "            # 7×7 → 14×14\n",
    "            nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1),\n",
    "            nn.BatchNorm2d(64), nn.ReLU(),\n",
    "            # 14×14 → 28×28\n",
    "            nn.ConvTranspose2d(64, 1, 4, stride=2, padding=1),\n",
    "            nn.Tanh()   # output in [-1, 1]\n",
    "        )\n",
    "\n",
    "    def forward(self, z):\n",
    "        x = self.project(z).view(-1, 128, 7, 7)\n",
    "        return self.conv_blocks(x)\n",
    "\n",
    "\n",
    "class Discriminator(nn.Module):\n",
    "    \"\"\"Maps a 1x28x28 image to a real/fake probability in (0,1).\"\"\"\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            # 28×28 → 14×14\n",
    "            nn.Conv2d(1, 64, 4, stride=2, padding=1),\n",
    "            nn.LeakyReLU(0.2),\n",
    "            # 14×14 → 7×7\n",
    "            nn.Conv2d(64, 128, 4, stride=2, padding=1),\n",
    "            nn.BatchNorm2d(128), nn.LeakyReLU(0.2),\n",
    "            nn.Flatten(),\n",
    "            nn.Linear(128 * 7 * 7, 1),\n",
    "            nn.Sigmoid()   # output: P(real)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        return self.net(x)\n",
    "\n",
    "\n",
    "# ── Initialise ────────────────────────────────────────────────────────────────\n",
    "G = Generator(Z_DIM).to(device)\n",
    "D = Discriminator().to(device)\n",
    "\n",
    "print(f'Generator     params: {sum(p.numel() for p in G.parameters()):,}')\n",
    "print(f'Discriminator params: {sum(p.numel() for p in D.parameters()):,}')\n",
    "\n",
    "# Sample a fake image to confirm shapes\n",
    "z_test = torch.randn(4, Z_DIM).to(device)\n",
    "fake   = G(z_test)\n",
    "print(f'\\nG output shape: {fake.shape}  (batch=4, C=1, H=28, W=28)')\n",
    "print(f'D output shape: {D(fake).shape}  (batch=4, score)')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-loss-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.3 Loss Functions\n",
    "\n",
    "Both losses are binary cross-entropy (BCE). The key difference:\n",
    "\n",
    "- **$\\mathcal{L}_D$**: D wants $D(x) \\to 1$ (real labelled 1) and $D(G(z)) \\to 0$ (fake labelled 0).\n",
    "- **$\\mathcal{L}_G$**: G wants $D(G(z)) \\to 1$ (fool D into calling fakes \"real\").\n",
    "- We use $-\\log D(G(z))$ instead of $\\log(1-D(G(z)))$ — the **non-saturating fix** because the gradient of $\\log(1-D)$ vanishes when $D \\approx 0$ early in training."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-loss",
   "metadata": {},
   "outputs": [],
   "source": [
    "bce = nn.BCELoss()  # binary cross-entropy\n",
    "\n",
    "def discriminator_loss(D, x_real, z):\n",
    "    \"\"\"\n",
    "    L_D = -[ log D(x_real) + log(1 - D(G(z))) ]\n",
    "    Implemented as BCE with:\n",
    "      real images → target 1\n",
    "      fake images → target 0\n",
    "    \"\"\"\n",
    "    batch_size = x_real.size(0)\n",
    "    real_labels = torch.ones(batch_size, 1).to(device)   # D should output 1 for real\n",
    "    fake_labels = torch.zeros(batch_size, 1).to(device)  # D should output 0 for fake\n",
    "\n",
    "    # Score real images — D(x_real) should be close to 1\n",
    "    d_real   = D(x_real)\n",
    "    loss_real = bce(d_real, real_labels)\n",
    "\n",
    "    # Score fake images — D(G(z)) should be close to 0\n",
    "    fake     = G(z).detach()   # detach: we are NOT updating G here\n",
    "    d_fake   = D(fake)\n",
    "    loss_fake = bce(d_fake, fake_labels)\n",
    "\n",
    "    return loss_real + loss_fake, d_real.mean().item(), d_fake.mean().item()\n",
    "\n",
    "\n",
    "def generator_loss(D, z):\n",
    "    \"\"\"\n",
    "    L_G = -log D(G(z))   [non-saturating]\n",
    "    G wants D to output 1 on fakes → we use target=1.\n",
    "    Gradient flows from D's loss BACK THROUGH D into G.\n",
    "    D's weights are frozen (we do not call optimizer_D.step here).\n",
    "    \"\"\"\n",
    "    batch_size = z.size(0)\n",
    "    real_labels = torch.ones(batch_size, 1).to(device)  # G wants D to say \"real\"\n",
    "\n",
    "    fake   = G(z)         # do NOT detach — we need gradients to flow to G\n",
    "    d_fake = D(fake)      # D is frozen; only used as a differentiable loss signal\n",
    "    return bce(d_fake, real_labels)\n",
    "\n",
    "\n",
    "print('Loss functions defined ✓')\n",
    "print('Note: .detach() in discriminator_loss prevents gradients reaching G during D update.')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-train-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.4 The Two-Step GAN Training Loop\n",
    "\n",
    "Every mini-batch performs **two** backward passes:\n",
    "\n",
    "```\n",
    "Step 1 — Update D  (G frozen via .detach())\n",
    "   L_D = BCE(D(x_real), 1) + BCE(D(G(z).detach()), 0)\n",
    "   optimizer_D.zero_grad() → L_D.backward() → optimizer_D.step()\n",
    "\n",
    "Step 2 — Update G  (D frozen, but gradient flows THROUGH it)\n",
    "   L_G = BCE(D(G(z)), 1)   ← no .detach() on G(z)\n",
    "   optimizer_G.zero_grad() → L_G.backward() → optimizer_G.step()\n",
    "```\n",
    "\n",
    "After each epoch we log $D(x)$ (should stay near 0.5–0.7) and $D(G(z))$ (should rise as G improves)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-train",
   "metadata": {},
   "outputs": [],
   "source": [
    "GAN_EPOCHS = 20\n",
    "LR_D = 2e-4\n",
    "LR_G = 2e-4\n",
    "\n",
    "optimizer_D = optim.Adam(D.parameters(), lr=LR_D, betas=(0.5, 0.999))\n",
    "optimizer_G = optim.Adam(G.parameters(), lr=LR_G, betas=(0.5, 0.999))\n",
    "# betas=(0.5, 0.999) is the DCGAN recommendation — lower momentum for stability\n",
    "\n",
    "# Fixed noise for consistent sample grid across epochs\n",
    "fixed_z = torch.randn(64, Z_DIM).to(device)\n",
    "\n",
    "history = {'loss_D': [], 'loss_G': [], 'D_x': [], 'D_Gz': []}\n",
    "sample_grids = []  # save sample images every few epochs\n",
    "\n",
    "print(f'Training GAN for {GAN_EPOCHS} epochs...')\n",
    "print(f'{\"Epoch\":>6} | {\"Loss_D\":>8} | {\"Loss_G\":>8} | {\"D(x)\":>6} | {\"D(G(z))\":>8}')\n",
    "print('-' * 50)\n",
    "\n",
    "for epoch in range(1, GAN_EPOCHS + 1):\n",
    "    G.train(); D.train()\n",
    "    epoch_ld = epoch_lg = epoch_dx = epoch_dgz = 0.0\n",
    "\n",
    "    for x_real, _ in gan_loader:\n",
    "        x_real = x_real.to(device)\n",
    "        bsz    = x_real.size(0)\n",
    "        z      = torch.randn(bsz, Z_DIM).to(device)\n",
    "\n",
    "        # ── Step 1: Update Discriminator (G is frozen via .detach()) ─────────\n",
    "        optimizer_D.zero_grad()\n",
    "        ld, dx, dgz = discriminator_loss(D, x_real, z)\n",
    "        ld.backward()\n",
    "        optimizer_D.step()\n",
    "\n",
    "        # ── Step 2: Update Generator (D is frozen; gradient flows through it) ─\n",
    "        z = torch.randn(bsz, Z_DIM).to(device)  # fresh noise for G update\n",
    "        optimizer_G.zero_grad()\n",
    "        lg = generator_loss(D, z)\n",
    "        lg.backward()\n",
    "        optimizer_G.step()\n",
    "\n",
    "        epoch_ld  += ld.item()\n",
    "        epoch_lg  += lg.item()\n",
    "        epoch_dx  += dx\n",
    "        epoch_dgz += dgz\n",
    "\n",
    "    n = len(gan_loader)\n",
    "    history['loss_D'].append(epoch_ld  / n)\n",
    "    history['loss_G'].append(epoch_lg  / n)\n",
    "    history['D_x'].append(epoch_dx    / n)\n",
    "    history['D_Gz'].append(epoch_dgz  / n)\n",
    "\n",
    "    print(f'{epoch:>6} | {history[\"loss_D\"][-1]:>8.4f} | {history[\"loss_G\"][-1]:>8.4f} | '\n",
    "          f'{history[\"D_x\"][-1]:>6.3f} | {history[\"D_Gz\"][-1]:>8.3f}')\n",
    "\n",
    "    # Save sample grid every 5 epochs\n",
    "    if epoch % 5 == 0 or epoch == 1:\n",
    "        G.eval()\n",
    "        with torch.no_grad():\n",
    "            imgs = G(fixed_z) * 0.5 + 0.5   # rescale to [0,1]\n",
    "        grid = torchvision.utils.make_grid(imgs, nrow=8, padding=2)\n",
    "        sample_grids.append((epoch, grid.cpu()))\n",
    "        G.train()\n",
    "\n",
    "print('\\nTraining complete ✓')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-losscurve-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.5 GAN Training Dynamics\n",
    "\n",
    "**What healthy GAN training looks like:**\n",
    "- $D(x)$ (discriminator score on real images) stays around 0.6–0.8. If it reaches 1.0, D has won entirely and G gets no gradient.\n",
    "- $D(G(z))$ (score on fakes) starts near 0 and rises gradually as G gets better.\n",
    "- Loss_D and Loss_G should fluctuate without one collapsing to zero — they compete.\n",
    "\n",
    "**Warning signs:**\n",
    "- $D(x) \\approx 1$ and $D(G(z)) \\approx 0$ throughout → G is not learning (discriminator too strong)\n",
    "- $D(G(z)) \\approx 1$ early → mode collapse (G found a few images D always calls real)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-losscurve",
   "metadata": {},
   "outputs": [],
   "source": [
    "epochs_range = range(1, GAN_EPOCHS + 1)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n",
    "\n",
    "# Losses\n",
    "axes[0].plot(epochs_range, history['loss_D'], label='$\\\\mathcal{L}_D$', color='steelblue',  lw=2)\n",
    "axes[0].plot(epochs_range, history['loss_G'], label='$\\\\mathcal{L}_G$', color='#CC092F', lw=2)\n",
    "axes[0].set_title('GAN Losses', fontweight='bold')\n",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')\n",
    "axes[0].legend(); axes[0].grid(alpha=0.3)\n",
    "\n",
    "# D scores\n",
    "axes[1].plot(epochs_range, history['D_x'],  label='D(x) — real',   color='green',    lw=2)\n",
    "axes[1].plot(epochs_range, history['D_Gz'], label='D(G(z)) — fake', color='#CC092F', lw=2, ls='--')\n",
    "axes[1].axhline(0.5, color='gray', ls=':', lw=1.5, label='0.5 equilibrium')\n",
    "axes[1].set_title('Discriminator Scores', fontweight='bold')\n",
    "axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('D output')\n",
    "axes[1].set_ylim(0, 1); axes[1].legend(); axes[1].grid(alpha=0.3)\n",
    "\n",
    "for ax in axes:\n",
    "    ax.spines['top'].set_visible(False)\n",
    "    ax.spines['right'].set_visible(False)\n",
    "\n",
    "plt.suptitle('GAN Training Dynamics', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-progress-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.6 Visual Progress Through Training\n",
    "\n",
    "We saved the Generator output every 5 epochs using the same fixed noise vector. This shows the Generator learning — from pure noise to recognisable digit shapes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-progress",
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, axes = plt.subplots(1, len(sample_grids), figsize=(16, 4))\n",
    "if len(sample_grids) == 1:\n",
    "    axes = [axes]\n",
    "\n",
    "for ax, (epoch, grid) in zip(axes, sample_grids):\n",
    "    ax.imshow(grid.permute(1, 2, 0).squeeze(), cmap='gray')\n",
    "    ax.set_title(f'Epoch {epoch}', fontweight='bold')\n",
    "    ax.axis('off')\n",
    "\n",
    "plt.suptitle('GAN Sample Quality Over Training (fixed noise z)',\n",
    "             fontsize=12, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-final-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.7 Final Generated Samples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-final",
   "metadata": {},
   "outputs": [],
   "source": [
    "G.eval()\n",
    "with torch.no_grad():\n",
    "    z_final = torch.randn(64, Z_DIM).to(device)\n",
    "    fake_imgs = G(z_final) * 0.5 + 0.5   # rescale to [0,1]\n",
    "\n",
    "grid = torchvision.utils.make_grid(fake_imgs, nrow=8, padding=3, normalize=False)\n",
    "\n",
    "plt.figure(figsize=(10, 10))\n",
    "plt.imshow(grid.permute(1, 2, 0).cpu().squeeze(), cmap='gray')\n",
    "plt.axis('off')\n",
    "plt.title('GAN Final Samples — 64 images from random noise', fontsize=12, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "gan-compare-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 2.8 VAE vs. GAN: Side-by-Side Comparison\n",
    "\n",
    "Let's put both models' outputs next to each other for a direct visual comparison."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "gan-compare",
   "metadata": {},
   "outputs": [],
   "source": [
    "N = 8  # images per row\n",
    "\n",
    "# VAE samples: sample z from prior, decode\n",
    "vae.eval()\n",
    "with torch.no_grad():\n",
    "    z_vae = torch.randn(N, LATENT_DIM).to(device)\n",
    "    vae_samples = vae.decoder(z_vae).cpu().squeeze(1)  # [N, 28, 28]\n",
    "\n",
    "# GAN samples\n",
    "G.eval()\n",
    "with torch.no_grad():\n",
    "    z_gan = torch.randn(N, Z_DIM).to(device)\n",
    "    gan_samples = (G(z_gan) * 0.5 + 0.5).cpu().squeeze(1)  # [N, 28, 28]\n",
    "\n",
    "fig, axes = plt.subplots(2, N, figsize=(14, 4))\n",
    "titles = [['VAE sample'] * N, ['GAN sample'] * N]\n",
    "colors = ['steelblue', '#CC092F']\n",
    "model_labels = ['VAE (Fashion-MNIST)', 'GAN (MNIST)']\n",
    "\n",
    "for row, (samples, label, color) in enumerate(\n",
    "        zip([vae_samples, gan_samples], model_labels, colors)):\n",
    "    for col in range(N):\n",
    "        axes[row, col].imshow(samples[col].numpy(), cmap='gray')\n",
    "        axes[row, col].axis('off')\n",
    "    axes[row, 0].set_ylabel(label, fontsize=9, rotation=0,\n",
    "                             labelpad=90, color=color, fontweight='bold')\n",
    "\n",
    "plt.suptitle('VAE vs. GAN Generated Samples', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(\"\"\"\n",
    "Observations to discuss:\n",
    "  VAE: structured, diverse, but softer/blurrier edges\n",
    "       (MSE averaging effect — the core VAE limitation)\n",
    "  GAN: sharper, more photorealistic-looking strokes\n",
    "       but may repeat similar patterns (early mode collapse tendency)\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bonus-header",
   "metadata": {},
   "source": [
    "---\n",
    "## 🚀 Conditional GAN (cGAN)\n",
    "\n",
    "A conditional GAN adds a **class label $c$** as extra input to both $G$ and $D$:\n",
    "$$G(z, c) \\qquad D(x, c)$$\n",
    "This lets you generate images of a *specific* digit on demand.\n",
    "\n",
    "The modification is small: embed the class label as a learned vector and concatenate it to $z$ (for G) or flatten it and append it to the image features (for D). Complete the skeleton below if time permits."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bonus-cgan",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Conditional GAN skeleton ──────────────────────────────────────────\n",
    "NUM_CLASSES = 10\n",
    "EMBED_DIM   = 10   # class embedding size\n",
    "\n",
    "class ConditionalGenerator(nn.Module):\n",
    "    def __init__(self, z_dim=100, num_classes=10, embed_dim=10):\n",
    "        super().__init__()\n",
    "        self.label_embed = nn.Embedding(num_classes, embed_dim)\n",
    "        # TODO: modify the Generator to accept z_dim + embed_dim as input\n",
    "        self.project = nn.Sequential(\n",
    "            nn.Linear(z_dim + embed_dim, 128 * 7 * 7),\n",
    "            nn.BatchNorm1d(128 * 7 * 7), nn.ReLU()\n",
    "        )\n",
    "        self.conv_blocks = nn.Sequential(\n",
    "            nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1),\n",
    "            nn.BatchNorm2d(64), nn.ReLU(),\n",
    "            nn.ConvTranspose2d(64, 1, 4, stride=2, padding=1),\n",
    "            nn.Tanh()\n",
    "        )\n",
    "\n",
    "    def forward(self, z, labels):\n",
    "        c_embed = self.label_embed(labels)       # [B, embed_dim]\n",
    "        zc      = torch.cat([z, c_embed], dim=1) # [B, z_dim + embed_dim]\n",
    "        x       = self.project(zc).view(-1, 128, 7, 7)\n",
    "        return self.conv_blocks(x)\n",
    "\n",
    "\n",
    "cG = ConditionalGenerator().to(device)\n",
    "\n",
    "# Quick shape check\n",
    "z_c    = torch.randn(4, Z_DIM).to(device)\n",
    "labels = torch.randint(0, 10, (4,)).to(device)\n",
    "out    = cG(z_c, labels)\n",
    "print(f'Conditional Generator output: {out.shape}')\n",
    "print('TODO: implement ConditionalDiscriminator and the cGAN training loop.')\n",
    "print('Hint: D receives (image, class_label) and must learn to distinguish '\n",
    "      'real (x, c) pairs from fake (G(z,c), c) pairs.')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "summary-header",
   "metadata": {},
   "source": [
    "---\n",
    "## Lab Summary\n",
    "\n",
    "| Concept | What you implemented |\n",
    "|---------|----------------------|\n",
    "| **Reparameterisation trick** | `z = mu + std * epsilon` with `epsilon ~ N(0,I)` |\n",
    "| **ELBO loss** | Reconstruction (BCE) + KL (closed form) |\n",
    "| **Latent space structure** | 2-D scatter of $\\mu$ coloured by class |\n",
    "| **Latent interpolation** | Linear walk between two encoded images |\n",
    "| **GAN training loop** | Two backward passes: update D, then G |\n",
    "| **Non-saturating fix** | $-\\log D(G(z))$ instead of $\\log(1-D(G(z)))$ |\n",
    "| **DCGAN recipe** | ConvTranspose + BatchNorm + Tanh in G; LeakyReLU in D |\n",
    "| **Training diagnostics** | D scores, loss curves, sample progression |\n",
    "\n",
    "### Key takeaways\n",
    "- The KL term is what makes VAE generation possible — without it, the latent space has holes and random samples decode to garbage.\n",
    "- VAE outputs are blurry because MSE averages multiple valid outputs; GANs avoid this by replacing the pixel-wise loss with a **learned judge** (the Discriminator).\n",
    "- GANs are powerful but fragile: the two-player objective makes training sensitive to learning rate balance and architecture choices.\n",
    "- Modern best-in-class models (Stable Diffusion, DALL-E 3) combine VAE-style latent spaces with diffusion processes — a direction you can explore in the next lecture."
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
