{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "44247142",
   "metadata": {},
   "source": [
    "# Lab: Transformer Concepts from the Lecture Slides — Instructor Version (Coding Exercises with Solutions)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a0650be",
   "metadata": {},
   "source": [
    "## Suggested use in class\n",
    "\n",
    "1. Start a **GPU** runtime in Colab.\n",
    "2. Run the notebook top to bottom once with the default settings.\n",
    "3. Keep the defaults for the first pass so the lab fits comfortably on a free T4.\n",
    "4. Use the exercise prompts to connect the code back to the lecture slides.\n",
    "5. Spend most of the discussion time on the attention plots, masking, and the training vs inference sections.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ef07f64c",
   "metadata": {},
   "source": [
    "## Industry-level problem framing\n",
    "\n",
    "Use this lab as a **small industry prototype** for **text routing**.\n",
    "\n",
    "Imagine a company receives a large stream of incoming text items such as support requests, incident summaries, product feedback, or internal tickets. A model has to read each sequence and route it to the correct queue.\n",
    "\n",
    "In this notebook:\n",
    "- the downloaded 20 Newsgroups categories act as a **stand-in** for real business queues,\n",
    "- the goal is to keep the implementation small enough for a **free Colab T4**, and\n",
    "- the discussion stays inside the lecture-slide concepts: embeddings, positional encoding, self-attention, multi-head attention, layer normalization, feed-forward networks, masking, and training/inference.\n",
    "\n",
    "So the task is realistic in **problem framing**, while the model remains intentionally compact for teaching and for free-tier hardware.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1a834ddc",
   "metadata": {},
   "source": [
    "> **Instructor note:** This version includes worked coding solutions for every exercise.  \n",
    "> The scope is kept to the concepts shown in the lecture slides."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c8174681",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Core imports and T4-friendly setup\n",
    "import math\n",
    "import random\n",
    "import re\n",
    "from collections import Counter\n",
    "from contextlib import nullcontext\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "from sklearn.datasets import fetch_20newsgroups\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "SEED = 42\n",
    "random.seed(SEED)\n",
    "np.random.seed(SEED)\n",
    "torch.manual_seed(SEED)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed_all(SEED)\n",
    "    torch.backends.cuda.matmul.allow_tf32 = True\n",
    "    torch.backends.cudnn.allow_tf32 = True\n",
    "\n",
    "try:\n",
    "    torch.set_float32_matmul_precision(\"high\")\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"CPU\"\n",
    "print(\"Using device:\", device)\n",
    "print(\"Device name:\", gpu_name)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fdd9b805",
   "metadata": {},
   "source": [
    "## Part 0 — T4 runtime check and lab configuration\n",
    "\n",
    "The defaults below are chosen so the notebook runs comfortably on a free Colab T4:\n",
    "\n",
    "- compact sequence length,\n",
    "- compact vocabulary,\n",
    "- two encoder blocks,\n",
    "- mixed precision on CUDA,\n",
    "- moderate batch size.\n",
    "\n",
    "These are practical runtime choices only. The conceptual focus stays on the slide topics.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d540cad9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# T4-oriented lab defaults\n",
    "USE_GPU = device.type == \"cuda\"\n",
    "AMP_ENABLED = USE_GPU\n",
    "\n",
    "N_TRAIN_PER_CLASS = 500\n",
    "N_TEST_PER_CLASS = 200\n",
    "\n",
    "MAX_VOCAB = 8000\n",
    "MAX_LEN = 128\n",
    "\n",
    "BATCH_SIZE = 128 if USE_GPU else 64\n",
    "NUM_WORKERS = 2 if USE_GPU else 0\n",
    "PIN_MEMORY = USE_GPU\n",
    "\n",
    "EPOCHS = 5 if USE_GPU else 4\n",
    "LR = 3e-4\n",
    "WEIGHT_DECAY = 1e-4\n",
    "\n",
    "print(\"AMP enabled:\", AMP_ENABLED)\n",
    "print(\"Batch size:\", BATCH_SIZE)\n",
    "print(\"Num workers:\", NUM_WORKERS)\n",
    "print(\"Train samples per class:\", N_TRAIN_PER_CLASS)\n",
    "print(\"Test samples per class:\", N_TEST_PER_CLASS)\n",
    "print(\"Max vocabulary:\", MAX_VOCAB)\n",
    "print(\"Max sequence length:\", MAX_LEN)\n",
    "print(\"Epochs:\", EPOCHS)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5ed2799f",
   "metadata": {},
   "source": [
    "## Part A — Download a small text corpus directly in code\n",
    "\n",
    "We download a small subset of 20 Newsgroups directly through `scikit-learn`.\n",
    "This is only a convenient text source for the lab so we can build input IDs, embeddings, positional encodings, attention, layer normalization, and masking without needing any manual file upload.\n",
    "\n",
    "For the **industry framing**, think of each category as a destination queue in a text-routing workflow. The downloaded corpus simply gives us a lightweight stand-in for that operational setting while staying inside the lecture-slide concepts.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d77ae22",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Pick a small but diverse subset of categories\n",
    "CATEGORIES = [\n",
    "    \"comp.graphics\",\n",
    "    \"sci.space\",\n",
    "    \"rec.sport.baseball\",\n",
    "    \"talk.politics.mideast\",\n",
    "]\n",
    "\n",
    "train_raw = fetch_20newsgroups(\n",
    "    subset=\"train\",\n",
    "    categories=CATEGORIES,\n",
    "    remove=(\"headers\", \"footers\", \"quotes\"),\n",
    "    shuffle=True,\n",
    "    random_state=SEED,\n",
    ")\n",
    "\n",
    "test_raw = fetch_20newsgroups(\n",
    "    subset=\"test\",\n",
    "    categories=CATEGORIES,\n",
    "    remove=(\"headers\", \"footers\", \"quotes\"),\n",
    "    shuffle=True,\n",
    "    random_state=SEED,\n",
    ")\n",
    "\n",
    "label_names = train_raw.target_names\n",
    "print(\"Label names:\", label_names)\n",
    "print(\"Train examples:\", len(train_raw.data))\n",
    "print(\"Test examples:\", len(test_raw.data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37c814b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Keep the lab compact enough for a free T4 run\n",
    "N_TRAIN_PER_CLASS = 500\n",
    "N_TEST_PER_CLASS = 200\n",
    "\n",
    "def stratified_take(texts, labels, n_per_class, seed=42):\n",
    "    rng = np.random.default_rng(seed)\n",
    "    selected_idx = []\n",
    "    labels = np.array(labels)\n",
    "\n",
    "    for cls in sorted(np.unique(labels)):\n",
    "        idx = np.where(labels == cls)[0]\n",
    "        rng.shuffle(idx)\n",
    "        selected_idx.extend(idx[: min(n_per_class, len(idx))])\n",
    "\n",
    "    rng.shuffle(selected_idx)\n",
    "    return [texts[i] for i in selected_idx], labels[selected_idx]\n",
    "\n",
    "train_texts, train_labels = stratified_take(train_raw.data, train_raw.target, N_TRAIN_PER_CLASS, seed=SEED)\n",
    "test_texts, test_labels = stratified_take(test_raw.data, test_raw.target, N_TEST_PER_CLASS, seed=SEED)\n",
    "\n",
    "# Remove near-empty samples produced by the header/footer/quote removal step\n",
    "def filter_empty(texts, labels, min_chars=20):\n",
    "    out_texts, out_labels = [], []\n",
    "    for text, label in zip(texts, labels):\n",
    "        if isinstance(text, str) and len(text.strip()) >= min_chars:\n",
    "            out_texts.append(text)\n",
    "            out_labels.append(int(label))\n",
    "    return out_texts, np.array(out_labels)\n",
    "\n",
    "train_texts, train_labels = filter_empty(train_texts, train_labels)\n",
    "test_texts, test_labels = filter_empty(test_texts, test_labels)\n",
    "\n",
    "print(\"Filtered train size:\", len(train_texts))\n",
    "print(\"Filtered test size:\", len(test_texts))\n",
    "\n",
    "for class_id, class_name in enumerate(label_names):\n",
    "    print(f\"{class_name:>24}: train={(train_labels == class_id).sum():4d} | test={(test_labels == class_id).sum():4d}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cd3f794d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Peek at a few examples\n",
    "for i in range(3):\n",
    "    print(\"=\" * 100)\n",
    "    print(\"Label:\", label_names[train_labels[i]])\n",
    "    print(train_texts[i][:700].replace(\"\\n\", \" \"))\n",
    "    print()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "62d5f7ff",
   "metadata": {},
   "source": [
    "### Slide warm-up — Why move beyond RNNs?\n",
    "\n",
    "Before you continue, answer these based on the slides:\n",
    "\n",
    "1. Why can long sequences be slow for RNNs?\n",
    "2. Why are vanishing and exploding gradients a problem?\n",
    "3. Why can direct token-to-token attention help with long-range dependencies?\n",
    "4. In a realistic text-routing system, why would these points matter when messages become longer or more complex?\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26a8d52d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Raw text preview:\")\n",
    "print(train_texts[0][:600].replace(\"\\n\", \" \"))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ce402f15",
   "metadata": {},
   "source": [
    "## Part A.2 — Tokenization and vocabulary\n",
    "\n",
    "The slides move from tokens to **input IDs** and then to **input embeddings**.\n",
    "To keep that path transparent, we use a small regex tokenizer and a compact vocabulary.\n",
    "\n",
    "Special tokens used here:\n",
    "- `[PAD]` for padding\n",
    "- `[UNK]` for unknown words\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d4777ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "TOKEN_RE = re.compile(r\"[A-Za-z']+\")\n",
    "\n",
    "PAD_TOKEN = \"[PAD]\"\n",
    "UNK_TOKEN = \"[UNK]\"\n",
    "\n",
    "PAD_IDX = 0\n",
    "UNK_IDX = 1\n",
    "\n",
    "def tokenize(text):\n",
    "    return TOKEN_RE.findall(text.lower())\n",
    "\n",
    "# Build a compact vocabulary sized for a short T4 run\n",
    "MAX_VOCAB = 8000\n",
    "\n",
    "counter = Counter()\n",
    "for text in train_texts:\n",
    "    counter.update(tokenize(text))\n",
    "\n",
    "most_common_tokens = [tok for tok, _ in counter.most_common(MAX_VOCAB - 2)]\n",
    "itos = [PAD_TOKEN, UNK_TOKEN] + most_common_tokens\n",
    "stoi = {tok: idx for idx, tok in enumerate(itos)}\n",
    "\n",
    "print(\"Vocabulary size:\", len(itos))\n",
    "print(\"Top 20 tokens:\", most_common_tokens[:20])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb901fa4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# MAX_LEN is defined in the configuration cell above\n",
    "\n",
    "def encode_text(text, stoi, max_len=MAX_LEN):\n",
    "    tokens = tokenize(text)\n",
    "    ids = [stoi.get(tok, UNK_IDX) for tok in tokens[:max_len]]\n",
    "    mask = [1] * len(ids)\n",
    "\n",
    "    if len(ids) < max_len:\n",
    "        pad_len = max_len - len(ids)\n",
    "        ids += [PAD_IDX] * pad_len\n",
    "        mask += [0] * pad_len\n",
    "\n",
    "    return ids, mask\n",
    "\n",
    "sample_ids, sample_mask = encode_text(train_texts[0], stoi, max_len=MAX_LEN)\n",
    "print(\"Encoded length:\", len(sample_ids))\n",
    "print(\"Visible tokens:\", sum(sample_mask))\n",
    "print(\"First 20 ids:\", sample_ids[:20])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "65afe162",
   "metadata": {},
   "outputs": [],
   "source": [
    "class NewsDataset(Dataset):\n",
    "    def __init__(self, texts, labels, stoi, max_len):\n",
    "        self.texts = list(texts)\n",
    "        self.labels = torch.tensor(labels, dtype=torch.long)\n",
    "\n",
    "        encoded = [encode_text(text, stoi, max_len) for text in self.texts]\n",
    "        self.input_ids = torch.tensor([x[0] for x in encoded], dtype=torch.long)\n",
    "        self.attn_mask = torch.tensor([x[1] for x in encoded], dtype=torch.bool)\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.texts)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        return self.input_ids[idx], self.attn_mask[idx], self.labels[idx]\n",
    "\n",
    "train_ds = NewsDataset(train_texts, train_labels, stoi, MAX_LEN)\n",
    "test_ds = NewsDataset(test_texts, test_labels, stoi, MAX_LEN)\n",
    "\n",
    "loader_kwargs = dict(\n",
    "    batch_size=BATCH_SIZE,\n",
    "    num_workers=NUM_WORKERS,\n",
    "    pin_memory=PIN_MEMORY,\n",
    "    persistent_workers=NUM_WORKERS > 0,\n",
    ")\n",
    "\n",
    "train_loader = DataLoader(train_ds, shuffle=True, **loader_kwargs)\n",
    "test_loader = DataLoader(test_ds, shuffle=False, **loader_kwargs)\n",
    "\n",
    "print(\"Train batches:\", len(train_loader))\n",
    "print(\"Test batches:\", len(test_loader))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f2a09640",
   "metadata": {},
   "source": [
    "### Exercise A — Code: decode IDs and inspect embeddings\n",
    "\n",
    "Complete the next code cell.\n",
    "\n",
    "**Tasks**\n",
    "1. Decode the first `N_SHOW` visible input IDs back to token strings.\n",
    "2. Create a small embedding layer with output width `16`.\n",
    "3. Pass the selected IDs through the embedding layer.\n",
    "4. Print the decoded tokens and the embedding output shape.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "03d4e180",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solution: decode the first N visible IDs and inspect a demo embedding lookup\n",
    "N_SHOW = 12\n",
    "sample_input_ids, sample_attn_mask, _ = train_ds[0]\n",
    "visible_ids = sample_input_ids[sample_attn_mask][:N_SHOW]\n",
    "\n",
    "decoded_tokens = [itos[idx] for idx in visible_ids.tolist()]\n",
    "embedding_demo = nn.Embedding(num_embeddings=len(itos), embedding_dim=16)\n",
    "embed_out = embedding_demo(visible_ids.unsqueeze(0))\n",
    "\n",
    "print(\"Visible ids:\", visible_ids.tolist())\n",
    "print(\"Decoded tokens:\", decoded_tokens)\n",
    "print(\"Embedding output shape:\", tuple(embed_out.shape))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bfd64a84",
   "metadata": {},
   "source": [
    "## Part B — Positional encoding\n",
    "\n",
    "The slides emphasize that embeddings alone do not carry token order.\n",
    "So we add **positional encoding** to the token embeddings.\n",
    "\n",
    "Below, we implement the sinusoidal positional encoding from the slides and visualize it.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4d89919",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PositionalEncoding(nn.Module):\n",
    "    def __init__(self, d_model, max_len=512):\n",
    "        super().__init__()\n",
    "\n",
    "        pe = torch.zeros(max_len, d_model)\n",
    "        position = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)\n",
    "        div_term = torch.exp(\n",
    "            torch.arange(0, d_model, 2, dtype=torch.float32)\n",
    "            * (-math.log(10000.0) / d_model)\n",
    "        )\n",
    "\n",
    "        pe[:, 0::2] = torch.sin(position * div_term)\n",
    "        pe[:, 1::2] = torch.cos(position * div_term)\n",
    "        pe = pe.unsqueeze(0)  # (1, max_len, d_model)\n",
    "\n",
    "        self.register_buffer(\"pe\", pe)\n",
    "\n",
    "    def forward(self, x):\n",
    "        seq_len = x.size(1)\n",
    "        return x + self.pe[:, :seq_len]\n",
    "\n",
    "# Visualize positional encoding\n",
    "d_model_demo = 64\n",
    "pos_enc_demo = PositionalEncoding(d_model_demo, max_len=128)\n",
    "pe_matrix = pos_enc_demo.pe[0].cpu().numpy()\n",
    "\n",
    "plt.figure(figsize=(10, 4))\n",
    "plt.imshow(pe_matrix.T, aspect=\"auto\", cmap=\"coolwarm\")\n",
    "plt.colorbar()\n",
    "plt.xlabel(\"Position\")\n",
    "plt.ylabel(\"Embedding dimension\")\n",
    "plt.title(\"Sinusoidal positional encoding\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "694a1b88",
   "metadata": {},
   "source": [
    "### Interpretation prompt\n",
    "\n",
    "- What repeated structure do you see in the positional encoding plot?\n",
    "- Why do sine and cosine give a smooth positional pattern?\n",
    "- Why can the same positional encoding table be reused across many sentences?\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5b6842a",
   "metadata": {},
   "outputs": [],
   "source": [
    "small_pe = PositionalEncoding(d_model=16, max_len=32).pe[0].detach().cpu().numpy()\n",
    "\n",
    "positions_to_compare = [0, 1, 2, 10]\n",
    "for pos in positions_to_compare:\n",
    "    print(f\"Position {pos:>2} | first 8 dims:\", np.round(small_pe[pos, :8], 4))\n",
    "\n",
    "def cosine_sim(a, b):\n",
    "    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))\n",
    "\n",
    "print()\n",
    "print(\"cos(pos0, pos1) =\", round(cosine_sim(small_pe[0], small_pe[1]), 4))\n",
    "print(\"cos(pos0, pos10) =\", round(cosine_sim(small_pe[0], small_pe[10]), 4))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e71c237f",
   "metadata": {},
   "source": [
    "### Exercise B — Code: compare positional vectors numerically\n",
    "\n",
    "Complete the next code cell.\n",
    "\n",
    "**Tasks**\n",
    "1. Compute cosine similarity between position `0` and positions `1`, `2`, and `10`.\n",
    "2. Find which position in `1..15` is most similar to position `0`.\n",
    "3. Rerun after changing the comparison range and inspect how similarity changes.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d4221d1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solution: compare positional encodings numerically\n",
    "base_pos = 0\n",
    "compare_positions = [1, 2, 10]\n",
    "\n",
    "sims = {}\n",
    "for pos in compare_positions:\n",
    "    sims[pos] = cosine_sim(small_pe[base_pos], small_pe[pos])\n",
    "\n",
    "print(\"Cosine similarities:\", sims)\n",
    "\n",
    "nearest_pos = max(range(1, 16), key=lambda p: cosine_sim(small_pe[base_pos], small_pe[p]))\n",
    "print(\"Nearest position to 0 in [1, 15]:\", nearest_pos)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aff26e19",
   "metadata": {},
   "source": [
    "## Part B.2 — Build one encoder block from scratch\n",
    "\n",
    "This section matches the components highlighted in the slides:\n",
    "\n",
    "- multi-head self-attention,\n",
    "- feed-forward network,\n",
    "- residual connections,\n",
    "- layer normalization.\n",
    "\n",
    "The model is intentionally small so the lab fits on a free T4.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "26ef0390",
   "metadata": {},
   "outputs": [],
   "source": [
    "class MultiHeadSelfAttention(nn.Module):\n",
    "    def __init__(self, d_model, num_heads, dropout=0.1):\n",
    "        super().__init__()\n",
    "        assert d_model % num_heads == 0, \"d_model must be divisible by num_heads\"\n",
    "\n",
    "        self.d_model = d_model\n",
    "        self.num_heads = num_heads\n",
    "        self.head_dim = d_model // num_heads\n",
    "\n",
    "        self.q_proj = nn.Linear(d_model, d_model)\n",
    "        self.k_proj = nn.Linear(d_model, d_model)\n",
    "        self.v_proj = nn.Linear(d_model, d_model)\n",
    "        self.out_proj = nn.Linear(d_model, d_model)\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "\n",
    "    def forward(self, x, attn_mask=None, causal=False, return_attn=False):\n",
    "        B, T, C = x.shape\n",
    "\n",
    "        q = self.q_proj(x).view(B, T, self.num_heads, self.head_dim).transpose(1, 2)\n",
    "        k = self.k_proj(x).view(B, T, self.num_heads, self.head_dim).transpose(1, 2)\n",
    "        v = self.v_proj(x).view(B, T, self.num_heads, self.head_dim).transpose(1, 2)\n",
    "\n",
    "        scores = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)\n",
    "\n",
    "        if attn_mask is not None:\n",
    "            key_mask = attn_mask[:, None, None, :]\n",
    "            scores = scores.masked_fill(~key_mask, float(\"-inf\"))\n",
    "\n",
    "        if causal:\n",
    "            causal_mask = torch.triu(\n",
    "                torch.ones(T, T, device=x.device, dtype=torch.bool), diagonal=1\n",
    "            )\n",
    "            scores = scores.masked_fill(causal_mask[None, None, :, :], float(\"-inf\"))\n",
    "\n",
    "        attn = torch.softmax(scores, dim=-1)\n",
    "\n",
    "        if attn_mask is not None:\n",
    "            query_mask = attn_mask[:, None, :, None]\n",
    "            attn = attn * query_mask\n",
    "            denom = attn.sum(dim=-1, keepdim=True).clamp_min(1e-9)\n",
    "            attn = attn / denom\n",
    "\n",
    "        attn = self.dropout(attn)\n",
    "        out = attn @ v\n",
    "        out = out.transpose(1, 2).contiguous().view(B, T, C)\n",
    "        out = self.out_proj(out)\n",
    "\n",
    "        if return_attn:\n",
    "            return out, attn\n",
    "        return out\n",
    "\n",
    "\n",
    "class TransformerEncoderBlock(nn.Module):\n",
    "    def __init__(self, d_model, num_heads, ff_dim, dropout=0.1):\n",
    "        super().__init__()\n",
    "        self.norm1 = nn.LayerNorm(d_model)\n",
    "        self.norm2 = nn.LayerNorm(d_model)\n",
    "\n",
    "        self.attn = MultiHeadSelfAttention(d_model, num_heads, dropout=dropout)\n",
    "\n",
    "        self.ff = nn.Sequential(\n",
    "            nn.Linear(d_model, ff_dim),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(dropout),\n",
    "            nn.Linear(ff_dim, d_model),\n",
    "        )\n",
    "\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "\n",
    "    def forward(self, x, attn_mask=None, return_attn=False):\n",
    "        if return_attn:\n",
    "            attn_out, attn_weights = self.attn(\n",
    "                self.norm1(x), attn_mask=attn_mask, causal=False, return_attn=True\n",
    "            )\n",
    "            x = x + self.dropout(attn_out)\n",
    "            x = x + self.dropout(self.ff(self.norm2(x)))\n",
    "            return x, attn_weights\n",
    "        else:\n",
    "            x = x + self.dropout(self.attn(self.norm1(x), attn_mask=attn_mask))\n",
    "            x = x + self.dropout(self.ff(self.norm2(x)))\n",
    "            return x\n",
    "\n",
    "\n",
    "class TinyTransformerEncoderModel(nn.Module):\n",
    "    def __init__(\n",
    "        self,\n",
    "        vocab_size,\n",
    "        num_classes,\n",
    "        d_model=128,\n",
    "        num_heads=4,\n",
    "        ff_dim=256,\n",
    "        num_layers=2,\n",
    "        dropout=0.1,\n",
    "        max_len=128,\n",
    "    ):\n",
    "        super().__init__()\n",
    "        self.embedding = nn.Embedding(vocab_size, d_model, padding_idx=PAD_IDX)\n",
    "        self.pos_encoding = PositionalEncoding(d_model, max_len=max_len)\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "\n",
    "        self.layers = nn.ModuleList(\n",
    "            [\n",
    "                TransformerEncoderBlock(d_model, num_heads, ff_dim, dropout=dropout)\n",
    "                for _ in range(num_layers)\n",
    "            ]\n",
    "        )\n",
    "\n",
    "        self.final_norm = nn.LayerNorm(d_model)\n",
    "        self.output_layer = nn.Linear(d_model, num_classes)\n",
    "        self.d_model = d_model\n",
    "\n",
    "    def forward(self, input_ids, attn_mask=None, return_attn=False):\n",
    "        x = self.embedding(input_ids) * math.sqrt(self.d_model)\n",
    "        x = self.pos_encoding(x)\n",
    "        x = self.dropout(x)\n",
    "\n",
    "        attn_maps = []\n",
    "        for layer in self.layers:\n",
    "            if return_attn:\n",
    "                x, attn = layer(x, attn_mask=attn_mask, return_attn=True)\n",
    "                attn_maps.append(attn)\n",
    "            else:\n",
    "                x = layer(x, attn_mask=attn_mask)\n",
    "\n",
    "        x = self.final_norm(x)\n",
    "\n",
    "        if attn_mask is not None:\n",
    "            mask = attn_mask.unsqueeze(-1).float()\n",
    "            pooled = (x * mask).sum(dim=1) / mask.sum(dim=1).clamp_min(1.0)\n",
    "        else:\n",
    "            pooled = x.mean(dim=1)\n",
    "\n",
    "        logits = self.output_layer(pooled)\n",
    "\n",
    "        if return_attn:\n",
    "            return logits, attn_maps\n",
    "        return logits\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8308cb10",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Instantiate a small model\n",
    "model = TinyTransformerEncoderModel(\n",
    "    vocab_size=len(itos),\n",
    "    num_classes=len(label_names),\n",
    "    d_model=128,\n",
    "    num_heads=4,\n",
    "    ff_dim=256,\n",
    "    num_layers=2,\n",
    "    dropout=0.1,\n",
    "    max_len=MAX_LEN,\n",
    ").to(device)\n",
    "\n",
    "# Shape check\n",
    "batch = next(iter(train_loader))\n",
    "input_ids, attn_mask, labels = [x.to(device) for x in batch]\n",
    "logits, attn_maps = model(input_ids, attn_mask=attn_mask, return_attn=True)\n",
    "\n",
    "print(\"Input shape:\", input_ids.shape)\n",
    "print(\"Logits shape:\", logits.shape)\n",
    "print(\"Number of attention map tensors:\", len(attn_maps))\n",
    "print(\"Attention map shape for one layer:\", attn_maps[0].shape)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d9c19c1e",
   "metadata": {},
   "source": [
    "### Checkpoint\n",
    "\n",
    "At this stage, verify that:\n",
    "\n",
    "- the encoder keeps the sequence structure,\n",
    "- the attention maps have shape `(batch, heads, seq_len, seq_len)`,\n",
    "- the feed-forward block maps each token representation back to `d_model`,\n",
    "- and layer normalization appears inside each block.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "56f53761",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"d_model:\", model.d_model)\n",
    "print(\"number of heads:\", model.layers[0].attn.num_heads)\n",
    "print(\"head dimension d_k:\", model.layers[0].attn.head_dim)\n",
    "print()\n",
    "print(\"Q projection weight shape:\", tuple(model.layers[0].attn.q_proj.weight.shape))\n",
    "print(\"K projection weight shape:\", tuple(model.layers[0].attn.k_proj.weight.shape))\n",
    "print(\"V projection weight shape:\", tuple(model.layers[0].attn.v_proj.weight.shape))\n",
    "print(\"Feed-forward first layer shape:\", tuple(model.layers[0].ff[0].weight.shape))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bec5be6a",
   "metadata": {},
   "source": [
    "### Exercise C — Code: inspect one encoder block\n",
    "\n",
    "Complete the next code cell.\n",
    "\n",
    "**Tasks**\n",
    "1. Verify numerically that `head_dim = d_model // num_heads`.\n",
    "2. Run the attention module on a dummy batch and print its output shape.\n",
    "3. Run the full encoder block on the same dummy batch and print its output shape.\n",
    "4. Print the layer-normalization modules and the feed-forward module used inside the block.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f0feae5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solution: verify encoder-block dimensions and inspect the main submodules\n",
    "attn_module = model.layers[0].attn\n",
    "\n",
    "print(\"d_model:\", model.d_model)\n",
    "print(\"num_heads:\", attn_module.num_heads)\n",
    "print(\"head_dim:\", attn_module.head_dim)\n",
    "print(\"d_model // num_heads:\", model.d_model // attn_module.num_heads)\n",
    "print(\"Matches:\", attn_module.head_dim == model.d_model // attn_module.num_heads)\n",
    "\n",
    "dummy = torch.randn(2, 8, model.d_model, device=device)\n",
    "dummy_mask = torch.ones(2, 8, dtype=torch.bool, device=device)\n",
    "\n",
    "with torch.no_grad():\n",
    "    attn_out, attn_weights = attn_module(dummy, attn_mask=dummy_mask, return_attn=True)\n",
    "    block_out, _ = model.layers[0](dummy, attn_mask=dummy_mask, return_attn=True)\n",
    "\n",
    "print(\"Attention output shape:\", tuple(attn_out.shape))\n",
    "print(\"Attention map shape:\", tuple(attn_weights.shape))\n",
    "print(\"Block output shape:\", tuple(block_out.shape))\n",
    "print(\"LayerNorm modules:\", model.layers[0].norm1.__class__.__name__, model.layers[0].norm2.__class__.__name__)\n",
    "print(\"Feed-forward module:\", model.layers[0].ff)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0b312ad4",
   "metadata": {},
   "source": [
    "## Part C — Train the model\n",
    "\n",
    "This compact loop is only a practical way to make the slide components learn something on a small T4-friendly corpus.\n",
    "\n",
    "Conceptually, keep the slides in mind:\n",
    "- training uses a loss over known targets,\n",
    "- inference uses the trained model after learning,\n",
    "- masking matters when future tokens must be hidden.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2edd18a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "criterion = nn.CrossEntropyLoss()\n",
    "optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)\n",
    "scaler = torch.cuda.amp.GradScaler(enabled=AMP_ENABLED)\n",
    "\n",
    "def run_epoch(model, loader, optimizer=None):\n",
    "    is_train = optimizer is not None\n",
    "    model.train() if is_train else model.eval()\n",
    "\n",
    "    losses = []\n",
    "    all_preds = []\n",
    "    all_targets = []\n",
    "\n",
    "    for input_ids, attn_mask, labels in loader:\n",
    "        input_ids = input_ids.to(device, non_blocking=PIN_MEMORY)\n",
    "        attn_mask = attn_mask.to(device, non_blocking=PIN_MEMORY)\n",
    "        labels = labels.to(device, non_blocking=PIN_MEMORY)\n",
    "\n",
    "        if is_train:\n",
    "            optimizer.zero_grad(set_to_none=True)\n",
    "\n",
    "        with torch.set_grad_enabled(is_train):\n",
    "            amp_context = (\n",
    "                torch.autocast(device_type=\"cuda\", dtype=torch.float16)\n",
    "                if AMP_ENABLED\n",
    "                else nullcontext()\n",
    "            )\n",
    "\n",
    "            with amp_context:\n",
    "                logits = model(input_ids, attn_mask=attn_mask)\n",
    "                loss = criterion(logits, labels)\n",
    "\n",
    "            if is_train:\n",
    "                scaler.scale(loss).backward()\n",
    "                scaler.unscale_(optimizer)\n",
    "                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
    "                scaler.step(optimizer)\n",
    "                scaler.update()\n",
    "\n",
    "        losses.append(loss.item())\n",
    "        preds = logits.argmax(dim=1)\n",
    "\n",
    "        all_preds.extend(preds.detach().cpu().numpy())\n",
    "        all_targets.extend(labels.detach().cpu().numpy())\n",
    "\n",
    "    avg_loss = float(np.mean(losses))\n",
    "    acc = accuracy_score(all_targets, all_preds)\n",
    "    return avg_loss, acc\n",
    "\n",
    "history = {\"train_loss\": [], \"train_acc\": [], \"test_loss\": [], \"test_acc\": []}\n",
    "\n",
    "for epoch in range(1, EPOCHS + 1):\n",
    "    train_loss, train_acc = run_epoch(model, train_loader, optimizer=optimizer)\n",
    "    test_loss, test_acc = run_epoch(model, test_loader, optimizer=None)\n",
    "\n",
    "    history[\"train_loss\"].append(train_loss)\n",
    "    history[\"train_acc\"].append(train_acc)\n",
    "    history[\"test_loss\"].append(test_loss)\n",
    "    history[\"test_acc\"].append(test_acc)\n",
    "\n",
    "    print(\n",
    "        f\"Epoch {epoch:02d} | \"\n",
    "        f\"train_loss={train_loss:.4f} | train_acc={train_acc:.4f} | \"\n",
    "        f\"test_loss={test_loss:.4f} | test_acc={test_acc:.4f}\"\n",
    "    )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1238f243",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot learning curves\n",
    "epochs = np.arange(1, EPOCHS + 1)\n",
    "\n",
    "plt.figure(figsize=(12, 4))\n",
    "\n",
    "plt.subplot(1, 2, 1)\n",
    "plt.plot(epochs, history[\"train_loss\"], marker=\"o\", label=\"Train loss\")\n",
    "plt.plot(epochs, history[\"test_loss\"], marker=\"o\", label=\"Test loss\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Loss\")\n",
    "plt.title(\"Loss curves\")\n",
    "plt.legend()\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "plt.plot(epochs, history[\"train_acc\"], marker=\"o\", label=\"Train accuracy\")\n",
    "plt.plot(epochs, history[\"test_acc\"], marker=\"o\", label=\"Test accuracy\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Accuracy\")\n",
    "plt.title(\"Accuracy curves\")\n",
    "plt.legend()\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da08d5dd",
   "metadata": {},
   "source": [
    "### Interpretation prompt\n",
    "\n",
    "- In the slides, why can training use all target information at once after shifting right?\n",
    "- Why does inference become step-by-step?\n",
    "- Why is masking essential in a decoder but not in an encoder self-attention block?\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "474dc2c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "industry_review = {\n",
    "    \"business_proxy\": \"Text routing / queue assignment\",\n",
    "    \"change_tested\": \"TODO\",\n",
    "    \"runtime_observation\": \"TODO\",\n",
    "    \"quality_observation\": \"TODO\",\n",
    "    \"attention_observation\": \"TODO\",\n",
    "    \"engineering_takeaway\": \"TODO\",\n",
    "}\n",
    "industry_review\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "89576fb8",
   "metadata": {},
   "source": [
    "### Exercise D — Code: shift-right training setup and greedy decoding\n",
    "\n",
    "Complete the next code cell.\n",
    "\n",
    "**Tasks**\n",
    "1. Build a shifted-right decoder input from a toy target sequence.\n",
    "2. Take greedy token choices from a toy logits tensor with `argmax`.\n",
    "3. Print a causal mask for the same sequence length.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9605bcd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solution: show the shift-right training setup and one greedy decoding step\n",
    "toy_target = torch.tensor([5, 9, 4, 2, 7])\n",
    "BOS_IDX = 1\n",
    "\n",
    "decoder_input = torch.empty_like(toy_target)\n",
    "decoder_input[0] = BOS_IDX\n",
    "decoder_input[1:] = toy_target[:-1]\n",
    "\n",
    "print(\"Target sequence:\", toy_target.tolist())\n",
    "print(\"Shifted decoder input:\", decoder_input.tolist())\n",
    "\n",
    "toy_logits = torch.tensor([\n",
    "    [0.2, 1.1, -0.7, 0.5],\n",
    "    [0.4, 0.1, 1.6, -0.3],\n",
    "    [0.3, 2.4, 0.1, -1.0],\n",
    "])\n",
    "\n",
    "greedy_tokens = toy_logits.argmax(dim=-1)\n",
    "print(\"Greedy token choices:\", greedy_tokens.tolist())\n",
    "\n",
    "def causal_mask_local(seq_len):\n",
    "    return torch.triu(torch.ones(seq_len, seq_len, dtype=torch.bool), diagonal=1)\n",
    "\n",
    "print(\"Causal mask:\\n\", causal_mask_local(len(toy_target)).int())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8da9a8c6",
   "metadata": {},
   "source": [
    "## Part C.2 — Final sanity check\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38272ec5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_loader(model, loader):\n",
    "    model.eval()\n",
    "    preds = []\n",
    "    targets = []\n",
    "\n",
    "    with torch.no_grad():\n",
    "        for input_ids, attn_mask, labels in loader:\n",
    "            input_ids = input_ids.to(device)\n",
    "            attn_mask = attn_mask.to(device)\n",
    "\n",
    "            logits = model(input_ids, attn_mask=attn_mask)\n",
    "            batch_preds = logits.argmax(dim=1).cpu().numpy()\n",
    "\n",
    "            preds.extend(batch_preds)\n",
    "            targets.extend(labels.numpy())\n",
    "\n",
    "    return np.array(preds), np.array(targets)\n",
    "\n",
    "test_preds, test_targets = predict_loader(model, test_loader)\n",
    "\n",
    "print(\"Held-out accuracy (sanity check only):\", accuracy_score(test_targets, test_preds))\n",
    "print(\"We only need the model to learn enough structure for attention inspection.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d9b2f441",
   "metadata": {},
   "source": [
    "The held-out score is only a quick sanity check.  \n",
    "The real focus of the lab is the attention structure, the role of positional encoding, and the contrast between full attention and masked attention.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bebe33bf",
   "metadata": {},
   "source": [
    "## Part D — Attention visualization\n",
    "\n",
    "Now we inspect the learned attention maps.\n",
    "\n",
    "We will:\n",
    "1. select a correctly predicted example,\n",
    "2. recover the visible tokens,\n",
    "3. plot a heatmap for one layer and head,\n",
    "4. inspect the attention distribution for one chosen query token,\n",
    "5. compare heads.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4a2fbf9",
   "metadata": {},
   "outputs": [],
   "source": [
    "def ids_to_tokens(input_ids, attn_mask, itos):\n",
    "    visible_len = int(attn_mask.sum().item())\n",
    "    ids = input_ids[:visible_len].tolist()\n",
    "    return [itos[idx] for idx in ids]\n",
    "\n",
    "def get_correct_example(model, dataset):\n",
    "    model.eval()\n",
    "    for idx in range(len(dataset)):\n",
    "        input_ids, attn_mask, label = dataset[idx]\n",
    "        with torch.no_grad():\n",
    "            logits, attn_maps = model(\n",
    "                input_ids.unsqueeze(0).to(device),\n",
    "                attn_mask=attn_mask.unsqueeze(0).to(device),\n",
    "                return_attn=True,\n",
    "            )\n",
    "        pred = logits.argmax(dim=1).item()\n",
    "        if pred == int(label):\n",
    "            return idx, input_ids, attn_mask, attn_maps\n",
    "    raise RuntimeError(\"No correctly predicted example found. Try training for more epochs.\")\n",
    "\n",
    "example_idx, ex_ids, ex_mask, ex_attn_maps = get_correct_example(model, test_ds)\n",
    "tokens = ids_to_tokens(ex_ids, ex_mask, itos)\n",
    "\n",
    "print(\"Selected test index:\", example_idx)\n",
    "print()\n",
    "print(\"Original text snippet:\")\n",
    "print(test_ds.texts[example_idx][:900].replace(\"\\n\", \" \"))\n",
    "print()\n",
    "print(\"Visible tokens:\")\n",
    "print(tokens[:40])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec7de660",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Choose which layer and head to inspect\n",
    "LAYER_TO_PLOT = 0\n",
    "HEAD_TO_PLOT = 0\n",
    "MAX_TOKENS_TO_SHOW = min(20, len(tokens))\n",
    "\n",
    "attn = ex_attn_maps[LAYER_TO_PLOT][0, HEAD_TO_PLOT].detach().cpu().numpy()\n",
    "attn = attn[:MAX_TOKENS_TO_SHOW, :MAX_TOKENS_TO_SHOW]\n",
    "tok_view = tokens[:MAX_TOKENS_TO_SHOW]\n",
    "\n",
    "plt.figure(figsize=(9, 7))\n",
    "plt.imshow(attn, cmap=\"magma\")\n",
    "plt.colorbar()\n",
    "plt.xticks(range(MAX_TOKENS_TO_SHOW), tok_view, rotation=60, ha=\"right\")\n",
    "plt.yticks(range(MAX_TOKENS_TO_SHOW), tok_view)\n",
    "plt.xlabel(\"Key tokens\")\n",
    "plt.ylabel(\"Query tokens\")\n",
    "plt.title(f\"Attention heatmap | layer={LAYER_TO_PLOT}, head={HEAD_TO_PLOT}\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "212cf3d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualize attention FROM one chosen query token to all visible tokens\n",
    "LAYER_TO_PLOT = 0\n",
    "HEAD_TO_PLOT = 0\n",
    "MAX_TOKENS_TO_SHOW = min(25, len(tokens))\n",
    "QUERY_POS = min(3, MAX_TOKENS_TO_SHOW - 1)\n",
    "\n",
    "attn = ex_attn_maps[LAYER_TO_PLOT][0, HEAD_TO_PLOT].detach().cpu().numpy()\n",
    "query_to_all = attn[QUERY_POS, :MAX_TOKENS_TO_SHOW]\n",
    "tok_view = tokens[:MAX_TOKENS_TO_SHOW]\n",
    "query_token = tok_view[QUERY_POS]\n",
    "\n",
    "plt.figure(figsize=(10, 4))\n",
    "plt.bar(range(len(tok_view)), query_to_all)\n",
    "plt.xticks(range(len(tok_view)), tok_view, rotation=60, ha=\"right\")\n",
    "plt.ylabel(\"Attention weight\")\n",
    "plt.title(f\"Attention from query token '{query_token}' | layer={LAYER_TO_PLOT}, head={HEAD_TO_PLOT}\")\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5877c0df",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Compare average attention across heads in a layer\n",
    "LAYER_TO_PLOT = 0\n",
    "MAX_TOKENS_TO_SHOW = min(20, len(tokens))\n",
    "\n",
    "layer_attn = ex_attn_maps[LAYER_TO_PLOT][0].detach().cpu().numpy()  # (H, T, T)\n",
    "avg_attn = layer_attn.mean(axis=0)[:MAX_TOKENS_TO_SHOW, :MAX_TOKENS_TO_SHOW]\n",
    "tok_view = tokens[:MAX_TOKENS_TO_SHOW]\n",
    "\n",
    "plt.figure(figsize=(9, 7))\n",
    "plt.imshow(avg_attn, cmap=\"viridis\")\n",
    "plt.colorbar()\n",
    "plt.xticks(range(MAX_TOKENS_TO_SHOW), tok_view, rotation=60, ha=\"right\")\n",
    "plt.yticks(range(MAX_TOKENS_TO_SHOW), tok_view)\n",
    "plt.xlabel(\"Key tokens\")\n",
    "plt.ylabel(\"Query tokens\")\n",
    "plt.title(f\"Average attention across heads | layer={LAYER_TO_PLOT}\")\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41c03ee9",
   "metadata": {},
   "source": [
    "### Attention interpretation prompts\n",
    "\n",
    "- Which tokens receive the most attention from the chosen query token?\n",
    "- Do different heads appear to focus on different patterns?\n",
    "- Do you see mostly local interactions, broader interactions, or a mix of both?\n",
    "- How does this connect to the slide claim that attention lets words relate to each other?\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2787e0a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "def top_tokens_for_each_head(attn_maps, tokens, query_pos, layer=0, top_k=6):\n",
    "    layer_attn = attn_maps[layer][0].detach().cpu().numpy()\n",
    "    visible_len = len(tokens)\n",
    "    out = []\n",
    "\n",
    "    for head in range(layer_attn.shape[0]):\n",
    "        scores = layer_attn[head, query_pos, :visible_len]\n",
    "        ranked = np.argsort(scores)[::-1][:top_k]\n",
    "        out.append((head, [(tokens[i], float(scores[i])) for i in ranked]))\n",
    "    return out\n",
    "\n",
    "query_pos = min(3, len(tokens) - 1)\n",
    "head_summaries = top_tokens_for_each_head(ex_attn_maps, tokens, query_pos=query_pos, layer=0, top_k=6)\n",
    "print(\"Query token:\", tokens[query_pos])\n",
    "print()\n",
    "for head, items in head_summaries:\n",
    "    print(f\"Head {head}\")\n",
    "    for tok, score in items:\n",
    "        print(f\"  {tok:>15} : {score:.4f}\")\n",
    "    print()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ab7901a6",
   "metadata": {},
   "source": [
    "### Exercise E — Code: compare heads quantitatively\n",
    "\n",
    "Complete the next code cell.\n",
    "\n",
    "**Tasks**\n",
    "1. For one query token, record the top-ranked attended token from each head.\n",
    "2. Compute the top-4 attention mass for each head.\n",
    "3. Change `query_pos` and rerun to compare how the heads behave for a different query token.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49d701e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solution: compare heads quantitatively for one query token\n",
    "query_pos = min(3, len(tokens) - 1)\n",
    "head_summaries = top_tokens_for_each_head(ex_attn_maps, tokens, query_pos=query_pos, layer=0, top_k=4)\n",
    "\n",
    "top1_by_head = {}\n",
    "for head, items in head_summaries:\n",
    "    top1_by_head[head] = items[0][0]\n",
    "\n",
    "print(\"Query token:\", tokens[query_pos])\n",
    "print(\"Top-1 attended token by head:\", top1_by_head)\n",
    "\n",
    "layer_attn = ex_attn_maps[0][0].detach().cpu().numpy()\n",
    "for head in range(layer_attn.shape[0]):\n",
    "    scores = np.sort(layer_attn[head, query_pos, :len(tokens)])[::-1]\n",
    "    print(f\"Head {head} top-4 mass:\", round(float(scores[:4].sum()), 4))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "813396fa",
   "metadata": {},
   "source": [
    "## Part D.2 — Inspect attention on your own sentence\n",
    "\n",
    "You can also feed a short custom sentence and inspect its attention pattern.\n",
    "This section is only for attention inspection, not for introducing any new concepts beyond the slides.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "501cd9f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "custom_text = \"The shuttle mission launched into orbit with a new satellite and crew.\"\n",
    "custom_ids, custom_mask = encode_text(custom_text, stoi, max_len=MAX_LEN)\n",
    "\n",
    "custom_ids_t = torch.tensor(custom_ids, dtype=torch.long).unsqueeze(0).to(device)\n",
    "custom_mask_t = torch.tensor(custom_mask, dtype=torch.bool).unsqueeze(0).to(device)\n",
    "\n",
    "with torch.no_grad():\n",
    "    _, custom_attn_maps = model(custom_ids_t, attn_mask=custom_mask_t, return_attn=True)\n",
    "\n",
    "custom_tokens = [itos[idx] for idx in custom_ids[: sum(custom_mask)]]\n",
    "\n",
    "print(\"Custom text:\", custom_text)\n",
    "print(\"Tokens:\", custom_tokens)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "87c1d018",
   "metadata": {},
   "outputs": [],
   "source": [
    "LAYER_TO_PLOT = 0\n",
    "HEAD_TO_PLOT = 0\n",
    "MAX_TOKENS_TO_SHOW = min(20, len(custom_tokens))\n",
    "QUERY_POS = min(2, MAX_TOKENS_TO_SHOW - 1)\n",
    "\n",
    "attn = custom_attn_maps[LAYER_TO_PLOT][0, HEAD_TO_PLOT].detach().cpu().numpy()\n",
    "query_to_all = attn[QUERY_POS, :MAX_TOKENS_TO_SHOW]\n",
    "tok_view = custom_tokens[:MAX_TOKENS_TO_SHOW]\n",
    "query_token = tok_view[QUERY_POS]\n",
    "\n",
    "plt.figure(figsize=(10, 4))\n",
    "plt.bar(range(len(tok_view)), query_to_all)\n",
    "plt.xticks(range(len(tok_view)), tok_view, rotation=60, ha=\"right\")\n",
    "plt.ylabel(\"Attention weight\")\n",
    "plt.title(f\"Custom sentence attention from '{query_token}' | layer={LAYER_TO_PLOT}, head={HEAD_TO_PLOT}\")\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1616080d",
   "metadata": {},
   "source": [
    "## Part E — Causal masking visualization\n",
    "\n",
    "So far we have used full encoder self-attention.\n",
    "\n",
    "The decoder slide introduces **masked multi-head attention**, where a token must not look ahead to future positions.\n",
    "The next cell shows the upper-triangular causal mask used for that purpose.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa5a2e00",
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_causal_mask(seq_len):\n",
    "    # True = masked position\n",
    "    return torch.triu(torch.ones(seq_len, seq_len, dtype=torch.bool), diagonal=1)\n",
    "\n",
    "seq_len = 12\n",
    "causal_mask = make_causal_mask(seq_len).numpy()\n",
    "\n",
    "plt.figure(figsize=(6, 5))\n",
    "plt.imshow(causal_mask, cmap=\"gray_r\")\n",
    "plt.xlabel(\"Key position\")\n",
    "plt.ylabel(\"Query position\")\n",
    "plt.title(\"Causal mask (white = blocked future position)\")\n",
    "plt.colorbar()\n",
    "plt.show()\n",
    "\n",
    "print(causal_mask.astype(int))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f1efc0df",
   "metadata": {},
   "source": [
    "### Why this matters\n",
    "\n",
    "In the encoder:\n",
    "- each visible token can attend to the other visible tokens.\n",
    "\n",
    "In the decoder:\n",
    "- position `t` must not use information from positions `t+1, t+2, ...`,\n",
    "- so entries above the diagonal are blocked before softmax.\n",
    "\n",
    "This is exactly the causal idea highlighted in the masking slides.\n",
    "In an industry setting, this matters whenever a system must generate or predict the next token without leaking future target information.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "724c906e",
   "metadata": {},
   "source": [
    "### Exercise F — Code: verify the causal mask numerically\n",
    "\n",
    "Complete the next code cell.\n",
    "\n",
    "**Tasks**\n",
    "1. Apply the causal mask to a toy score matrix.\n",
    "2. Convert the masked scores into probabilities with `softmax`.\n",
    "3. Confirm numerically that future positions receive zero probability mass.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7dd3a51e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solution: verify that masked future positions get zero probability\n",
    "toy_scores = torch.tensor([\n",
    "    [2.0, 1.0, 0.5, -0.3],\n",
    "    [1.5, 2.2, 0.7, 0.1],\n",
    "    [0.8, 1.1, 2.0, 0.9],\n",
    "    [0.2, 0.4, 1.0, 1.7],\n",
    "], dtype=torch.float32)\n",
    "\n",
    "mask = make_causal_mask(seq_len=toy_scores.size(0))\n",
    "masked_scores = toy_scores.masked_fill(mask, float(\"-inf\"))\n",
    "masked_probs = torch.softmax(masked_scores, dim=-1)\n",
    "\n",
    "print(\"Masked probabilities:\")\n",
    "print(masked_probs)\n",
    "print()\n",
    "\n",
    "for row in range(masked_probs.size(0)):\n",
    "    future_mass = float(masked_probs[row, row + 1 :].sum())\n",
    "    print(f\"Row {row} future-position probability mass:\", round(future_mass, 6))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "47f6819a",
   "metadata": {},
   "source": [
    "## Optional extra coding drills\n",
    "\n",
    "1. Change `HEAD_TO_PLOT` and rerun the attention heatmap.\n",
    "2. Change `QUERY_POS` in the attention bar chart and compare the top attended tokens.\n",
    "3. Replace `custom_text` with another short sentence and rerun the custom attention view.\n",
    "4. Change `seq_len` in the causal-mask cell and confirm how the blocked upper triangle changes.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f10cca01",
   "metadata": {},
   "source": [
    "## Wrap-up\n",
    "\n",
    "You have now worked through the same core ideas emphasized in the slides:\n",
    "\n",
    "- input embeddings,\n",
    "- positional encoding,\n",
    "- self-attention,\n",
    "- multi-head attention,\n",
    "- layer normalization,\n",
    "- feed-forward networks,\n",
    "- masking,\n",
    "- training and inference,\n",
    "- attention visualization.\n",
    "\n",
    "The notebook stays intentionally narrow so the discussion remains inside the lecture material, but the running example is framed like a small industry text-routing prototype.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "439c4996",
   "metadata": {},
   "source": [
    "## Reference note\n",
    "\n",
    "This version of the lab is intentionally restricted to the concepts explicitly discussed in the lecture slides.\n",
    "The small downloaded text corpus, the industry-style routing scenario, and the T4-friendly implementation details are only there to make those slide concepts runnable and interpretable in Colab.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.x"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
