{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d2852f88",
   "metadata": {},
   "source": [
    "# Week 4 Lab: Regularization & Optimizers in Deep Learning - SOLUTIONS\n",
    "\n",
    "**LDSCI6211 Machine Learning and Data Mining II**\n",
    "\n",
    "**Overview:**\n",
    "1. **Regularization Techniques**: L1, L2, and Elastic Net regularization\n",
    "2. **Early Stopping**: Preventing overfitting by monitoring validation loss\n",
    "3. **Dropout**: Randomly dropping neurons during training\n",
    "4. **Batch Normalization**: Stabilizing training with normalized activations\n",
    "5. **Optimization Algorithms**: SGD, Momentum, Adam, RMSProp\n",
    "\n",
    "**Learning Outcomes:**\n",
    "- Explain the bias-variance tradeoff and why overfitting occurs\n",
    "- Compare L1 (sparse) vs L2 (small weights) regularization\n",
    "- Apply early stopping and dropout techniques\n",
    "- Implement SGD with momentum and explain overshoot\n",
    "- Compare AdaGrad, RMSProp, and Adam optimizers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e2ca06b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import time\n",
    "\n",
    "from sklearn.datasets import load_wine, fetch_california_housing, make_classification\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import confusion_matrix, classification_report, mean_absolute_error\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader, TensorDataset\n",
    "\n",
    "# For reproducibility\n",
    "np.random.seed(42)\n",
    "torch.manual_seed(42)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed(42)\n",
    "\n",
    "# Set device\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"PyTorch version: {torch.__version__}\")\n",
    "print(f\"Using device: {device}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "overview_regularization",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 1: Understanding Overfitting\n",
    "\n",
    "Before we explore regularization techniques, let's understand the overfitting problem.\n",
    "\n",
    "**Key Concepts:**\n",
    "- **Overfitting**: Model performs well on training data but poorly on unseen data\n",
    "- **Bias-Variance Tradeoff**: Balance between underfitting (high bias) and overfitting (high variance)\n",
    "- **Regularization Goal**: Reduce variance with minimal increase in bias"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "create_overfit_data",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a synthetic dataset that's prone to overfitting\n",
    "# More features than useful, small sample size\n",
    "X_overfit, y_overfit = make_classification(\n",
    "    n_samples=200, \n",
    "    n_features=50, \n",
    "    n_informative=10,\n",
    "    n_redundant=20,\n",
    "    n_classes=2,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "# Split data\n",
    "X_train_of, X_test_of, y_train_of, y_test_of = train_test_split(\n",
    "    X_overfit, y_overfit, test_size=0.3, random_state=42\n",
    ")\n",
    "\n",
    "# Scale\n",
    "scaler_of = StandardScaler()\n",
    "X_train_of = scaler_of.fit_transform(X_train_of)\n",
    "X_test_of = scaler_of.transform(X_test_of)\n",
    "\n",
    "print(f\"Training samples: {X_train_of.shape[0]}, Features: {X_train_of.shape[1]}\")\n",
    "print(f\"Test samples: {X_test_of.shape[0]}\")\n",
    "print(\"\\nThis setup is prone to overfitting: many features, small sample size!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "baseline_model",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Baseline model WITHOUT any regularization\n",
    "class BaselineClassifier(nn.Module):\n",
    "    \"\"\"A model prone to overfitting - no regularization.\"\"\"\n",
    "    def __init__(self, input_size, hidden_size=128):\n",
    "        super(BaselineClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.fc2 = nn.Linear(hidden_size, hidden_size)\n",
    "        self.fc3 = nn.Linear(hidden_size, 64)\n",
    "        self.fc4 = nn.Linear(64, 2)\n",
    "        self.relu = nn.ReLU()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu(self.fc1(x))\n",
    "        x = self.relu(self.fc2(x))\n",
    "        x = self.relu(self.fc3(x))\n",
    "        return self.fc4(x)\n",
    "\n",
    "\n",
    "def train_model_simple(model, X_train, y_train, X_val, y_val, epochs=200, lr=0.01, device='cpu'):\n",
    "    \"\"\"Simple training function that tracks train and validation metrics.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=lr)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.LongTensor(y_val).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        # Training\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        loss = criterion(outputs, y_train_t)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        train_acc = (preds == y_train_t).float().mean().item()\n",
    "        \n",
    "        # Validation\n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_val_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['train_acc'].append(train_acc)\n",
    "        history['val_acc'].append(val_acc)\n",
    "    \n",
    "    return history\n",
    "\n",
    "\n",
    "# Train baseline model\n",
    "model_baseline = BaselineClassifier(X_train_of.shape[1])\n",
    "history_baseline = train_model_simple(\n",
    "    model_baseline, X_train_of, y_train_of, X_test_of, y_test_of, \n",
    "    epochs=300, lr=0.001, device=device\n",
    ")\n",
    "\n",
    "print(f\"Final Train Acc: {history_baseline['train_acc'][-1]:.4f}\")\n",
    "print(f\"Final Val Acc: {history_baseline['val_acc'][-1]:.4f}\")\n",
    "print(f\"\\nGap: {history_baseline['train_acc'][-1] - history_baseline['val_acc'][-1]:.4f}\")\n",
    "print(\"A large gap indicates OVERFITTING!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plot_overfitting",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualize overfitting\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
    "\n",
    "axes[0].plot(history_baseline['train_loss'], label='Train', linewidth=2)\n",
    "axes[0].plot(history_baseline['val_loss'], label='Validation', linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Loss')\n",
    "axes[0].set_title('Loss Curves - Overfitting Example')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "axes[1].plot(history_baseline['train_acc'], label='Train', linewidth=2)\n",
    "axes[1].plot(history_baseline['val_acc'], label='Validation', linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Accuracy')\n",
    "axes[1].set_title('Accuracy Curves - Overfitting Example')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(\"\\nNotice: Training metrics keep improving while validation metrics plateau or worsen.\")\n",
    "print(\"This is the classic sign of overfitting!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "l2_reg_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 2: L2 Regularization (Weight Decay)\n",
    "\n",
    "**L2 Regularization** adds a penalty proportional to the squared magnitude of weights:\n",
    "\n",
    "$$\\mathcal{L}_{L2}(\\theta) = \\mathcal{L}(\\theta) + \\frac{\\lambda}{2}\\sum_i \\theta_i^2$$\n",
    "\n",
    "**Key Properties:**\n",
    "- Encourages **small, distributed weights**\n",
    "- No single weight dominates\n",
    "- Also called \"Ridge\" regularization or \"Weight Decay\"\n",
    "\n",
    "In PyTorch, use the `weight_decay` parameter in optimizers!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "l2_implementation",
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_with_weight_decay(model, X_train, y_train, X_val, y_val, \n",
    "                            epochs=200, lr=0.01, weight_decay=0.0, device='cpu'):\n",
    "    \"\"\"Training function with L2 regularization via weight_decay.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    # weight_decay parameter implements L2 regularization!\n",
    "    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.LongTensor(y_val).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        loss = criterion(outputs, y_train_t)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        train_acc = (preds == y_train_t).float().mean().item()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_val_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['train_acc'].append(train_acc)\n",
    "        history['val_acc'].append(val_acc)\n",
    "    \n",
    "    return history\n",
    "\n",
    "\n",
    "# Compare different weight decay values\n",
    "weight_decays = [0, 0.001, 0.01, 0.1]\n",
    "results_wd = {}\n",
    "\n",
    "for wd in weight_decays:\n",
    "    model = BaselineClassifier(X_train_of.shape[1])\n",
    "    history = train_with_weight_decay(\n",
    "        model, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "        epochs=300, lr=0.001, weight_decay=wd, device=device\n",
    "    )\n",
    "    results_wd[wd] = history\n",
    "    print(f\"Weight Decay={wd}: Train Acc={history['train_acc'][-1]:.4f}, Val Acc={history['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plot_weight_decay",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot comparison\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "for wd in weight_decays:\n",
    "    axes[0].plot(results_wd[wd]['val_loss'], label=f'WD={wd}', linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation Loss')\n",
    "axes[0].set_title('Effect of L2 Regularization (Weight Decay)')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "for wd in weight_decays:\n",
    "    axes[1].plot(results_wd[wd]['val_acc'], label=f'WD={wd}', linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Validation Accuracy')\n",
    "axes[1].set_title('Validation Accuracy with Different Weight Decay')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dropout_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 3: Dropout\n",
    "\n",
    "**Dropout** randomly sets neurons to zero during training with probability $p$.\n",
    "\n",
    "**Key Concepts:**\n",
    "- Prevents neurons from **co-adapting** (relying too much on each other)\n",
    "- Acts like training an **ensemble** of networks\n",
    "- **Inverted dropout**: Scale surviving neurons by $\\frac{1}{1-p}$ during training\n",
    "- Must call `model.eval()` during inference to disable dropout!\n",
    "\n",
    "**Typical Dropout Rates:**\n",
    "- Fully connected layers: $p = 0.5$\n",
    "- Convolutional layers: $p = 0.1$ to $0.3$\n",
    "- Input layer: $p = 0.1$ to $0.2$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dropout_model",
   "metadata": {},
   "outputs": [],
   "source": [
    "class DropoutClassifier(nn.Module):\n",
    "    \"\"\"Model with dropout for regularization.\"\"\"\n",
    "    def __init__(self, input_size, hidden_size=128, dropout_rate=0.5):\n",
    "        super(DropoutClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.dropout1 = nn.Dropout(p=dropout_rate)\n",
    "        self.fc2 = nn.Linear(hidden_size, hidden_size)\n",
    "        self.dropout2 = nn.Dropout(p=dropout_rate)\n",
    "        self.fc3 = nn.Linear(hidden_size, 64)\n",
    "        self.dropout3 = nn.Dropout(p=dropout_rate)\n",
    "        self.fc4 = nn.Linear(64, 2)\n",
    "        self.relu = nn.ReLU()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu(self.fc1(x))\n",
    "        x = self.dropout1(x)  # Apply dropout after activation\n",
    "        x = self.relu(self.fc2(x))\n",
    "        x = self.dropout2(x)\n",
    "        x = self.relu(self.fc3(x))\n",
    "        x = self.dropout3(x)\n",
    "        return self.fc4(x)\n",
    "\n",
    "\n",
    "# Compare different dropout rates\n",
    "dropout_rates = [0.0, 0.2, 0.5, 0.7]\n",
    "results_dropout = {}\n",
    "\n",
    "for dr in dropout_rates:\n",
    "    model = DropoutClassifier(X_train_of.shape[1], dropout_rate=dr)\n",
    "    history = train_model_simple(\n",
    "        model, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "        epochs=300, lr=0.001, device=device\n",
    "    )\n",
    "    results_dropout[dr] = history\n",
    "    print(f\"Dropout={dr}: Train Acc={history['train_acc'][-1]:.4f}, Val Acc={history['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plot_dropout",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot dropout comparison\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "for dr in dropout_rates:\n",
    "    axes[0].plot(results_dropout[dr]['val_loss'], label=f'Dropout={dr}', linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation Loss')\n",
    "axes[0].set_title('Effect of Dropout Rate on Validation Loss')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Plot train vs val gap for each dropout rate\n",
    "gaps = []\n",
    "for dr in dropout_rates:\n",
    "    gap = results_dropout[dr]['train_acc'][-1] - results_dropout[dr]['val_acc'][-1]\n",
    "    gaps.append(gap)\n",
    "\n",
    "axes[1].bar([str(dr) for dr in dropout_rates], gaps, color=['red', 'orange', 'green', 'blue'])\n",
    "axes[1].set_xlabel('Dropout Rate')\n",
    "axes[1].set_ylabel('Train-Val Accuracy Gap')\n",
    "axes[1].set_title('Overfitting Gap (Lower is Better)')\n",
    "axes[1].axhline(y=0, color='k', linestyle='--', alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "batchnorm_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 4: Batch Normalization\n",
    "\n",
    "**Batch Normalization** normalizes layer inputs to stabilize training:\n",
    "\n",
    "$$\\hat{x}_i = \\frac{x_i - \\mu_B}{\\sqrt{\\sigma_B^2 + \\epsilon}}, \\quad y_i = \\gamma \\hat{x}_i + \\beta$$\n",
    "\n",
    "**Benefits:**\n",
    "- Enables **higher learning rates**\n",
    "- Reduces sensitivity to **weight initialization**\n",
    "- Acts as mild **regularizer**\n",
    "- Faster convergence\n",
    "\n",
    "**Important:** Use `model.eval()` during inference to use running statistics!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "batchnorm_model",
   "metadata": {},
   "outputs": [],
   "source": [
    "class BatchNormClassifier(nn.Module):\n",
    "    \"\"\"Model with Batch Normalization.\"\"\"\n",
    "    def __init__(self, input_size, hidden_size=128):\n",
    "        super(BatchNormClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.bn1 = nn.BatchNorm1d(hidden_size)\n",
    "        self.fc2 = nn.Linear(hidden_size, hidden_size)\n",
    "        self.bn2 = nn.BatchNorm1d(hidden_size)\n",
    "        self.fc3 = nn.Linear(hidden_size, 64)\n",
    "        self.bn3 = nn.BatchNorm1d(64)\n",
    "        self.fc4 = nn.Linear(64, 2)\n",
    "        self.relu = nn.ReLU()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu(self.bn1(self.fc1(x)))  # BN before or after activation\n",
    "        x = self.relu(self.bn2(self.fc2(x)))\n",
    "        x = self.relu(self.bn3(self.fc3(x)))\n",
    "        return self.fc4(x)\n",
    "\n",
    "\n",
    "# Compare with and without BatchNorm using higher learning rate\n",
    "learning_rates = [0.001, 0.01, 0.1]\n",
    "\n",
    "print(\"Training WITHOUT Batch Normalization:\")\n",
    "results_no_bn = {}\n",
    "for lr in learning_rates:\n",
    "    model = BaselineClassifier(X_train_of.shape[1])\n",
    "    history = train_model_simple(\n",
    "        model, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "        epochs=100, lr=lr, device=device\n",
    "    )\n",
    "    results_no_bn[lr] = history\n",
    "    print(f\"  LR={lr}: Final Val Acc={history['val_acc'][-1]:.4f}\")\n",
    "\n",
    "print(\"\\nTraining WITH Batch Normalization:\")\n",
    "results_bn = {}\n",
    "for lr in learning_rates:\n",
    "    model = BatchNormClassifier(X_train_of.shape[1])\n",
    "    history = train_model_simple(\n",
    "        model, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "        epochs=100, lr=lr, device=device\n",
    "    )\n",
    "    results_bn[lr] = history\n",
    "    print(f\"  LR={lr}: Final Val Acc={history['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plot_batchnorm",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot BatchNorm comparison\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "for lr in learning_rates:\n",
    "    axes[0].plot(results_no_bn[lr]['val_loss'], label=f'No BN, LR={lr}', linestyle='--')\n",
    "    axes[0].plot(results_bn[lr]['val_loss'], label=f'With BN, LR={lr}')\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation Loss')\n",
    "axes[0].set_title('BatchNorm Enables Higher Learning Rates')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "axes[0].set_ylim([0, 2])\n",
    "\n",
    "for lr in learning_rates:\n",
    "    axes[1].plot(results_bn[lr]['val_acc'], label=f'LR={lr}', linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Validation Accuracy')\n",
    "axes[1].set_title('Validation Accuracy with BatchNorm')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "early_stopping_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 5: Early Stopping\n",
    "\n",
    "**Early Stopping** monitors validation loss and stops training when it starts increasing.\n",
    "\n",
    "**Algorithm:**\n",
    "1. Track validation loss after each epoch\n",
    "2. If validation loss doesn't improve for `patience` epochs, stop\n",
    "3. Restore the best model weights"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "early_stopping_impl",
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_with_early_stopping(model, X_train, y_train, X_val, y_val, \n",
    "                               epochs=500, lr=0.01, patience=20, device='cpu'):\n",
    "    \"\"\"Training with early stopping.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=lr)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.LongTensor(y_val).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}\n",
    "    \n",
    "    best_val_loss = float('inf')\n",
    "    best_model_state = None\n",
    "    patience_counter = 0\n",
    "    stopped_epoch = epochs\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        # Training\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        loss = criterion(outputs, y_train_t)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        train_acc = (preds == y_train_t).float().mean().item()\n",
    "        \n",
    "        # Validation\n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_val_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['train_acc'].append(train_acc)\n",
    "        history['val_acc'].append(val_acc)\n",
    "        \n",
    "        # Early stopping check\n",
    "        if val_loss.item() < best_val_loss:\n",
    "            best_val_loss = val_loss.item()\n",
    "            best_model_state = model.state_dict().copy()\n",
    "            patience_counter = 0\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            if patience_counter >= patience:\n",
    "                stopped_epoch = epoch + 1\n",
    "                print(f\"Early stopping triggered at epoch {stopped_epoch}\")\n",
    "                break\n",
    "    \n",
    "    # Restore best model\n",
    "    if best_model_state:\n",
    "        model.load_state_dict(best_model_state)\n",
    "    \n",
    "    return history, stopped_epoch\n",
    "\n",
    "\n",
    "# Train with early stopping\n",
    "model_es = BaselineClassifier(X_train_of.shape[1])\n",
    "history_es, stopped = train_with_early_stopping(\n",
    "    model_es, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "    epochs=500, lr=0.001, patience=30, device=device\n",
    ")\n",
    "\n",
    "print(f\"\\nTraining stopped at epoch: {stopped}\")\n",
    "print(f\"Best validation accuracy: {max(history_es['val_acc']):.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plot_early_stopping",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot early stopping\n",
    "fig, ax = plt.subplots(figsize=(10, 5))\n",
    "\n",
    "ax.plot(history_es['train_loss'], label='Train Loss', linewidth=2)\n",
    "ax.plot(history_es['val_loss'], label='Validation Loss', linewidth=2)\n",
    "ax.axvline(x=stopped-1, color='r', linestyle='--', label=f'Early Stop (epoch {stopped})')\n",
    "\n",
    "# Mark best validation loss\n",
    "best_epoch = np.argmin(history_es['val_loss'])\n",
    "ax.scatter([best_epoch], [history_es['val_loss'][best_epoch]], \n",
    "           color='green', s=100, zorder=5, label=f'Best Model (epoch {best_epoch+1})')\n",
    "\n",
    "ax.set_xlabel('Epoch')\n",
    "ax.set_ylabel('Loss')\n",
    "ax.set_title('Early Stopping Prevents Overfitting')\n",
    "ax.legend()\n",
    "ax.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "optimizers_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Part 6: Optimization Algorithms\n",
    "\n",
    "Different optimizers have different properties:\n",
    "\n",
    "| Optimizer | Momentum | Adaptive LR | Best For |\n",
    "|-----------|----------|-------------|----------|\n",
    "| SGD | ✗ | ✗ | Simple problems |\n",
    "| SGD+Momentum | ✓ | ✗ | CNNs, vision |\n",
    "| AdaGrad | ✗ | ✓ | Sparse data |\n",
    "| RMSProp | ✗ | ✓ | RNNs |\n",
    "| Adam | ✓ | ✓ | Default choice |"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "optimizer_comparison",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load Wine dataset for optimizer comparison\n",
    "wine = load_wine()\n",
    "X_wine, y_wine = wine.data, wine.target\n",
    "\n",
    "X_train_w, X_test_w, y_train_w, y_test_w = train_test_split(\n",
    "    X_wine, y_wine, test_size=0.2, random_state=42, stratify=y_wine\n",
    ")\n",
    "\n",
    "scaler_w = StandardScaler()\n",
    "X_train_w = scaler_w.fit_transform(X_train_w)\n",
    "X_test_w = scaler_w.transform(X_test_w)\n",
    "\n",
    "\n",
    "class WineClassifier(nn.Module):\n",
    "    def __init__(self, input_size=13, num_classes=3):\n",
    "        super(WineClassifier, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, 64)\n",
    "        self.fc2 = nn.Linear(64, 32)\n",
    "        self.fc3 = nn.Linear(32, num_classes)\n",
    "        self.relu = nn.ReLU()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        x = self.relu(self.fc1(x))\n",
    "        x = self.relu(self.fc2(x))\n",
    "        return self.fc3(x)\n",
    "\n",
    "\n",
    "def train_with_optimizer(optimizer_class, optimizer_kwargs, epochs=100):\n",
    "    \"\"\"Train model with specified optimizer.\"\"\"\n",
    "    model = WineClassifier().to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optimizer_class(model.parameters(), **optimizer_kwargs)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train_w).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train_w).to(device)\n",
    "    X_test_t = torch.FloatTensor(X_test_w).to(device)\n",
    "    y_test_t = torch.LongTensor(y_test_w).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        loss = criterion(outputs, y_train_t)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_test_t)\n",
    "            val_loss = criterion(val_outputs, y_test_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_test_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['val_acc'].append(val_acc)\n",
    "    \n",
    "    return history\n",
    "\n",
    "\n",
    "# Compare optimizers\n",
    "optimizers = {\n",
    "    'SGD': (optim.SGD, {'lr': 0.01}),\n",
    "    'SGD+Momentum': (optim.SGD, {'lr': 0.01, 'momentum': 0.9}),\n",
    "    'RMSProp': (optim.RMSprop, {'lr': 0.001}),\n",
    "    'Adam': (optim.Adam, {'lr': 0.001}),\n",
    "    'AdamW': (optim.AdamW, {'lr': 0.001, 'weight_decay': 0.01}),\n",
    "}\n",
    "\n",
    "results_opt = {}\n",
    "for name, (opt_class, opt_kwargs) in optimizers.items():\n",
    "    history = train_with_optimizer(opt_class, opt_kwargs, epochs=150)\n",
    "    results_opt[name] = history\n",
    "    print(f\"{name}: Final Val Acc = {history['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "plot_optimizers",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plot optimizer comparison\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "for name in optimizers.keys():\n",
    "    axes[0].plot(results_opt[name]['train_loss'], label=name, linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Training Loss')\n",
    "axes[0].set_title('Training Loss by Optimizer')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "axes[0].set_ylim([0, 2])\n",
    "\n",
    "for name in optimizers.keys():\n",
    "    axes[1].plot(results_opt[name]['val_acc'], label=name, linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Validation Accuracy')\n",
    "axes[1].set_title('Validation Accuracy by Optimizer')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "momentum_visual",
   "metadata": {},
   "source": [
    "---\n",
    "## Understanding Momentum\n",
    "\n",
    "**Momentum** accumulates velocity in consistent gradient directions:\n",
    "\n",
    "$$v_t = \\beta v_{t-1} + \\nabla_\\theta \\mathcal{L}(\\theta_t)$$\n",
    "$$\\theta_{t+1} = \\theta_t - \\alpha v_t$$\n",
    "\n",
    "Where $\\beta$ is typically 0.9."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "momentum_demo",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Demonstrate momentum effect on a simple optimization\n",
    "def optimize_quadratic(optimizer_fn, lr, epochs=50, momentum=0):\n",
    "    \"\"\"Optimize f(x,y) = x^2 + 10*y^2 (elongated bowl).\"\"\"\n",
    "    x = torch.tensor([5.0], requires_grad=True)\n",
    "    y = torch.tensor([5.0], requires_grad=True)\n",
    "    \n",
    "    if momentum > 0:\n",
    "        optimizer = optimizer_fn([x, y], lr=lr, momentum=momentum)\n",
    "    else:\n",
    "        optimizer = optimizer_fn([x, y], lr=lr)\n",
    "    \n",
    "    path = [(x.item(), y.item())]\n",
    "    \n",
    "    for _ in range(epochs):\n",
    "        optimizer.zero_grad()\n",
    "        loss = x**2 + 10*y**2  # Elongated quadratic\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        path.append((x.item(), y.item()))\n",
    "    \n",
    "    return np.array(path)\n",
    "\n",
    "# Compare SGD with and without momentum\n",
    "path_sgd = optimize_quadratic(optim.SGD, lr=0.05, momentum=0)\n",
    "path_momentum = optimize_quadratic(optim.SGD, lr=0.05, momentum=0.9)\n",
    "\n",
    "# Plot optimization paths\n",
    "fig, ax = plt.subplots(figsize=(10, 8))\n",
    "\n",
    "# Create contour plot\n",
    "x_grid = np.linspace(-6, 6, 100)\n",
    "y_grid = np.linspace(-6, 6, 100)\n",
    "X_grid, Y_grid = np.meshgrid(x_grid, y_grid)\n",
    "Z = X_grid**2 + 10*Y_grid**2\n",
    "\n",
    "ax.contour(X_grid, Y_grid, Z, levels=30, cmap='viridis', alpha=0.5)\n",
    "ax.plot(path_sgd[:, 0], path_sgd[:, 1], 'r.-', label='SGD (no momentum)', markersize=8)\n",
    "ax.plot(path_momentum[:, 0], path_momentum[:, 1], 'b.-', label='SGD + Momentum', markersize=8)\n",
    "ax.scatter([0], [0], color='green', s=200, marker='*', zorder=5, label='Minimum')\n",
    "ax.scatter([5], [5], color='black', s=100, marker='o', zorder=5, label='Start')\n",
    "\n",
    "ax.set_xlabel('x')\n",
    "ax.set_ylabel('y')\n",
    "ax.set_title('Optimization Paths: SGD vs SGD with Momentum\\n(on elongated quadratic f(x,y) = x² + 10y²)')\n",
    "ax.legend()\n",
    "ax.set_aspect('equal')\n",
    "ax.grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(f\"SGD final position: ({path_sgd[-1, 0]:.4f}, {path_sgd[-1, 1]:.4f})\")\n",
    "print(f\"Momentum final position: ({path_momentum[-1, 0]:.4f}, {path_momentum[-1, 1]:.4f})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "exercises_header",
   "metadata": {},
   "source": [
    "---\n",
    "# Exercises - SOLUTIONS\n",
    "\n",
    "Complete the following exercises to demonstrate your understanding of regularization and optimization techniques."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex1_header",
   "metadata": {},
   "source": [
    "## Exercise 1: L1 vs L2 Regularization Comparison\n",
    "\n",
    "**L1 Regularization** (Lasso) encourages **sparse** weights (many zeros).\n",
    "\n",
    "**Tasks:**\n",
    "1. Implement manual L1 regularization by adding penalty to loss (5 marks)\n",
    "2. Compare L1, L2, and Elastic Net (L1+L2) on the overfitting dataset (6 marks)\n",
    "3. Analyze weight distributions and explain differences (4 marks)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex1_code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 1 SOLUTION: L1 vs L2 Regularization\n",
    "\n",
    "def train_with_l1_reg(model, X_train, y_train, X_val, y_val, \n",
    "                      epochs=200, lr=0.01, l1_lambda=0.001, device='cpu'):\n",
    "    \"\"\"Training with manual L1 regularization.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=lr)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.LongTensor(y_val).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        \n",
    "        # Base loss\n",
    "        base_loss = criterion(outputs, y_train_t)\n",
    "        \n",
    "        # SOLUTION: Add L1 penalty\n",
    "        l1_penalty = 0\n",
    "        for param in model.parameters():\n",
    "            l1_penalty += torch.abs(param).sum()\n",
    "        \n",
    "        loss = base_loss + l1_lambda * l1_penalty\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_val_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['val_acc'].append(val_acc)\n",
    "    \n",
    "    return history, model\n",
    "\n",
    "\n",
    "def train_with_elastic_net(model, X_train, y_train, X_val, y_val, \n",
    "                           epochs=200, lr=0.01, l1_lambda=0.001, l2_lambda=0.001, device='cpu'):\n",
    "    \"\"\"Training with Elastic Net (L1 + L2) regularization.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    optimizer = optim.Adam(model.parameters(), lr=lr)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.LongTensor(y_val).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        \n",
    "        base_loss = criterion(outputs, y_train_t)\n",
    "        \n",
    "        # Elastic Net: L1 + L2\n",
    "        l1_penalty = 0\n",
    "        l2_penalty = 0\n",
    "        for param in model.parameters():\n",
    "            l1_penalty += torch.abs(param).sum()\n",
    "            l2_penalty += (param ** 2).sum()\n",
    "        \n",
    "        loss = base_loss + l1_lambda * l1_penalty + l2_lambda * l2_penalty\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_val_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['val_acc'].append(val_acc)\n",
    "    \n",
    "    return history, model\n",
    "\n",
    "\n",
    "# SOLUTION: Train models with L1, L2, and Elastic Net\n",
    "print(\"Training with different regularization:\")\n",
    "\n",
    "# No regularization\n",
    "model_none = BaselineClassifier(X_train_of.shape[1])\n",
    "history_none = train_model_simple(model_none, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                   epochs=200, lr=0.001, device=device)\n",
    "print(f\"No Reg: Val Acc = {history_none['val_acc'][-1]:.4f}\")\n",
    "\n",
    "# L1 regularization\n",
    "model_l1 = BaselineClassifier(X_train_of.shape[1])\n",
    "history_l1, model_l1 = train_with_l1_reg(model_l1, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                          epochs=200, lr=0.001, l1_lambda=0.001, device=device)\n",
    "print(f\"L1: Val Acc = {history_l1['val_acc'][-1]:.4f}\")\n",
    "\n",
    "# L2 regularization\n",
    "model_l2 = BaselineClassifier(X_train_of.shape[1])\n",
    "history_l2 = train_with_weight_decay(model_l2, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                      epochs=200, lr=0.001, weight_decay=0.01, device=device)\n",
    "print(f\"L2: Val Acc = {history_l2['val_acc'][-1]:.4f}\")\n",
    "\n",
    "# Elastic Net\n",
    "model_en = BaselineClassifier(X_train_of.shape[1])\n",
    "history_en, model_en = train_with_elastic_net(model_en, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                               epochs=200, lr=0.001, l1_lambda=0.0005, l2_lambda=0.005, device=device)\n",
    "print(f\"Elastic Net: Val Acc = {history_en['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex1_plots",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION: Plot comparison and weight distributions\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "# Validation accuracy comparison\n",
    "axes[0].plot(history_none['val_acc'], label='No Reg', linewidth=2)\n",
    "axes[0].plot(history_l1['val_acc'], label='L1', linewidth=2)\n",
    "axes[0].plot(history_l2['val_acc'], label='L2', linewidth=2)\n",
    "axes[0].plot(history_en['val_acc'], label='Elastic Net', linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation Accuracy')\n",
    "axes[0].set_title('Regularization Comparison')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Weight distribution for L1 model (sparse)\n",
    "l1_weights = []\n",
    "for param in model_l1.parameters():\n",
    "    l1_weights.extend(param.detach().cpu().numpy().flatten())\n",
    "axes[1].hist(l1_weights, bins=50, alpha=0.7, color='blue', edgecolor='black')\n",
    "axes[1].set_xlabel('Weight Value')\n",
    "axes[1].set_ylabel('Count')\n",
    "axes[1].set_title(f'L1 Weight Distribution\\n(Near-zero: {np.sum(np.abs(l1_weights) < 0.01)/len(l1_weights)*100:.1f}%)')\n",
    "axes[1].axvline(x=0, color='r', linestyle='--')\n",
    "\n",
    "# Weight distribution for L2 model (small but not sparse)\n",
    "l2_weights = []\n",
    "for param in model_l2.parameters():\n",
    "    l2_weights.extend(param.detach().cpu().numpy().flatten())\n",
    "axes[2].hist(l2_weights, bins=50, alpha=0.7, color='green', edgecolor='black')\n",
    "axes[2].set_xlabel('Weight Value')\n",
    "axes[2].set_ylabel('Count')\n",
    "axes[2].set_title(f'L2 Weight Distribution\\n(Near-zero: {np.sum(np.abs(l2_weights) < 0.01)/len(l2_weights)*100:.1f}%)')\n",
    "axes[2].axvline(x=0, color='r', linestyle='--')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex1_analysis",
   "metadata": {},
   "source": [
    "**Analysis - SOLUTION:**\n",
    "\n",
    "**Differences between L1 and L2 regularization:**\n",
    "\n",
    "1. **L1 (Lasso) Regularization:**\n",
    "   - Produces **sparse weights** - many weights become exactly or nearly zero\n",
    "   - Acts as **feature selection** - effectively eliminates unimportant features\n",
    "   - The penalty gradient is constant (±λ), pushing weights to exactly zero\n",
    "   - Better when you suspect many features are irrelevant\n",
    "\n",
    "2. **L2 (Ridge) Regularization:**\n",
    "   - Produces **small but non-zero weights** - weights shrink but rarely become exactly zero\n",
    "   - Distributes importance across all features\n",
    "   - The penalty gradient is proportional to weight magnitude (2λw), so large weights shrink faster\n",
    "   - Better when all features contribute some information\n",
    "\n",
    "3. **Elastic Net (L1 + L2):**\n",
    "   - Combines benefits of both: some sparsity with stability\n",
    "   - L2 term helps with correlated features (where L1 alone might be unstable)\n",
    "   - Often works well in practice as a compromise\n",
    "\n",
    "**Observed Results:**\n",
    "- L1 shows more weights concentrated near zero (sparsity)\n",
    "- L2 shows a more Gaussian distribution of small weights\n",
    "- Both improve generalization compared to no regularization"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex2_header",
   "metadata": {},
   "source": [
    "## Exercise 2: Dropout + Batch Normalization Combined\n",
    "\n",
    "**Tasks:**\n",
    "1. Create a model that combines Dropout AND BatchNorm (5 marks)\n",
    "2. Experiment with the order: BN before Dropout vs Dropout before BN (5 marks)\n",
    "3. Compare results and explain which order works better and why (5 marks)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex2_code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 2 SOLUTION: Dropout + BatchNorm Combined\n",
    "\n",
    "class BNThenDropout(nn.Module):\n",
    "    \"\"\"Model with BatchNorm BEFORE Dropout.\"\"\"\n",
    "    def __init__(self, input_size, hidden_size=128, dropout_rate=0.3):\n",
    "        super(BNThenDropout, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.bn1 = nn.BatchNorm1d(hidden_size)\n",
    "        self.dropout1 = nn.Dropout(p=dropout_rate)\n",
    "        \n",
    "        self.fc2 = nn.Linear(hidden_size, hidden_size)\n",
    "        self.bn2 = nn.BatchNorm1d(hidden_size)\n",
    "        self.dropout2 = nn.Dropout(p=dropout_rate)\n",
    "        \n",
    "        self.fc3 = nn.Linear(hidden_size, 64)\n",
    "        self.bn3 = nn.BatchNorm1d(64)\n",
    "        self.dropout3 = nn.Dropout(p=dropout_rate)\n",
    "        \n",
    "        self.fc4 = nn.Linear(64, 2)\n",
    "        self.relu = nn.ReLU()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        # Order: Linear -> BN -> ReLU -> Dropout\n",
    "        x = self.dropout1(self.relu(self.bn1(self.fc1(x))))\n",
    "        x = self.dropout2(self.relu(self.bn2(self.fc2(x))))\n",
    "        x = self.dropout3(self.relu(self.bn3(self.fc3(x))))\n",
    "        return self.fc4(x)\n",
    "\n",
    "\n",
    "class DropoutThenBN(nn.Module):\n",
    "    \"\"\"Model with Dropout BEFORE BatchNorm.\"\"\"\n",
    "    def __init__(self, input_size, hidden_size=128, dropout_rate=0.3):\n",
    "        super(DropoutThenBN, self).__init__()\n",
    "        self.fc1 = nn.Linear(input_size, hidden_size)\n",
    "        self.dropout1 = nn.Dropout(p=dropout_rate)\n",
    "        self.bn1 = nn.BatchNorm1d(hidden_size)\n",
    "        \n",
    "        self.fc2 = nn.Linear(hidden_size, hidden_size)\n",
    "        self.dropout2 = nn.Dropout(p=dropout_rate)\n",
    "        self.bn2 = nn.BatchNorm1d(hidden_size)\n",
    "        \n",
    "        self.fc3 = nn.Linear(hidden_size, 64)\n",
    "        self.dropout3 = nn.Dropout(p=dropout_rate)\n",
    "        self.bn3 = nn.BatchNorm1d(64)\n",
    "        \n",
    "        self.fc4 = nn.Linear(64, 2)\n",
    "        self.relu = nn.ReLU()\n",
    "    \n",
    "    def forward(self, x):\n",
    "        # Order: Linear -> ReLU -> Dropout -> BN\n",
    "        x = self.bn1(self.dropout1(self.relu(self.fc1(x))))\n",
    "        x = self.bn2(self.dropout2(self.relu(self.fc2(x))))\n",
    "        x = self.bn3(self.dropout3(self.relu(self.fc3(x))))\n",
    "        return self.fc4(x)\n",
    "\n",
    "\n",
    "# SOLUTION: Train both models and compare\n",
    "print(\"Comparing BN + Dropout ordering:\")\n",
    "\n",
    "# BN then Dropout\n",
    "model_bn_do = BNThenDropout(X_train_of.shape[1])\n",
    "history_bn_do = train_model_simple(model_bn_do, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                    epochs=200, lr=0.001, device=device)\n",
    "print(f\"BN -> Dropout: Val Acc = {max(history_bn_do['val_acc']):.4f}\")\n",
    "\n",
    "# Dropout then BN\n",
    "model_do_bn = DropoutThenBN(X_train_of.shape[1])\n",
    "history_do_bn = train_model_simple(model_do_bn, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                    epochs=200, lr=0.001, device=device)\n",
    "print(f\"Dropout -> BN: Val Acc = {max(history_do_bn['val_acc']):.4f}\")\n",
    "\n",
    "# Plot comparison\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n",
    "\n",
    "axes[0].plot(history_bn_do['val_loss'], label='BN → Dropout', linewidth=2)\n",
    "axes[0].plot(history_do_bn['val_loss'], label='Dropout → BN', linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation Loss')\n",
    "axes[0].set_title('Validation Loss: BN + Dropout Ordering')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "axes[1].plot(history_bn_do['val_acc'], label='BN → Dropout', linewidth=2)\n",
    "axes[1].plot(history_do_bn['val_acc'], label='Dropout → BN', linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Validation Accuracy')\n",
    "axes[1].set_title('Validation Accuracy: BN + Dropout Ordering')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex2_analysis",
   "metadata": {},
   "source": [
    "**Analysis  - SOLUTION:**\n",
    "\n",
    "**Which order works better: BN→Dropout or Dropout→BN?**\n",
    "\n",
    "**Recommended order: BatchNorm BEFORE Dropout (or avoid combining them)**\n",
    "\n",
    "**Reasons:**\n",
    "\n",
    "1. **BatchNorm statistics issue:**\n",
    "   - BatchNorm computes mean and variance from the batch\n",
    "   - During training with Dropout, some activations are zeroed out\n",
    "   - If Dropout is applied BEFORE BatchNorm, the statistics are computed on partially-zeroed data\n",
    "   - At inference (no dropout), the statistics mismatch causes problems\n",
    "\n",
    "2. **Why BN→Dropout is better:**\n",
    "   - BatchNorm normalizes the full activations first\n",
    "   - Then Dropout randomly zeros some (already normalized) values\n",
    "   - The running statistics in BN are consistent between train and test\n",
    "\n",
    "3. **Modern practice:**\n",
    "   - Many modern architectures use BatchNorm WITHOUT Dropout\n",
    "   - BatchNorm itself has a regularizing effect\n",
    "   - If using both, BN→Dropout is the safer choice\n",
    "   - Consider using lower dropout rates (0.1-0.2) when combined with BN\n",
    "\n",
    "4. **Alternative approaches:**\n",
    "   - Use dropout only in final layers\n",
    "   - Use DropBlock for CNNs\n",
    "   - Rely on BatchNorm's implicit regularization"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex3_header",
   "metadata": {},
   "source": [
    "## Exercise 3: Optimizer Hyperparameter Tuning\n",
    "\n",
    "**Tasks:**\n",
    "1. For Adam optimizer, compare different β1 and β2 values (5 marks)\n",
    "2. For SGD+Momentum, compare different momentum values (0.5, 0.9, 0.99) (5 marks)\n",
    "3. Create a summary table and recommend best settings (5 marks)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex3_code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 3 SOLUTION: Optimizer Hyperparameter Tuning\n",
    "\n",
    "# SOLUTION: Experiment with different Adam beta values\n",
    "adam_configs = [\n",
    "    {'betas': (0.9, 0.999), 'name': 'Default (0.9, 0.999)'},\n",
    "    {'betas': (0.5, 0.999), 'name': 'Low β1 (0.5, 0.999)'},\n",
    "    {'betas': (0.9, 0.99), 'name': 'Low β2 (0.9, 0.99)'},\n",
    "    {'betas': (0.95, 0.9999), 'name': 'High (0.95, 0.9999)'},\n",
    "]\n",
    "\n",
    "results_adam = {}\n",
    "print(\"Adam beta comparison:\")\n",
    "for config in adam_configs:\n",
    "    model = WineClassifier()\n",
    "    history = train_with_optimizer(optim.Adam, {'lr': 0.001, 'betas': config['betas']}, epochs=100)\n",
    "    results_adam[config['name']] = history\n",
    "    print(f\"  {config['name']}: Val Acc = {history['val_acc'][-1]:.4f}\")\n",
    "\n",
    "# SOLUTION: Experiment with different momentum values for SGD\n",
    "momentum_values = [0.0, 0.5, 0.9, 0.99]\n",
    "\n",
    "results_momentum = {}\n",
    "print(\"\\nSGD momentum comparison:\")\n",
    "for mom in momentum_values:\n",
    "    model = WineClassifier()\n",
    "    if mom > 0:\n",
    "        history = train_with_optimizer(optim.SGD, {'lr': 0.01, 'momentum': mom}, epochs=100)\n",
    "    else:\n",
    "        history = train_with_optimizer(optim.SGD, {'lr': 0.01}, epochs=100)\n",
    "    results_momentum[mom] = history\n",
    "    print(f\"  Momentum={mom}: Val Acc = {history['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex3_plots",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION: Plot comparisons\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "# Adam comparison\n",
    "for name in results_adam.keys():\n",
    "    axes[0].plot(results_adam[name]['val_acc'], label=name, linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation Accuracy')\n",
    "axes[0].set_title('Adam: Effect of β1 and β2')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Momentum comparison\n",
    "for mom in momentum_values:\n",
    "    axes[1].plot(results_momentum[mom]['val_acc'], label=f'Momentum={mom}', linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Validation Accuracy')\n",
    "axes[1].set_title('SGD: Effect of Momentum')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex3_analysis",
   "metadata": {},
   "source": [
    "**Summary and Recommendations - SOLUTION:**\n",
    "\n",
    "| Setting | Best Value | Notes |\n",
    "|---------|------------|-------|\n",
    "| Adam β1 | 0.9 (default) | Controls momentum for gradients. Lower values = more responsive but noisier |\n",
    "| Adam β2 | 0.999 (default) | Controls momentum for squared gradients. Very stable at default |\n",
    "| SGD Momentum | 0.9 | Good balance. 0.99 can overshoot, 0.5 is too weak |\n",
    "| Learning Rate | 0.001 (Adam), 0.01 (SGD) | Adam typically needs lower LR |\n",
    "\n",
    "**Recommendations:**\n",
    "\n",
    "1. **Start with defaults:** Adam with β1=0.9, β2=0.999 works well for most cases\n",
    "\n",
    "2. **For SGD:** Use momentum=0.9 as the standard choice\n",
    "\n",
    "3. **When to adjust:**\n",
    "   - Lower β1 (0.5-0.8) if training is unstable with noisy gradients\n",
    "   - Higher momentum (0.95-0.99) for very smooth loss landscapes\n",
    "   - Lower momentum (0.5-0.8) if experiencing oscillations\n",
    "\n",
    "4. **AdamW is preferred** over Adam with weight_decay for better generalization"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex4_header",
   "metadata": {},
   "source": [
    "## Exercise 4: Complete Regularized Model\n",
    "\n",
    "Build a well-regularized model combining multiple techniques:\n",
    "\n",
    "**Tasks:**\n",
    "1. Create a model with: BatchNorm, Dropout, and proper initialization (6 marks)\n",
    "2. Train with: Adam optimizer with weight decay, early stopping (6 marks)\n",
    "3. Apply learning rate scheduling (4 marks)\n",
    "4. Compare with baseline and report improvement (4 marks)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex4_code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 4 SOLUTION: Complete Regularized Model\n",
    "\n",
    "class FullyRegularizedModel(nn.Module):\n",
    "    \"\"\"Model with all regularization techniques.\"\"\"\n",
    "    def __init__(self, input_size, hidden_sizes=[128, 64, 32], \n",
    "                 num_classes=2, dropout_rate=0.3):\n",
    "        super(FullyRegularizedModel, self).__init__()\n",
    "        \n",
    "        layers = []\n",
    "        prev_size = input_size\n",
    "        \n",
    "        for hidden_size in hidden_sizes:\n",
    "            layers.append(nn.Linear(prev_size, hidden_size))\n",
    "            layers.append(nn.BatchNorm1d(hidden_size))\n",
    "            layers.append(nn.ReLU())\n",
    "            layers.append(nn.Dropout(p=dropout_rate))\n",
    "            prev_size = hidden_size\n",
    "        \n",
    "        layers.append(nn.Linear(prev_size, num_classes))\n",
    "        \n",
    "        self.network = nn.Sequential(*layers)\n",
    "        \n",
    "        # Apply proper weight initialization (He/Kaiming for ReLU)\n",
    "        self._init_weights()\n",
    "    \n",
    "    def _init_weights(self):\n",
    "        for m in self.modules():\n",
    "            if isinstance(m, nn.Linear):\n",
    "                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')\n",
    "                if m.bias is not None:\n",
    "                    nn.init.constant_(m.bias, 0)\n",
    "            elif isinstance(m, nn.BatchNorm1d):\n",
    "                nn.init.constant_(m.weight, 1)\n",
    "                nn.init.constant_(m.bias, 0)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.network(x)\n",
    "\n",
    "\n",
    "def train_fully_regularized(model, X_train, y_train, X_val, y_val,\n",
    "                            epochs=300, lr=0.001, weight_decay=0.01,\n",
    "                            patience=30, device='cpu'):\n",
    "    \"\"\"Training with all regularization techniques.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.CrossEntropyLoss()\n",
    "    \n",
    "    # AdamW optimizer with weight decay\n",
    "    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)\n",
    "    \n",
    "    # Cosine annealing scheduler\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.LongTensor(y_train).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.LongTensor(y_val).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': [], 'lr': []}\n",
    "    \n",
    "    best_val_acc = 0\n",
    "    best_model_state = None\n",
    "    patience_counter = 0\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        loss = criterion(outputs, y_train_t)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        scheduler.step()\n",
    "        \n",
    "        _, preds = torch.max(outputs, 1)\n",
    "        train_acc = (preds == y_train_t).float().mean().item()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            _, val_preds = torch.max(val_outputs, 1)\n",
    "            val_acc = (val_preds == y_val_t).float().mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['train_acc'].append(train_acc)\n",
    "        history['val_acc'].append(val_acc)\n",
    "        history['lr'].append(optimizer.param_groups[0]['lr'])\n",
    "        \n",
    "        # Early stopping based on validation accuracy\n",
    "        if val_acc > best_val_acc:\n",
    "            best_val_acc = val_acc\n",
    "            best_model_state = model.state_dict().copy()\n",
    "            patience_counter = 0\n",
    "        else:\n",
    "            patience_counter += 1\n",
    "            if patience_counter >= patience:\n",
    "                print(f\"Early stopping at epoch {epoch + 1}\")\n",
    "                break\n",
    "    \n",
    "    if best_model_state:\n",
    "        model.load_state_dict(best_model_state)\n",
    "    \n",
    "    return history\n",
    "\n",
    "\n",
    "# SOLUTION: Train and compare with baseline\n",
    "print(\"Training fully regularized model:\")\n",
    "model_full = FullyRegularizedModel(X_train_of.shape[1], hidden_sizes=[128, 64, 32], \n",
    "                                    num_classes=2, dropout_rate=0.3)\n",
    "history_full = train_fully_regularized(model_full, X_train_of, y_train_of, X_test_of, y_test_of,\n",
    "                                        epochs=300, lr=0.001, weight_decay=0.01,\n",
    "                                        patience=50, device=device)\n",
    "\n",
    "print(f\"\\nComparison:\")\n",
    "print(f\"Baseline: Train Acc = {history_baseline['train_acc'][-1]:.4f}, Val Acc = {history_baseline['val_acc'][-1]:.4f}\")\n",
    "print(f\"Full Reg: Train Acc = {history_full['train_acc'][-1]:.4f}, Val Acc = {max(history_full['val_acc']):.4f}\")\n",
    "print(f\"\\nImprovement: {max(history_full['val_acc']) - history_baseline['val_acc'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex4_plots",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION: Plot comparison\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "# Training loss comparison\n",
    "axes[0].plot(history_baseline['train_loss'], label='Baseline', linewidth=2)\n",
    "axes[0].plot(history_full['train_loss'], label='Fully Regularized', linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Training Loss')\n",
    "axes[0].set_title('Training Loss')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Validation accuracy comparison\n",
    "axes[1].plot(history_baseline['val_acc'], label='Baseline', linewidth=2)\n",
    "axes[1].plot(history_full['val_acc'], label='Fully Regularized', linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Validation Accuracy')\n",
    "axes[1].set_title('Validation Accuracy')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "# Overfitting gap\n",
    "baseline_gap = [t - v for t, v in zip(history_baseline['train_acc'], history_baseline['val_acc'])]\n",
    "full_gap = [t - v for t, v in zip(history_full['train_acc'], history_full['val_acc'])]\n",
    "\n",
    "axes[2].plot(baseline_gap, label='Baseline', linewidth=2)\n",
    "axes[2].plot(full_gap, label='Fully Regularized', linewidth=2)\n",
    "axes[2].set_xlabel('Epoch')\n",
    "axes[2].set_ylabel('Train - Val Accuracy')\n",
    "axes[2].set_title('Overfitting Gap (Lower is Better)')\n",
    "axes[2].axhline(y=0, color='k', linestyle='--', alpha=0.3)\n",
    "axes[2].legend()\n",
    "axes[2].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ex5_header",
   "metadata": {},
   "source": [
    "## Exercise 5: California Housing with Regularization\n",
    "\n",
    "Apply regularization techniques to a regression problem.\n",
    "\n",
    "**Tasks:**\n",
    "1. Load California Housing dataset (2 marks)\n",
    "2. Build a regularized regression model (6 marks)\n",
    "3. Compare different regularization combinations (6 marks)\n",
    "4. Report MAE and create visualizations (6 marks)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex5_code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Exercise 5 SOLUTION: California Housing Regression\n",
    "\n",
    "# Load data\n",
    "cal_housing = fetch_california_housing()\n",
    "X_cal, y_cal = cal_housing.data, cal_housing.target\n",
    "\n",
    "X_train_cal, X_test_cal, y_train_cal, y_test_cal = train_test_split(\n",
    "    X_cal, y_cal, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "scaler_cal = StandardScaler()\n",
    "X_train_cal = scaler_cal.fit_transform(X_train_cal)\n",
    "X_test_cal = scaler_cal.transform(X_test_cal)\n",
    "\n",
    "print(f\"Training samples: {X_train_cal.shape[0]}\")\n",
    "print(f\"Features: {X_train_cal.shape[1]}\")\n",
    "print(f\"Target range: {y_train_cal.min():.2f} to {y_train_cal.max():.2f}\")\n",
    "\n",
    "\n",
    "class RegularizedRegressor(nn.Module):\n",
    "    \"\"\"Regularized regression model.\"\"\"\n",
    "    def __init__(self, input_size, hidden_sizes=[64, 32], dropout_rate=0.2, use_bn=True):\n",
    "        super(RegularizedRegressor, self).__init__()\n",
    "        \n",
    "        layers = []\n",
    "        prev_size = input_size\n",
    "        \n",
    "        for hidden_size in hidden_sizes:\n",
    "            layers.append(nn.Linear(prev_size, hidden_size))\n",
    "            if use_bn:\n",
    "                layers.append(nn.BatchNorm1d(hidden_size))\n",
    "            layers.append(nn.ReLU())\n",
    "            if dropout_rate > 0:\n",
    "                layers.append(nn.Dropout(p=dropout_rate))\n",
    "            prev_size = hidden_size\n",
    "        \n",
    "        layers.append(nn.Linear(prev_size, 1))\n",
    "        self.network = nn.Sequential(*layers)\n",
    "    \n",
    "    def forward(self, x):\n",
    "        return self.network(x)\n",
    "\n",
    "\n",
    "def train_regressor(model, X_train, y_train, X_val, y_val,\n",
    "                    epochs=100, lr=0.001, weight_decay=0.0, device='cpu'):\n",
    "    \"\"\"Train regression model.\"\"\"\n",
    "    model = model.to(device)\n",
    "    criterion = nn.MSELoss()\n",
    "    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)\n",
    "    \n",
    "    X_train_t = torch.FloatTensor(X_train).to(device)\n",
    "    y_train_t = torch.FloatTensor(y_train).unsqueeze(1).to(device)\n",
    "    X_val_t = torch.FloatTensor(X_val).to(device)\n",
    "    y_val_t = torch.FloatTensor(y_val).unsqueeze(1).to(device)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_mae': []}\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(X_train_t)\n",
    "        loss = criterion(outputs, y_train_t)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_outputs = model(X_val_t)\n",
    "            val_loss = criterion(val_outputs, y_val_t)\n",
    "            val_mae = torch.abs(val_outputs - y_val_t).mean().item()\n",
    "        \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(val_loss.item())\n",
    "        history['val_mae'].append(val_mae)\n",
    "    \n",
    "    return history, model\n",
    "\n",
    "\n",
    "# SOLUTION: Compare different regularization strategies\n",
    "configs = [\n",
    "    {'name': 'No Reg', 'dropout': 0.0, 'use_bn': False, 'wd': 0.0},\n",
    "    {'name': 'Dropout Only', 'dropout': 0.3, 'use_bn': False, 'wd': 0.0},\n",
    "    {'name': 'BatchNorm Only', 'dropout': 0.0, 'use_bn': True, 'wd': 0.0},\n",
    "    {'name': 'BN + Dropout', 'dropout': 0.2, 'use_bn': True, 'wd': 0.0},\n",
    "    {'name': 'Full (BN+DO+WD)', 'dropout': 0.2, 'use_bn': True, 'wd': 0.01},\n",
    "]\n",
    "\n",
    "results_reg = {}\n",
    "models_reg = {}\n",
    "\n",
    "print(\"Comparing regularization strategies for regression:\")\n",
    "for config in configs:\n",
    "    model = RegularizedRegressor(X_train_cal.shape[1], hidden_sizes=[64, 32],\n",
    "                                  dropout_rate=config['dropout'], use_bn=config['use_bn'])\n",
    "    history, trained_model = train_regressor(model, X_train_cal, y_train_cal, \n",
    "                                              X_test_cal, y_test_cal,\n",
    "                                              epochs=100, lr=0.001, \n",
    "                                              weight_decay=config['wd'], device=device)\n",
    "    results_reg[config['name']] = history\n",
    "    models_reg[config['name']] = trained_model\n",
    "    print(f\"{config['name']}: Final MAE = {history['val_mae'][-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex5_plots",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION: Plot results\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "# Validation MAE\n",
    "for name in results_reg.keys():\n",
    "    axes[0].plot(results_reg[name]['val_mae'], label=name, linewidth=2)\n",
    "axes[0].set_xlabel('Epoch')\n",
    "axes[0].set_ylabel('Validation MAE')\n",
    "axes[0].set_title('Validation MAE by Regularization')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Training loss\n",
    "for name in results_reg.keys():\n",
    "    axes[1].plot(results_reg[name]['train_loss'], label=name, linewidth=2)\n",
    "axes[1].set_xlabel('Epoch')\n",
    "axes[1].set_ylabel('Training Loss (MSE)')\n",
    "axes[1].set_title('Training Loss by Regularization')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "# Final MAE comparison\n",
    "final_maes = [results_reg[name]['val_mae'][-1] for name in results_reg.keys()]\n",
    "colors = ['red' if mae == max(final_maes) else 'green' if mae == min(final_maes) else 'blue' \n",
    "          for mae in final_maes]\n",
    "axes[2].bar(list(results_reg.keys()), final_maes, color=colors)\n",
    "axes[2].set_xlabel('Regularization Strategy')\n",
    "axes[2].set_ylabel('Final Validation MAE')\n",
    "axes[2].set_title('Final MAE Comparison (Lower is Better)')\n",
    "axes[2].tick_params(axis='x', rotation=45)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ex6_predictions",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SOLUTION: Predictions visualization for best model\n",
    "best_model_name = min(results_reg.keys(), key=lambda x: results_reg[x]['val_mae'][-1])\n",
    "best_model = models_reg[best_model_name]\n",
    "\n",
    "best_model.eval()\n",
    "with torch.no_grad():\n",
    "    X_test_t = torch.FloatTensor(X_test_cal).to(device)\n",
    "    predictions = best_model(X_test_t).cpu().numpy().flatten()\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
    "\n",
    "# Predicted vs Actual\n",
    "axes[0].scatter(y_test_cal, predictions, alpha=0.3, s=10)\n",
    "axes[0].plot([y_test_cal.min(), y_test_cal.max()], \n",
    "             [y_test_cal.min(), y_test_cal.max()], 'r--', linewidth=2)\n",
    "axes[0].set_xlabel('Actual Values')\n",
    "axes[0].set_ylabel('Predicted Values')\n",
    "axes[0].set_title(f'Predictions vs Actual ({best_model_name})')\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Residual distribution\n",
    "residuals = predictions - y_test_cal\n",
    "axes[1].hist(residuals, bins=50, alpha=0.7, edgecolor='black')\n",
    "axes[1].axvline(x=0, color='r', linestyle='--', linewidth=2)\n",
    "axes[1].set_xlabel('Residual (Predicted - Actual)')\n",
    "axes[1].set_ylabel('Count')\n",
    "axes[1].set_title(f'Residual Distribution (MAE: {np.mean(np.abs(residuals)):.4f})')\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(f\"\\nBest Model: {best_model_name}\")\n",
    "print(f\"Test MAE: {np.mean(np.abs(residuals)):.4f}\")\n",
    "print(f\"Test RMSE: {np.sqrt(np.mean(residuals**2)):.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "summary",
   "metadata": {},
   "source": [
    "---\n",
    "# Summary\n",
    "\n",
    "## Key Concepts Covered\n",
    "\n",
    "**Regularization Techniques:**\n",
    "- L1 (Lasso): Sparse weights, feature selection\n",
    "- L2 (Ridge/Weight Decay): Small, distributed weights\n",
    "- Early Stopping: Stop when validation loss increases\n",
    "- Dropout: Random neuron dropping, prevents co-adaptation\n",
    "- Batch Normalization: Normalize layer inputs, enables higher LR\n",
    "\n",
    "**Optimization Algorithms:**\n",
    "- SGD: Basic gradient descent\n",
    "- Momentum: Accumulates velocity, faster convergence\n",
    "- Adam: Adaptive learning rates + momentum\n",
    "- AdamW: Adam with decoupled weight decay\n",
    "\n",
    "## Key Equations\n",
    "\n",
    "| Method | Update Rule |\n",
    "|--------|-------------|\n",
    "| L2 Regularization | $\\mathcal{L}_{reg} = \\mathcal{L} + \\frac{\\lambda}{2}\\|\\theta\\|_2^2$ |\n",
    "| Dropout | $\\tilde{h} = \\frac{m \\odot h}{1-p}$, $m \\sim \\text{Bernoulli}(1-p)$ |\n",
    "| Batch Norm | $\\hat{x} = \\frac{x - \\mu_B}{\\sqrt{\\sigma_B^2 + \\epsilon}}$, $y = \\gamma\\hat{x} + \\beta$ |\n",
    "| SGD + Momentum | $v_t = \\beta v_{t-1} + g_t$, $\\theta_{t+1} = \\theta_t - \\alpha v_t$ |\n",
    "| Adam | $\\theta_{t+1} = \\theta_t - \\frac{\\alpha}{\\sqrt{\\hat{v}_t} + \\epsilon}\\hat{m}_t$ |\n",
    "\n",
    "## Important Reminders\n",
    "\n",
    "- Use `model.train()` during training (dropout ON, BN uses batch stats)\n",
    "- Use `model.eval()` during inference (dropout OFF, BN uses running stats)\n",
    "- Always use `torch.no_grad()` during evaluation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28439bc5",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
